// Copyright (C) 2026 Sascha Ittner <sascha.ittner@modusoft.de>
// License: GPL Version 2
package cgen

import (
	"fmt"
	"io"
	"strings"

	"github.com/stratuMAK/stratumak/src/stmak/internal/gmicompile/ast"
)

// GenerateClientTS writes a TypeScript REST client module for calling the API
// over HTTP/JSON. Uses the Fetch API (browser/Node 18+).
func GenerateClientTS(w io.Writer, api *ast.API) error {
	g := &clientTSGen{w: w, api: api}
	return g.generate()
}

type clientTSGen struct {
	w         io.Writer
	api       *ast.API
	err       error
	reviveSet map[string]bool
}

func (g *clientTSGen) printf(format string, args ...interface{}) {
	if g.err != nil {
		return
	}
	_, g.err = fmt.Fprintf(g.w, format, args...)
}

func (g *clientTSGen) generate() error {
	// The REST client serves everything but the watch functions.
	g.reviveSet = tsReviveUsedSet(g.api, tsReviveSet(g.api), func(fn ast.Func) bool { return !fn.Watch })
	g.emitHeader()
	g.emitConstants()
	g.emitEnums()
	g.emitInterfaces()
	emitTSRevivers(g.printf, g.api, g.reviveSet)
	g.emitClient()
	g.emitClientMethods()
	g.printf("}\n")
	return g.err
}

// --- Header ---

func (g *clientTSGen) emitHeader() {
	g.printf("// Code generated by modcompile gmi --client-ts - DO NOT EDIT.\n")
	EmitMeta(g.w, g.api, "//")
	g.printf("//\n")
	g.printf("// REST client for %s API v%d\n\n", g.api.Name, g.api.Version)
}

// --- Constants ---

func (g *clientTSGen) emitConstants() {
	if len(g.api.Consts) == 0 {
		return
	}
	g.printf("// --- Constants ---\n\n")
	for _, c := range g.api.Consts {
		g.printf("export const %s = %d;\n", c.Name, c.Value)
	}
	g.printf("\n")
}

// --- Enums ---

func (g *clientTSGen) emitEnums() {
	if len(g.api.Enums) == 0 {
		return
	}
	g.printf("// --- Enums ---\n\n")
	for _, e := range g.api.Enums {
		name := toPascalCase(e.Name)
		g.printf("export enum %s {\n", name)
		for _, v := range e.Values {
			g.printf("  %s = %d,\n", v.Name, v.Value)
		}
		g.printf("}\n\n")
	}
}

// --- Interfaces (types) ---

func (g *clientTSGen) emitInterfaces() {
	if len(g.api.Types) == 0 {
		return
	}
	g.printf("// --- Types ---\n\n")
	for _, t := range g.api.Types {
		name := toPascalCase(t.Name)
		g.printf("export interface %s {\n", name)
		for _, f := range t.Fields {
			tsType := g.toTSType(f.Type)
			if f.Type.Nullable {
				g.printf("  %s?: %s;\n", f.Name, tsType)
			} else {
				g.printf("  %s: %s;\n", f.Name, tsType)
			}
		}
		g.printf("}\n\n")
	}
}

// --- Client ---

func (g *clientTSGen) emitClient() {
	className := toPascalCase(g.api.Name) + "Client"

	g.printf("// --- Client ---\n\n")

	// APIError class
	g.printf("export class APIError extends Error {\n")
	g.printf("  constructor(public readonly statusCode: number, message: string) {\n")
	g.printf("    super(`${message} (HTTP ${statusCode})`);\n")
	g.printf("    this.name = 'APIError';\n")
	g.printf("  }\n")
	g.printf("}\n\n")

	// ValidationError class — thrown client-side (collect-all) before a request.
	g.printf("export class ValidationError extends Error {\n")
	g.printf("  constructor(public readonly errors: string[]) {\n")
	g.printf("    super('validation failed: ' + errors.join('; '));\n")
	g.printf("    this.name = 'ValidationError';\n")
	g.printf("  }\n")
	g.printf("}\n\n")

	// Client class
	g.printf("export class %s {\n", className)
	g.printf("  private readonly baseUrl: string;\n\n")

	// Constructor
	g.printf("  constructor(baseUrl: string, instance: string = '%s') {\n", g.api.Prefix)
	g.printf("    this.baseUrl = baseUrl.replace(/\\/+$/, '') + '/api/v1/' + instance;\n")
	g.printf("  }\n\n")

	// _doRequest helper
	g.printf("  private async doRequest<T>(method: string, path: string, body?: unknown): Promise<T | undefined> {\n")
	g.printf("    const url = this.baseUrl + path;\n")
	g.printf("    const init: RequestInit = { method };\n")
	g.printf("    if (body !== undefined) {\n")
	g.printf("      init.headers = { 'Content-Type': 'application/json', 'Accept': 'application/json' };\n")
	// bigint replacer: 64-bit ints are typed bigint and travel as JSON strings
	// (G-M4). Top-level params are converted by tsParamSend, but a bigint
	// FIELD nested in a body struct reaches stringify as-is — and
	// JSON.stringify throws on bigint.
	g.printf("      init.body = JSON.stringify(body, (_k, v) => typeof v === 'bigint' ? String(v) : v);\n")
	g.printf("    } else {\n")
	g.printf("      init.headers = { 'Accept': 'application/json' };\n")
	g.printf("    }\n")
	g.printf("    const resp = await fetch(url, init);\n")
	g.printf("    if (!resp.ok) {\n")
	g.printf("      let msg: string;\n")
	g.printf("      try {\n")
	g.printf("        const errData = await resp.json();\n")
	g.printf("        msg = errData.error ?? resp.statusText;\n")
	g.printf("      } catch {\n")
	g.printf("        msg = await resp.text();\n")
	g.printf("      }\n")
	g.printf("      throw new APIError(resp.status, msg);\n")
	g.printf("    }\n")
	g.printf("    const text = await resp.text();\n")
	g.printf("    if (text) {\n")
	g.printf("      return JSON.parse(text) as T;\n")
	g.printf("    }\n")
	g.printf("    return undefined;\n")
	g.printf("  }\n\n")
}

// --- Client Methods ---

func (g *clientTSGen) emitClientMethods() {
	if len(g.api.Funcs) == 0 {
		return
	}
	g.printf("  // --- API Methods ---\n\n")

	for _, fn := range g.api.Funcs {
		if fn.Watch {
			continue // watch functions use WebSocket, not REST
		}
		g.emitClientMethod(fn)
	}
}

func (g *clientTSGen) emitClientMethod(fn ast.Func) {
	// See clientGoGen.emitClientMethod: the REST view is the marshaled shape.
	fn = restView(fn)
	methodName := toCamelCaseTS(fn.Name)

	// Signature
	params := g.methodParams(fn)
	retType := g.methodReturnType(fn)
	g.printf("  async %s(%s): Promise<%s> {\n", methodName, params, retType)

	// Client-side collect-all validation of IDL @constraints.
	if v := clientValidation(tsLang{}, fn, g.api); v != "" {
		g.printf("%s", spaceIndent(v, 2, 2))
	}

	// Build path
	path := fn.Path
	pathParams := extractPathParams(path)

	if len(pathParams) > 0 {
		// Use template literal for path interpolation
		tsPath := path
		for _, pp := range pathParams {
			paramName := toCamelCaseTS(pp)
			tsPath = strings.Replace(tsPath, "{"+pp+"}", "${encodeURIComponent(String("+paramName+"))}", 1)
		}
		g.printf("    const apiPath = `%s`;\n", tsPath)
	} else {
		g.printf("    const apiPath = '%s';\n", path)
	}

	// Query parameters (GET/DELETE)
	queryParams := g.nonPathParams(fn, pathParams)
	if len(queryParams) > 0 && (fn.Method == "GET" || fn.Method == "DELETE" || fn.Method == "") {
		g.printf("    const query = new URLSearchParams();\n")
		for _, qp := range queryParams {
			paramName := toCamelCaseTS(qp.Name)
			if qp.Type.Nullable {
				g.printf("    if (%s !== undefined) query.set('%s', String(%s));\n",
					paramName, qp.Name, paramName)
			} else {
				g.printf("    query.set('%s', String(%s));\n", qp.Name, paramName)
			}
		}
		g.printf("    const qs = query.toString();\n")
		g.printf("    const fullPath = qs ? `${apiPath}?${qs}` : apiPath;\n")
	}

	// Body (POST/PUT/PATCH)
	var bodyExpr string
	hasQuery := len(queryParams) > 0 && (fn.Method == "GET" || fn.Method == "DELETE" || fn.Method == "")
	if len(queryParams) > 0 && (fn.Method == "POST" || fn.Method == "PUT" || fn.Method == "PATCH") {
		g.printf("    const body = {\n")
		for _, bp := range queryParams {
			paramName := toCamelCaseTS(bp.Name)
			g.printf("      %s: %s,\n", bp.Name, tsParamSend(paramName, bp.Type))
		}
		g.printf("    };\n")
		bodyExpr = "body"
	}

	// HTTP method
	method := fn.Method
	if method == "" {
		method = "GET"
	}

	// Path variable to use
	pathVar := "apiPath"
	if hasQuery {
		pathVar = "fullPath"
	}

	// Make request
	hasResult := fn.Return != nil
	if !hasResult {
		if bodyExpr != "" {
			g.printf("    await this.doRequest<void>('%s', %s, %s);\n", method, pathVar, bodyExpr)
		} else {
			g.printf("    await this.doRequest<void>('%s', %s);\n", method, pathVar)
		}
	} else {
		tsType := g.toTSType(*fn.Return)
		revive := tsReviveStmt("__res", *fn.Return, g.reviveSet)
		if revive == "" {
			if bodyExpr != "" {
				g.printf("    return await this.doRequest<%s>('%s', %s, %s) as %s;\n", tsType, method, pathVar, bodyExpr, tsType)
			} else {
				g.printf("    return await this.doRequest<%s>('%s', %s) as %s;\n", tsType, method, pathVar, tsType)
			}
		} else {
			if bodyExpr != "" {
				g.printf("    const __res = await this.doRequest<%s>('%s', %s, %s) as %s;\n", tsType, method, pathVar, bodyExpr, tsType)
			} else {
				g.printf("    const __res = await this.doRequest<%s>('%s', %s) as %s;\n", tsType, method, pathVar, tsType)
			}
			g.printf("    %s", revive)
			g.printf("    return __res;\n")
		}
	}
	g.printf("  }\n\n")
}

func (g *clientTSGen) methodParams(fn ast.Func) string {
	if len(fn.Params) == 0 {
		return ""
	}
	var parts []string
	// Required params first, optional last
	for _, p := range fn.Params {
		if !p.Type.Nullable {
			parts = append(parts, fmt.Sprintf("%s: %s", toCamelCaseTS(p.Name), g.toTSType(p.Type)))
		}
	}
	for _, p := range fn.Params {
		if p.Type.Nullable {
			parts = append(parts, fmt.Sprintf("%s?: %s", toCamelCaseTS(p.Name), g.toTSType(p.Type)))
		}
	}
	return strings.Join(parts, ", ")
}

func (g *clientTSGen) methodReturnType(fn ast.Func) string {
	if fn.Return == nil {
		return "void"
	}
	return g.toTSType(*fn.Return)
}

func (g *clientTSGen) nonPathParams(fn ast.Func, pathParams []string) []ast.Param {
	pathSet := make(map[string]bool)
	for _, pp := range pathParams {
		pathSet[pp] = true
	}
	var result []ast.Param
	for _, p := range fn.Params {
		if !pathSet[p.Name] {
			result = append(result, p)
		}
	}
	return result
}

func (g *clientTSGen) toTSType(t ast.TypeRef) string {
	switch t.Kind {
	case ast.TypePrimitive:
		base := primitiveToTSType(t.Name)
		if t.Nullable {
			return base + " | undefined"
		}
		return base
	case ast.TypeNamed:
		name := toPascalCase(t.Name)
		if t.Nullable {
			return name + " | undefined"
		}
		return name
	case ast.TypeSlice:
		elem := g.toTSType(*t.Elem)
		return elem + "[]"
	case ast.TypeArray:
		elem := g.toTSType(*t.Elem)
		return elem + "[]"
	case ast.TypeMap:
		return "Record<string, " + g.toTSType(*t.Elem) + ">"
	}
	return "unknown"
}

func primitiveToTSType(name string) string {
	switch name {
	case "bool":
		return "boolean"
	case "i8", "u8", "i16", "u16", "i32", "u32", "f32", "f64":
		return "number"
	case "i64", "u64":
		return "bigint" // wire-encoded as a JSON string; revived via BigInt()
	case "string":
		return "string"
	default:
		return "unknown"
	}
}

// toCamelCaseTS converts snake_case to camelCase and escapes JS reserved words.
func toCamelCaseTS(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if i > 0 && len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	result := strings.Join(parts, "")
	return tsEscapeReserved(result)
}

// --- 64-bit bigint revival (shared by the REST and WS TS clients) ---
//
// 64-bit ints cross the wire as JSON strings (a JS number truncates above 2^53).
// TS types them as `bigint`; after JSON.parse each such field is a string that
// must be run through BigInt(). tsReviveSet/emitTSRevivers generate one in-place
// reviver per type that (transitively) contains a 64-bit field.

// tsPrinter is the shared printf signature of the two TS generators.
type tsPrinter = func(format string, args ...interface{})

// tsReviverName is the emitted reviver function name for a named type.
func tsReviverName(typeName string) string { return "__revive" + toPascalCase(typeName) }

// tsElemNeedsRevive reports whether a slice/array element type is a named type
// in the revive set, and panics (fail-loud, matching the emitter's other latent
// -shape guards) if it is a slice/array of a 64-bit primitive — a shape no IDL
// uses and which the reviver does not handle.
func tsElemNeedsRevive(elem *ast.TypeRef, set map[string]bool) bool {
	if elem == nil {
		return false
	}
	if is64BitScalarInt(*elem) {
		panic(fmt.Sprintf("gmicompile: slice/array of 64-bit int (%s) not supported by the TS bigint reviver", elem.String()))
	}
	return elem.Kind == ast.TypeNamed && set[elem.Name]
}

// typeNeedsReviveGiven reports whether a field's type requires revival given the
// current set of revivable named types.
func typeNeedsReviveGiven(t ast.TypeRef, set map[string]bool) bool {
	switch t.Kind {
	case ast.TypePrimitive:
		return is64BitScalarInt(t)
	case ast.TypeNamed:
		return set[t.Name]
	case ast.TypeSlice, ast.TypeArray:
		return tsElemNeedsRevive(t.Elem, set)
	}
	return false
}

// tsReviveSet computes, by fixpoint, the set of named types needing revival: a
// type qualifies if any field is a 64-bit int, a named type already in the set,
// or a slice/array whose element is such a named type.
func tsReviveSet(api *ast.API) map[string]bool {
	set := make(map[string]bool)
	for {
		changed := false
		for i := range api.Types {
			t := &api.Types[i]
			if set[t.Name] {
				continue
			}
			for _, f := range t.Fields {
				if typeNeedsReviveGiven(f.Type, set) {
					set[t.Name] = true
					changed = true
					break
				}
			}
		}
		if !changed {
			return set
		}
	}
}

// tsReviveUsedSet narrows a revive set to the types whose reviver the client
// being emitted actually calls, plus the types those revivers call into.
//
// tsReviveSet ranges over every type in the API, but a generator emits a method
// only for the functions it serves — the REST client skips watch functions —
// so a type reachable only through a skipped function would get a reviver that
// nothing calls. Under the webapps' `noUnusedLocals` that is a compile error,
// which is how this surfaced: emcstat's only StatFull-returning function is
// watch-only, leaving __reviveStatFull dead in the REST client.
func tsReviveUsedSet(api *ast.API, set map[string]bool, serves func(ast.Func) bool) map[string]bool {
	byName := make(map[string]*ast.Type, len(api.Types))
	for i := range api.Types {
		byName[api.Types[i].Name] = &api.Types[i]
	}

	used := make(map[string]bool)
	var markName func(name string)
	markType := func(t ast.TypeRef) {
		switch {
		case t.Kind == ast.TypeNamed && set[t.Name]:
			markName(t.Name)
		case (t.Kind == ast.TypeSlice || t.Kind == ast.TypeArray || t.Kind == ast.TypeMap) &&
			t.Elem != nil && t.Elem.Kind == ast.TypeNamed && set[t.Elem.Name]:
			markName(t.Elem.Name)
		}
	}
	// A reviver body calls the revivers of its revivable named fields, so the
	// closure has to follow them or the emitted body loses its callee.
	markName = func(name string) {
		if used[name] {
			return
		}
		used[name] = true
		t := byName[name]
		if t == nil {
			return
		}
		for _, f := range t.Fields {
			markType(f.Type)
		}
	}

	for _, fn := range api.Funcs {
		if fn.Return == nil || !serves(fn) {
			continue
		}
		markType(*fn.Return)
	}
	return used
}

// emitTSRevivers writes an in-place reviver function for every type in the set.
func emitTSRevivers(p tsPrinter, api *ast.API, set map[string]bool) {
	if len(set) == 0 {
		return
	}
	p("// --- 64-bit field revival (JSON string -> bigint) ---\n\n")
	for i := range api.Types {
		t := &api.Types[i]
		if !set[t.Name] {
			continue
		}
		name := toPascalCase(t.Name)
		p("function %s(o: %s): %s {\n", tsReviverName(t.Name), name, name)
		p("  if (o == null) return o;\n")
		for _, f := range t.Fields {
			p("%s", tsReviveFieldStmt(f, set))
		}
		p("  return o;\n")
		p("}\n\n")
	}
}

// tsReviveFieldStmt returns the reviver statement(s) for a single field.
func tsReviveFieldStmt(f ast.Field, set map[string]bool) string {
	acc := "o." + f.Name
	switch {
	case is64BitScalarInt(f.Type):
		conv := fmt.Sprintf("  %s = BigInt(%s as unknown as string);\n", acc, acc)
		if f.Type.Nullable {
			return fmt.Sprintf("  if (%s != null) %s = BigInt(%s as unknown as string);\n", acc, acc, acc)
		}
		return conv
	case f.Type.Kind == ast.TypeNamed && set[f.Type.Name]:
		call := fmt.Sprintf("  %s(%s);\n", tsReviverName(f.Type.Name), acc)
		if f.Type.Nullable {
			return fmt.Sprintf("  if (%s != null) %s(%s);\n", acc, tsReviverName(f.Type.Name), acc)
		}
		return call
	case (f.Type.Kind == ast.TypeSlice || f.Type.Kind == ast.TypeArray) && tsElemNeedsRevive(f.Type.Elem, set):
		return fmt.Sprintf("  %s?.forEach(%s);\n", acc, tsReviverName(f.Type.Elem.Name))
	}
	return ""
}

// tsReviveStmt returns the statement that revives a result variable of the given
// return type in place, or "" if no revival is needed.
func tsReviveStmt(varName string, t ast.TypeRef, set map[string]bool) string {
	switch {
	case t.Kind == ast.TypeNamed && set[t.Name]:
		return fmt.Sprintf("%s(%s);\n", tsReviverName(t.Name), varName)
	case (t.Kind == ast.TypeSlice || t.Kind == ast.TypeArray) && tsElemNeedsRevive(t.Elem, set):
		return fmt.Sprintf("%s?.forEach(%s);\n", varName, tsReviverName(t.Elem.Name))
	case t.Kind == ast.TypeMap && tsElemNeedsRevive(t.Elem, set):
		return fmt.Sprintf("if (%s) Object.values(%s).forEach(%s);\n", varName, varName, tsReviverName(t.Elem.Name))
	}
	return ""
}

// tsParamSend returns the JSON send expression for a request-body/command
// parameter. 64-bit ints are typed `bigint` but the wire carries them as JSON
// strings (see jsonStringOpt), and JSON.stringify throws on a bigint — so they
// are serialized via String(). All other params serialize as-is.
func tsParamSend(name string, t ast.TypeRef) string {
	if is64BitScalarInt(t) {
		return "String(" + name + ")"
	}
	return name
}

// tsEscapeReserved adds a trailing underscore to JavaScript/TypeScript reserved words.
func tsEscapeReserved(name string) string {
	switch name {
	case "break", "case", "catch", "class", "const", "continue", "debugger",
		"default", "delete", "do", "else", "enum", "export", "extends",
		"false", "finally", "for", "function", "if", "import", "in",
		"instanceof", "new", "null", "return", "super", "switch", "this",
		"throw", "true", "try", "typeof", "var", "void", "while", "with",
		"yield", "let", "static", "implements", "interface", "package",
		"private", "protected", "public", "await", "async":
		return name + "_"
	}
	return name
}
