// Copyright (C) 2026 Sascha Ittner <sascha.ittner@modusoft.de>
// License: GPL Version 2
package cgen

import (
	"fmt"
	"io"
	"strings"

	"github.com/stratuMAK/stratumak/src/stmak/internal/gmicompile/ast"
)

// GenerateClientTSWS writes a TypeScript WebSocket watch client module.
// Uses the browser/Node WebSocket API with typed callbacks.
func GenerateClientTSWS(w io.Writer, api *ast.API) error {
	g := &clientTSWSGen{w: w, api: api}
	return g.generate()
}

type clientTSWSGen struct {
	w         io.Writer
	api       *ast.API
	err       error
	reviveSet map[string]bool
}

func (g *clientTSWSGen) printf(format string, args ...interface{}) {
	if g.err != nil {
		return
	}
	_, g.err = fmt.Fprintf(g.w, format, args...)
}

func (g *clientTSWSGen) generate() error {
	// The WS client serves every function: watch ones as subscribe wrappers,
	// the rest as command methods.
	g.reviveSet = tsReviveUsedSet(g.api, tsReviveSet(g.api), func(ast.Func) bool { return true })
	g.emitHeader()
	g.emitConstants()
	g.emitEnums()
	g.emitInterfaces()
	emitTSRevivers(g.printf, g.api, g.reviveSet)
	g.emitClient()
	g.emitSubscribeMethods()
	g.emitCommandMethods()
	g.printf("}\n")
	return g.err
}

func (g *clientTSWSGen) emitHeader() {
	g.printf("// Code generated by gmicompile --client-ts-ws - DO NOT EDIT.\n")
	EmitMeta(g.w, g.api, "//")
	g.printf("//\n")
	g.printf("// WebSocket watch client for %s API v%d\n\n", g.api.Name, g.api.Version)
}

func (g *clientTSWSGen) emitConstants() {
	if len(g.api.Consts) == 0 {
		return
	}
	g.printf("// --- Constants ---\n\n")
	for _, c := range g.api.Consts {
		g.printf("export const %s = %d;\n", c.Name, c.Value)
	}
	g.printf("\n")
}

func (g *clientTSWSGen) emitEnums() {
	if len(g.api.Enums) == 0 {
		return
	}
	g.printf("// --- Enums ---\n\n")
	for _, e := range g.api.Enums {
		name := toPascalCase(e.Name)
		g.printf("export enum %s {\n", name)
		for _, v := range e.Values {
			g.printf("  %s = %d,\n", v.Name, v.Value)
		}
		g.printf("}\n\n")
	}
}

func (g *clientTSWSGen) emitInterfaces() {
	if len(g.api.Types) == 0 {
		return
	}
	g.printf("// --- Types ---\n\n")
	for _, t := range g.api.Types {
		name := toPascalCase(t.Name)
		g.printf("export interface %s {\n", name)
		for _, f := range t.Fields {
			tsType := g.toTSType(f.Type)
			if f.Type.Nullable {
				g.printf("  %s?: %s;\n", f.Name, tsType)
			} else {
				g.printf("  %s: %s;\n", f.Name, tsType)
			}
		}
		g.printf("}\n\n")
	}
}

func (g *clientTSWSGen) emitClient() {
	className := toPascalCase(g.api.Name) + "WatchClient"

	g.printf("// --- WebSocket Watch Client ---\n\n")

	g.printf("export class %s {\n", className)
	g.printf("  private readonly url: string;\n")
	g.printf("  private readonly api: string;\n")
	g.printf("  private readonly instance: string;\n")
	g.printf("  private ws: WebSocket | null = null;\n")
	g.printf("  private callbacks = new Map<string, (data: unknown) => void>();\n")
	g.printf("  private binaryCallbacks = new Map<string, (data: ArrayBuffer) => void>();\n")
	g.printf("  private pending = new Map<number, { resolve: (v: unknown) => void; reject: (e: Error) => void }>();\n")
	g.printf("  private nextId = 1;\n")
	g.printf("  onClose?: () => void;\n\n")

	// Constructor
	g.printf("  constructor(url: string, api = '%s', instance = '%s') {\n", g.api.Name, g.api.Name)
	g.printf("    this.url = url;\n")
	g.printf("    this.api = api;\n")
	g.printf("    this.instance = instance;\n")
	g.printf("  }\n\n")

	// connect
	g.printf("  connect(): Promise<void> {\n")
	g.printf("    return new Promise((resolve, reject) => {\n")
	g.printf("      this.ws = new WebSocket(this.url);\n")
	g.printf("      this.ws.binaryType = 'arraybuffer';\n")
	g.printf("      this.ws.onopen = () => resolve();\n")
	g.printf("      this.ws.onerror = () => reject(new Error('WebSocket error'));\n")
	g.printf("      this.ws.onmessage = (ev) => this.handleMessage(ev);\n")
	g.printf("      this.ws.onclose = () => {\n")
	g.printf("        for (const [, p] of this.pending) {\n")
	g.printf("          p.reject(new Error('WebSocket closed'));\n")
	g.printf("        }\n")
	g.printf("        this.pending.clear();\n")
	g.printf("        this.onClose?.();\n")
	g.printf("      };\n")
	g.printf("    });\n")
	g.printf("  }\n\n")

	// close
	g.printf("  close(): void {\n")
	g.printf("    this.ws?.close();\n")
	g.printf("    this.ws = null;\n")
	g.printf("  }\n\n")

	// handleMessage
	g.printf("  private handleMessage(ev: MessageEvent): void {\n")
	g.printf("    if (ev.data instanceof ArrayBuffer) {\n")
	g.printf("      this.handleBinaryMessage(ev.data);\n")
	g.printf("      return;\n")
	g.printf("    }\n")
	g.printf("    const msg = JSON.parse(ev.data as string);\n")
	g.printf("    if (msg.type === 'update') {\n")
	g.printf("      const cb = this.callbacks.get(msg.func);\n")
	g.printf("      if (cb) cb(msg.data);\n")
	g.printf("    } else if (msg.type === 'result') {\n")
	g.printf("      const p = this.pending.get(msg.id);\n")
	g.printf("      if (p) {\n")
	g.printf("        this.pending.delete(msg.id);\n")
	g.printf("        if (msg.error) {\n")
	g.printf("          p.reject(new Error(msg.error));\n")
	g.printf("        } else {\n")
	g.printf("          p.resolve(msg.data);\n")
	g.printf("        }\n")
	g.printf("      }\n")
	g.printf("    }\n")
	g.printf("  }\n\n")

	// handleBinaryMessage — binary frames use "funcName\0payload" format
	g.printf("  private handleBinaryMessage(buf: ArrayBuffer): void {\n")
	g.printf("    const bytes = new Uint8Array(buf);\n")
	g.printf("    const nullIdx = bytes.indexOf(0);\n")
	g.printf("    if (nullIdx < 0) return;\n")
	g.printf("    const funcName = new TextDecoder().decode(bytes.subarray(0, nullIdx));\n")
	g.printf("    const binCb = this.binaryCallbacks.get(funcName);\n")
	g.printf("    if (binCb) {\n")
	g.printf("      binCb(buf.slice(nullIdx + 1));\n")
	g.printf("      return;\n")
	g.printf("    }\n")
	g.printf("    const payload = bytes.subarray(nullIdx + 1);\n")
	g.printf("    const cb = this.callbacks.get(funcName);\n")
	g.printf("    if (cb) cb(Array.from(payload));\n")
	g.printf("  }\n\n")

	// subscribe (generic)
	g.printf("  subscribe(funcName: string, rateMs: number, callback: (data: unknown) => void, args?: Record<string, unknown>): void {\n")
	g.printf("    this.callbacks.set(funcName, callback);\n")
	g.printf("    const msg: Record<string, unknown> = {\n")
	g.printf("      action: 'subscribe',\n")
	g.printf("      api: this.api,\n")
	g.printf("      instance: this.instance,\n")
	g.printf("      func: funcName,\n")
	g.printf("      rate_ms: rateMs,\n")
	g.printf("    };\n")
	g.printf("    if (args) { msg.args = args; }\n")
	// bigint replacer: watch args may carry 64-bit fields (typed bigint,
	// wire = JSON string per G-M4); JSON.stringify throws on a bare bigint.
	g.printf("    this.ws?.send(JSON.stringify(msg, (_k, v) => typeof v === 'bigint' ? String(v) : v));\n")
	g.printf("  }\n\n")

	// @watch_delta merge state — emitted only when some watch declares it, so
	// every other generated client stays byte-identical.
	if g.hasStructDelta() {
		g.printf("  private deltaState = new Map<string, Record<string, unknown>>();\n\n")
		g.printf("  /** Merge a @watch_delta frame onto the last object seen for this watch.\n")
		g.printf("   *  The server sends the whole object on the first push of a connection and\n")
		g.printf("   *  only the changed top-level keys after that, so a subscriber that replaced\n")
		g.printf("   *  instead of merging would be handed an object missing most of its fields. */\n")
		g.printf("  private mergeDelta<T>(funcName: string, raw: unknown): T {\n")
		g.printf("    // A non-object frame has nothing to merge onto: drop the base and pass\n")
		g.printf("    // it through (a later object frame starts a fresh base). Mirrors the\n")
		g.printf("    // Python WS client's isinstance(data, dict) guard.\n")
		g.printf("    if (typeof raw !== 'object' || raw === null || Array.isArray(raw)) {\n")
		g.printf("      this.deltaState.delete(funcName);\n")
		g.printf("      return raw as T;\n")
		g.printf("    }\n")
		g.printf("    const merged = { ...(this.deltaState.get(funcName) ?? {}), ...(raw as Record<string, unknown>) };\n")
		g.printf("    this.deltaState.set(funcName, merged);\n")
		g.printf("    // The object handed to the subscriber IS the stored merge base: do not\n")
		g.printf("    // mutate it in the callback, or later frames merge onto corrupted state.\n")
		g.printf("    return merged as T;\n")
		g.printf("  }\n\n")
	}

	// unsubscribe
	g.printf("  unsubscribe(funcName: string): void {\n")
	g.printf("    this.callbacks.delete(funcName);\n")
	g.printf("    this.binaryCallbacks.delete(funcName);\n")
	if g.hasStructDelta() {
		// A resubscribe gets a fresh full frame from the server (the diff state
		// is per-connection), so carrying the old base forward could only
		// resurrect fields of a machine that has since changed.
		g.printf("    this.deltaState.delete(funcName);\n")
	}
	g.printf("    this.ws?.send(JSON.stringify({\n")
	g.printf("      action: 'unsubscribe',\n")
	g.printf("      api: this.api,\n")
	g.printf("      instance: this.instance,\n")
	g.printf("      func: funcName,\n")
	g.printf("    }));\n")
	g.printf("  }\n\n")

	// call (generic)
	g.printf("  call(funcName: string, args?: Record<string, unknown>): Promise<unknown> {\n")
	g.printf("    return new Promise((resolve, reject) => {\n")
	g.printf("      const id = this.nextId++;\n")
	g.printf("      this.pending.set(id, { resolve, reject });\n")
	// Same bigint replacer as subscribe: command args may carry 64-bit fields.
	g.printf("      this.ws?.send(JSON.stringify({\n")
	g.printf("        action: 'call',\n")
	g.printf("        api: this.api,\n")
	g.printf("        instance: this.instance,\n")
	g.printf("        func: funcName,\n")
	g.printf("        id,\n")
	g.printf("        args: args ?? {},\n")
	g.printf("      }, (_k, v) => typeof v === 'bigint' ? String(v) : v));\n")
	g.printf("    });\n")
	g.printf("  }\n\n")
}

func (g *clientTSWSGen) emitSubscribeMethods() {
	hasWatch := false
	for _, fn := range g.api.Funcs {
		if fn.Watch {
			hasWatch = true
			break
		}
	}
	if !hasWatch {
		return
	}

	g.printf("  // --- Subscribe methods ---\n\n")
	for _, fn := range g.api.Funcs {
		if !fn.Watch {
			continue
		}
		methodName := toCamelCaseTS(fn.Name)
		defaultRate := g.defaultRateMS(fn)

		if fn.Return != nil {
			// For []u8 watch functions (binary transfers), use ArrayBuffer callback
			if fn.Return.Kind == ast.TypeSlice && fn.Return.Elem != nil &&
				fn.Return.Elem.Kind == ast.TypePrimitive && fn.Return.Elem.Name == "u8" {
				g.printf("  subscribe%s(callback: (data: ArrayBuffer) => void, rateMs = %s): void {\n",
					toPascalCase(fn.Name), defaultRate)
				g.printf("    this.binaryCallbacks.set('%s', callback);\n", fn.Name)
				g.printf("    this.ws?.send(JSON.stringify({\n")
				g.printf("      action: 'subscribe',\n")
				g.printf("      api: this.api,\n")
				g.printf("      instance: this.instance,\n")
				g.printf("      func: '%s',\n", fn.Name)
				g.printf("      rate_ms: rateMs,\n")
				g.printf("    }));\n")
			} else {
				retType := g.toTSType(*fn.Return)
				if fn.WatchFactory && len(fn.Params) > 0 {
					// Factory watch: accept params and pass as subscribe args
					g.printf("  subscribe%s(callback: (data: %s) => void, rateMs = %s",
						toPascalCase(fn.Name), retType, defaultRate)
					for _, p := range fn.Params {
						pType := g.toTSType(p.Type)
						optional := p.Type.Nullable || (p.Type.Kind == ast.TypeSlice && p.Type.Elem != nil && p.Type.Elem.Nullable)
						if optional {
							// For nullable slices ([]T?), emit the non-nullable array type with optional marker
							if p.Type.Kind == ast.TypeSlice && p.Type.Elem != nil && p.Type.Elem.Nullable {
								elemType := ast.TypeRef{Kind: p.Type.Elem.Kind, Name: p.Type.Elem.Name}
								pType = g.toTSType(elemType) + "[]"
							}
							g.printf(", %s?: %s", toCamelCaseTS(p.Name), pType)
						} else {
							g.printf(", %s: %s", toCamelCaseTS(p.Name), pType)
						}
					}
					g.printf("): void {\n")
					g.printf("    const args: Record<string, unknown> = {};\n")
					for _, p := range fn.Params {
						pName := toCamelCaseTS(p.Name)
						optional := p.Type.Nullable || (p.Type.Kind == ast.TypeSlice && p.Type.Elem != nil && p.Type.Elem.Nullable)
						if optional {
							g.printf("    if (%s !== undefined) { args['%s'] = %s; }\n", pName, p.Name, tsParamSend(pName, p.Type))
						} else {
							g.printf("    args['%s'] = %s;\n", p.Name, tsParamSend(pName, p.Type))
						}
					}
					g.printf("    this.subscribe('%s', rateMs, %s, args);\n", fn.Name, g.reviveCallback(fn, *fn.Return, retType))
				} else {
					g.printf("  subscribe%s(callback: (data: %s) => void, rateMs = %s): void {\n",
						toPascalCase(fn.Name), retType, defaultRate)
					g.printf("    this.subscribe('%s', rateMs, %s);\n", fn.Name, g.reviveCallback(fn, *fn.Return, retType))
				}
			}
		} else {
			g.printf("  subscribe%s(callback: (data: unknown) => void, rateMs = %s): void {\n",
				toPascalCase(fn.Name), defaultRate)
			g.printf("    this.subscribe('%s', rateMs, callback);\n", fn.Name)
		}
		g.printf("  }\n\n")

		// Unsubscribe helper
		g.printf("  unsubscribe%s(): void {\n", toPascalCase(fn.Name))
		g.printf("    this.unsubscribe('%s');\n", fn.Name)
		g.printf("  }\n\n")

		_ = methodName // used for naming consistency check
	}
}

func (g *clientTSWSGen) emitCommandMethods() {
	hasCommand := false
	for _, fn := range g.api.Funcs {
		if !fn.Watch {
			hasCommand = true
			break
		}
	}
	if !hasCommand {
		return
	}

	g.printf("  // --- Command methods ---\n\n")
	for _, fn := range g.api.Funcs {
		if fn.Watch {
			continue
		}
		// See clientGoGen.emitClientMethod: the REST view is the marshaled shape.
		fn = restView(fn)
		methodName := toCamelCaseTS(fn.Name)
		params := g.methodParams(fn)
		retType := "unknown"
		if fn.Return != nil {
			retType = g.toTSType(*fn.Return)
		}

		g.printf("  async %s(%s): Promise<%s> {\n", methodName, params, retType)
		var revive string
		if fn.Return != nil {
			revive = tsReviveStmt("__res", *fn.Return, g.reviveSet)
		}
		// callArgs is the trailing arguments to this.call(name[, {...}]).
		callArgs := ""
		if len(fn.Params) > 0 {
			var sb strings.Builder
			sb.WriteString(", {\n")
			for _, p := range fn.Params {
				pName := toCamelCaseTS(p.Name)
				sb.WriteString(fmt.Sprintf("      %s: %s,\n", p.Name, tsParamSend(pName, p.Type)))
			}
			sb.WriteString("    }")
			callArgs = sb.String()
		}
		if revive == "" {
			g.printf("    return await this.call('%s'%s) as %s;\n", fn.Name, callArgs, retType)
		} else {
			g.printf("    const __res = await this.call('%s'%s) as %s;\n", fn.Name, callArgs, retType)
			g.printf("    %s", revive)
			g.printf("    return __res;\n")
		}
		g.printf("  }\n\n")
	}
}

// --- Helpers ---

// structDelta reports whether fn is a @watch_delta watch whose return type is a
// named struct — the case where a delta frame is NOT a valid value of the
// declared type and the client must merge.
//
// A @watch_delta map watch (classicladder rung states, pyvcp widget state) is
// deliberately left alone: a map of the changed keys is still a well-formed map
// of that type, and those apps merge it into their own keyed store, which is
// the point of diffing a map in the first place. A struct is different — a
// StatFull carrying only `heartbeat` is not a StatFull, and the generated
// 64-bit reviver threw outright on the missing field (BigInt(undefined)),
// freezing the UI on its last full frame under a healthy connection.
func structDelta(fn ast.Func) bool {
	return fn.Watch && fn.WatchDelta && fn.Return != nil && fn.Return.Kind == ast.TypeNamed
}

// hasStructDelta reports whether any watch needs the merge helper.
func (g *clientTSWSGen) hasStructDelta() bool {
	for _, fn := range g.api.Funcs {
		if structDelta(fn) {
			return true
		}
	}
	return false
}

// reviveCallback returns the watch-dispatch lambda for a subscribe method,
// merging a @watch_delta frame onto the previous object and inserting an
// in-place 64-bit revival pass before invoking the user callback when the
// return type contains a bigint field.
func (g *clientTSWSGen) reviveCallback(fn ast.Func, ret ast.TypeRef, retType string) string {
	revive := strings.TrimRight(tsReviveStmt("__d", ret, g.reviveSet), "\n")
	if structDelta(fn) {
		merge := fmt.Sprintf("const __d = this.mergeDelta<%s>('%s', raw);", retType, fn.Name)
		if revive == "" {
			return fmt.Sprintf("(raw) => { %s callback(__d); }", merge)
		}
		return fmt.Sprintf("(raw) => { %s %s callback(__d); }", merge, revive)
	}
	if revive == "" {
		return fmt.Sprintf("(raw) => callback(raw as %s)", retType)
	}
	return fmt.Sprintf("(raw) => { const __d = raw as %s; %s callback(__d); }", retType, revive)
}

func (g *clientTSWSGen) defaultRateMS(fn ast.Func) string {
	if fn.WatchDefaultRate != "" {
		return parseRateToMS(fn.WatchDefaultRate)
	}
	return "100"
}

func (g *clientTSWSGen) methodParams(fn ast.Func) string {
	if len(fn.Params) == 0 {
		return ""
	}
	var parts []string
	for _, p := range fn.Params {
		if !p.Type.Nullable {
			parts = append(parts, fmt.Sprintf("%s: %s", toCamelCaseTS(p.Name), g.toTSType(p.Type)))
		}
	}
	for _, p := range fn.Params {
		if p.Type.Nullable {
			parts = append(parts, fmt.Sprintf("%s?: %s", toCamelCaseTS(p.Name), g.toTSType(p.Type)))
		}
	}
	return joinStrings(parts, ", ")
}

func (g *clientTSWSGen) toTSType(t ast.TypeRef) string {
	switch t.Kind {
	case ast.TypePrimitive:
		base := primitiveToTSType(t.Name)
		if t.Nullable {
			return base + " | undefined"
		}
		return base
	case ast.TypeNamed:
		name := toPascalCase(t.Name)
		if t.Nullable {
			return name + " | undefined"
		}
		return name
	case ast.TypeSlice:
		elem := g.toTSType(*t.Elem)
		return elem + "[]"
	case ast.TypeArray:
		elem := g.toTSType(*t.Elem)
		return elem + "[]"
	case ast.TypeMap:
		return "Record<string, " + g.toTSType(*t.Elem) + ">"
	}
	return "unknown"
}
