/* Autogenerated by modcompile — do not edit. */

#include "stmak_env.h"
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdbool.h>

#ifndef TRUE
#define TRUE 1
#endif
#ifndef FALSE
#define FALSE 0
#endif

/* ---------------------------------------------------------------------------
 * Instance data
 * ------------------------------------------------------------------------- */

typedef struct {
    stmak_hal_bit_t *in1;
    stmak_hal_bit_t *in2;
    stmak_hal_bit_t *estop;
    stmak_hal_bit_t *ack;
    stmak_hal_bit_t *reset_fsm;
    stmak_hal_bit_t *enable_fsm;
    stmak_hal_bit_t *out1;
    stmak_hal_bit_t *out2;
    stmak_hal_bit_t *out3;
    stmak_hal_bit_t *special_timeout;
    stmak_hal_s32_t *fsm_state;
    stmak_hal_float_t *fsm_timer;
    stmak_hal_float_t wait_s;
} inst_hal_t;

typedef struct {
    cmod_t base;
    const cmod_env_t *env;
    int comp_id;
    char name[STMAK_HAL_NAME_LEN + 1];
    inst_hal_t *hal;  /* HAL shared memory portion */
    int latched1;
    int latched2;
    int __fsm_test_fsm_init;
    int __fsm_test_fsm_enter;
    int64_t __fsm_test_fsm_timer;
} inst_t;

static void funct__(void *arg, long period) STMAK_NONBLOCKING;

/* ---------------------------------------------------------------------------
 * Convenience defines — user code accesses pins/params by short names.
 * ------------------------------------------------------------------------- */

#undef FUNCTION
#define FUNCTION(name_) \
    static void funct_ ## name_ ## _body(inst_t *__comp_inst, long period) STMAK_NONBLOCKING; \
    static void funct_ ## name_(void *arg, long period) STMAK_NONBLOCKING { \
        funct_ ## name_ ## _body((inst_t *)arg, period); \
    } \
    static void funct_ ## name_ ## _body(inst_t *__comp_inst, long period)

#define fperiod (period * 1e-9)

#define in1 (*(__comp_inst->hal->in1))
#define in2 (*(__comp_inst->hal->in2))
#define estop (*(__comp_inst->hal->estop))
#define ack (*(__comp_inst->hal->ack))
#define reset_fsm (*(__comp_inst->hal->reset_fsm))
#define enable_fsm (*(__comp_inst->hal->enable_fsm))
#define out1 (*(__comp_inst->hal->out1))
#define out2 (*(__comp_inst->hal->out2))
#define out3 (*(__comp_inst->hal->out3))
#define special_timeout (*(__comp_inst->hal->special_timeout))
#define fsm_state (*(__comp_inst->hal->fsm_state))
#define fsm_timer (*(__comp_inst->hal->fsm_timer))
#define wait_s (__comp_inst->hal->wait_s)
#define latched1 (__comp_inst->latched1)
#define latched2 (__comp_inst->latched2)
#define __fsm_test_fsm_init (__comp_inst->__fsm_test_fsm_init)
#define __fsm_test_fsm_enter (__comp_inst->__fsm_test_fsm_enter)
#define __fsm_test_fsm_timer (__comp_inst->__fsm_test_fsm_timer)

/* RT-safe logging macros */
#define STMAK_LOG(level, fmt, ...) stmak_logf(__comp_inst->env->log, __comp_inst->name, (level), fmt, ##__VA_ARGS__)
#define STMAK_LOG_ERR(fmt, ...) stmak_log_errorf(__comp_inst->env->log, __comp_inst->name, fmt, ##__VA_ARGS__)
#define STMAK_LOG_WARN(fmt, ...) stmak_log_warnf(__comp_inst->env->log, __comp_inst->name, fmt, ##__VA_ARGS__)
#define STMAK_LOG_INFO(fmt, ...) stmak_log_infof(__comp_inst->env->log, __comp_inst->name, fmt, ##__VA_ARGS__)
#define STMAK_LOG_DBG(fmt, ...) stmak_log_debugf(__comp_inst->env->log, __comp_inst->name, fmt, ##__VA_ARGS__)

/* RTAPI compatibility macros */
#define rtapi_get_time() (__comp_inst->env->rtapi->get_time(__comp_inst->env->rtapi->ctx))

/* ---------------------------------------------------------------------------
 * State machines (fsm blocks)
 * ------------------------------------------------------------------------- */

/* fsm test_fsm (testdata/fsm.comp:18:1) */
enum test_fsm_state {
    test_fsm_IDLE = 0,
    test_fsm_WAIT_RELEASE = 1,
    test_fsm_TIMEOUT = 2,
    test_fsm_FAULT = 3,
};
static void test_fsm_run(inst_t *__comp_inst, long period) STMAK_NONBLOCKING;
static const char *test_fsm_state_name(int s) STMAK_NONBLOCKING __attribute__((unused));
#define test_fsm() test_fsm_run(__comp_inst, period)
#define test_fsm_in(s_) ((fsm_state) == test_fsm_ ## s_)

/* ---------------------------------------------------------------------------
 * User code
 * ------------------------------------------------------------------------- */

FUNCTION(_){
#line 55 "testdata/fsm.comp"
test_fsm();

#line 119 "testdata/fsm.c"
}

/* ---------------------------------------------------------------------------
 * State machines (fsm blocks)
 * ------------------------------------------------------------------------- */

/* fsm test_fsm (testdata/fsm.comp:18:1) */
static const char *test_fsm_state_name(int s) {
    switch (s) {
    case test_fsm_IDLE: return "IDLE";
    case test_fsm_WAIT_RELEASE: return "WAIT_RELEASE";
    case test_fsm_TIMEOUT: return "TIMEOUT";
    case test_fsm_FAULT: return "FAULT";
    }
    return "?";
}

static void test_fsm_enter_IDLE(inst_t *__comp_inst, long period) STMAK_NONBLOCKING;
static void test_fsm_enter_IDLE(inst_t *__comp_inst, long period) {
    (void)__comp_inst; (void)period;
#line 34 "testdata/fsm.comp"
                   out1 = 1; 
#line 142 "testdata/fsm.c"
}

static void test_fsm_exit_IDLE(inst_t *__comp_inst, long period) STMAK_NONBLOCKING;
static void test_fsm_exit_IDLE(inst_t *__comp_inst, long period) {
    (void)__comp_inst; (void)period;
#line 35 "testdata/fsm.comp"
                   out2 = 1; latched1 = 1; 
#line 150 "testdata/fsm.c"
}

static void test_fsm_during_WAIT_RELEASE(inst_t *__comp_inst, long period) STMAK_NONBLOCKING;
static void test_fsm_during_WAIT_RELEASE(inst_t *__comp_inst, long period) {
    (void)__comp_inst; (void)period;
#line 41 "testdata/fsm.comp"
                 out3 = 0; 
#line 158 "testdata/fsm.c"
}

static void test_fsm_run(inst_t *__comp_inst, long period) {
    int __rst = (
#line 22 "testdata/fsm.comp"
                reset_fsm
#line 165 "testdata/fsm.c"
);
    out1 = 0;
    out2 = 0;
    out3 = (
#line 20 "testdata/fsm.comp"
                                  1
#line 172 "testdata/fsm.c"
);
    special_timeout = 0;
    if (!__fsm_test_fsm_init || __rst) {
        __fsm_test_fsm_init = 1;
        fsm_state = test_fsm_IDLE;
        __fsm_test_fsm_timer = 0;
        fsm_timer = 0;
        latched1 = 0;
        latched2 = (
#line 21 "testdata/fsm.comp"
                                    3
#line 184 "testdata/fsm.c"
);
        __fsm_test_fsm_enter = 1;
        if (__rst) return;
    }
    if (!(
#line 23 "testdata/fsm.comp"
                enable_fsm
#line 192 "testdata/fsm.c"
)) return;
    if (__fsm_test_fsm_enter) {
        __fsm_test_fsm_enter = 0;
        switch (fsm_state) {
        case test_fsm_IDLE: test_fsm_enter_IDLE(__comp_inst, period); break;
        default: break;
        }
    } else {
        __fsm_test_fsm_timer += period;
        fsm_timer = __fsm_test_fsm_timer * 1e-9;
        switch (fsm_state) {
        case test_fsm_IDLE:
            if (
#line 29 "testdata/fsm.comp"
            estop
#line 208 "testdata/fsm.c"
) {
                test_fsm_exit_IDLE(__comp_inst, period);
                fsm_state = test_fsm_FAULT;
                __fsm_test_fsm_timer = 0;
                fsm_timer = 0;
                break;
            }
            if (
#line 36 "testdata/fsm.comp"
            in1 || in2 == 1
#line 219 "testdata/fsm.c"
) {
                test_fsm_exit_IDLE(__comp_inst, period);
                fsm_state = test_fsm_WAIT_RELEASE;
                __fsm_test_fsm_timer = 0;
                fsm_timer = 0;
                break;
            }
            {
                double __to = (
#line 37 "testdata/fsm.comp"
                 (60)
#line 231 "testdata/fsm.c"
);
                if (__to > 0 && __fsm_test_fsm_timer >= __to * 1e9) {
                    test_fsm_exit_IDLE(__comp_inst, period);
                    do {
#line 37 "testdata/fsm.comp"
                                   special_timeout = 1; 
#line 238 "testdata/fsm.c"
                    } while (0);
                    fsm_state = test_fsm_TIMEOUT;
                    __fsm_test_fsm_timer = 0;
                    fsm_timer = 0;
                    break;
                }
            }
            break;
        case test_fsm_WAIT_RELEASE:
            if (
#line 29 "testdata/fsm.comp"
            estop
#line 251 "testdata/fsm.c"
) {
                fsm_state = test_fsm_FAULT;
                __fsm_test_fsm_timer = 0;
                fsm_timer = 0;
                break;
            }
            if (
#line 42 "testdata/fsm.comp"
            !in1
#line 261 "testdata/fsm.c"
) {
                fsm_state = test_fsm_IDLE;
                __fsm_test_fsm_timer = 0;
                fsm_timer = 0;
                test_fsm_enter_IDLE(__comp_inst, period);
                break;
            }
            {
                double __to = (
#line 43 "testdata/fsm.comp"
                 wait_s
#line 273 "testdata/fsm.c"
);
                if (__to > 0 && __fsm_test_fsm_timer >= __to * 1e9) {
                    fsm_state = test_fsm_TIMEOUT;
                    __fsm_test_fsm_timer = 0;
                    fsm_timer = 0;
                    break;
                }
            }
            break;
        case test_fsm_TIMEOUT:
            if (
#line 29 "testdata/fsm.comp"
            estop
#line 287 "testdata/fsm.c"
) {
                fsm_state = test_fsm_FAULT;
                __fsm_test_fsm_timer = 0;
                fsm_timer = 0;
                break;
            }
            if (
#line 47 "testdata/fsm.comp"
            ack
#line 297 "testdata/fsm.c"
) {
                fsm_state = test_fsm_IDLE;
                __fsm_test_fsm_timer = 0;
                fsm_timer = 0;
                test_fsm_enter_IDLE(__comp_inst, period);
                break;
            }
            break;
        case test_fsm_FAULT:
            if (
#line 51 "testdata/fsm.comp"
            !estop && ack
#line 310 "testdata/fsm.c"
) {
                fsm_state = test_fsm_IDLE;
                __fsm_test_fsm_timer = 0;
                fsm_timer = 0;
                test_fsm_enter_IDLE(__comp_inst, period);
                break;
            }
            break;
        default:
            break;
        }
    }
    switch (fsm_state) {
    case test_fsm_WAIT_RELEASE: test_fsm_during_WAIT_RELEASE(__comp_inst, period); break;
    default: break;
    }
}

#undef test_fsm
#undef test_fsm_in

/* ---------------------------------------------------------------------------
 * Undefine convenience macros — clean namespace for generated code below.
 * ------------------------------------------------------------------------- */

#undef FUNCTION
#undef fperiod
#undef in1
#undef in2
#undef estop
#undef ack
#undef reset_fsm
#undef enable_fsm
#undef out1
#undef out2
#undef out3
#undef special_timeout
#undef fsm_state
#undef fsm_timer
#undef wait_s
#undef latched1
#undef latched2
#undef __fsm_test_fsm_init
#undef __fsm_test_fsm_enter
#undef __fsm_test_fsm_timer

/* ---------------------------------------------------------------------------
 * Lifecycle: Init / Start / Stop / Destroy
 * ------------------------------------------------------------------------- */

static int inst_start(cmod_t *self) {
    (void)self;
    return 0;
}

static void inst_stop(cmod_t *self) {
    (void)self;
}

static void inst_destroy(cmod_t *self) {
    inst_t *inst = (inst_t *)self;
    if (inst->comp_id > 0)
        inst->env->hal->exit(inst->env->hal->ctx, inst->comp_id);
    inst->env->rtapi->free(inst->env->rtapi->ctx, inst);
}

/* ---------------------------------------------------------------------------
 * Constructor: New()
 * ------------------------------------------------------------------------- */

int New(const cmod_env_t *env, const char *name,
        int argc, const char **argv, cmod_t **out) {
    int r;

    inst_t *inst = (inst_t *)env->rtapi->calloc(env->rtapi->ctx,
                        sizeof(inst_t));
    if (!inst) return -1;

    inst->base.Start   = inst_start;
    inst->base.Stop    = inst_stop;
    inst->base.Destroy = inst_destroy;
    inst->env = env;
    snprintf(inst->name, sizeof(inst->name), "%s", name);

    inst->comp_id = env->hal->init(env->hal->ctx, name,
                                   env->dl_handle, STMAK_HAL_COMP_REALTIME);
    if (inst->comp_id < 0) { env->rtapi->free(env->rtapi->ctx, inst); return -1; }

    inst->hal = (inst_hal_t *)env->hal->malloc(env->hal->ctx,
                    sizeof(inst_hal_t));
    if (!inst->hal) goto err;
    memset(inst->hal, 0, sizeof(inst_hal_t));

    r = stmak_hal_pin_bit_newf(env->hal, STMAK_HAL_IN,
            &inst->hal->in1, inst->comp_id,
            "%s.in1", name);
    if (r != 0) goto err;

    r = stmak_hal_pin_bit_newf(env->hal, STMAK_HAL_IN,
            &inst->hal->in2, inst->comp_id,
            "%s.in2", name);
    if (r != 0) goto err;

    r = stmak_hal_pin_bit_newf(env->hal, STMAK_HAL_IN,
            &inst->hal->estop, inst->comp_id,
            "%s.estop", name);
    if (r != 0) goto err;

    r = stmak_hal_pin_bit_newf(env->hal, STMAK_HAL_IN,
            &inst->hal->ack, inst->comp_id,
            "%s.ack", name);
    if (r != 0) goto err;

    r = stmak_hal_pin_bit_newf(env->hal, STMAK_HAL_IN,
            &inst->hal->reset_fsm, inst->comp_id,
            "%s.reset-fsm", name);
    if (r != 0) goto err;

    r = stmak_hal_pin_bit_newf(env->hal, STMAK_HAL_IN,
            &inst->hal->enable_fsm, inst->comp_id,
            "%s.enable-fsm", name);
    if (r != 0) goto err;

    r = stmak_hal_pin_bit_newf(env->hal, STMAK_HAL_OUT,
            &inst->hal->out1, inst->comp_id,
            "%s.out1", name);
    if (r != 0) goto err;

    r = stmak_hal_pin_bit_newf(env->hal, STMAK_HAL_OUT,
            &inst->hal->out2, inst->comp_id,
            "%s.out2", name);
    if (r != 0) goto err;

    r = stmak_hal_pin_bit_newf(env->hal, STMAK_HAL_OUT,
            &inst->hal->out3, inst->comp_id,
            "%s.out3", name);
    if (r != 0) goto err;

    r = stmak_hal_pin_bit_newf(env->hal, STMAK_HAL_OUT,
            &inst->hal->special_timeout, inst->comp_id,
            "%s.special-timeout", name);
    if (r != 0) goto err;

    r = stmak_hal_pin_s32_newf(env->hal, STMAK_HAL_OUT,
            &inst->hal->fsm_state, inst->comp_id,
            "%s.fsm-state", name);
    if (r != 0) goto err;

    r = stmak_hal_pin_float_newf(env->hal, STMAK_HAL_OUT,
            &inst->hal->fsm_timer, inst->comp_id,
            "%s.fsm-timer", name);
    if (r != 0) goto err;

    inst->hal->wait_s = 1;
    r = stmak_hal_param_float_newf(env->hal, STMAK_HAL_RW,
            &inst->hal->wait_s, inst->comp_id,
            "%s.wait-s", name);
    if (r != 0) goto err;


    {
        char fname[STMAK_HAL_NAME_LEN + 1];
        snprintf(fname, sizeof(fname), "%s", name);
        r = env->hal->export_funct(env->hal->ctx, fname,
                funct__, inst, 1, 0, inst->comp_id);
        if (r != 0) goto err;
    }

    r = env->hal->ready(env->hal->ctx, inst->comp_id);
    if (r != 0) goto err;

    *out = &inst->base;
    return 0;

err:
    env->hal->exit(env->hal->ctx, inst->comp_id);
    env->rtapi->free(env->rtapi->ctx, inst);
    return -1;
}
