// Copyright (C) 2026 Sascha Ittner <sascha.ittner@modusoft.de>
// License: GPL Version 2
// Package ast defines the intermediate representation shared between
// modcompile frontends (.comp, future .st) and backends (C codegen).
//
// The top-level unit is Package, which maps to a single .so output file.
// A Package always contains exactly one Component (the HAL-facing interface)
// and may additionally contain user-defined types, function blocks, and
// pure functions (used by ST modules).
package ast

import (
	"fmt"
	"strings"
)

// ---------------------------------------------------------------------------
// Source positions
// ---------------------------------------------------------------------------

// Pos tracks a location in the source for error reporting.
type Pos struct {
	File string
	Line int
	Col  int
}

func (p Pos) String() string {
	if p.File == "" {
		return fmt.Sprintf("%d:%d", p.Line, p.Col)
	}
	return fmt.Sprintf("%s:%d:%d", p.File, p.Line, p.Col)
}

// ---------------------------------------------------------------------------
// Package — the compilation unit (one .so)
// ---------------------------------------------------------------------------

// Package is the top-level compilation unit produced by a frontend.
type Package struct {
	Component Component

	// Warnings are non-fatal frontend diagnostics for the CLI to print —
	// a declaration that parses but does nothing, so it says so instead of
	// being quietly dropped.
	Warnings []string

	// Future ST support: user-defined types, sub-modules, helpers.
	Types     []TypeDef
	Blocks    []FunctionBlock
	Functions []PureFunction
}

// ---------------------------------------------------------------------------
// Component — the HAL-facing interface
// ---------------------------------------------------------------------------

// Component describes a HAL component: its pins, parameters, exported
// functions, per-instance variables, options, and (for .comp) verbatim
// user C code.
type Component struct {
	Name string
	Pos  Pos // position of the "component" keyword

	// Documentation fields.
	Summary     string // Short one-line description from component declaration
	Description string // Full description from "description" block
	License     string
	Author      string
	SeeAlso     string
	Notes       string
	Examples    string

	// Declarations.
	Pins      []Pin
	Params    []Param
	Functions []Function
	Variables []Variable
	Options   map[string]string
	Modparams []Modparam
	Includes  []string

	// Mcodes lists the M-codes (100-199) this component handles via the
	// mcode_handler API.  Each declared code gets an MCODE(<n>){...} body in
	// the verbatim C section; modcompile emits the trampoline + registration.
	Mcodes []int

	// GMI API bindings.
	// GMIProvide lists API names this component provides (server side).
	// GMIConsume lists APIs this component consumes (client side).
	GMIProvide []string
	GMIConsume []GMIConsumeEntry

	// Archs restricts the module to the listed target architectures (from
	// an "arch" declaration).  Empty means the module builds on every
	// architecture.  Names are validated against ArchMacros.  On a
	// non-matching target the backend emits a stub that refuses to load
	// instead of the real module, so packaging still builds everywhere.
	Archs []string

	// External build dependencies, for a module that links something beyond
	// the C library and libm.
	//
	// PkgConfig is the blessed route: modcompile asks pkg-config for the
	// flags at compile time, which keeps the .comp declarative (a name, not a
	// command), makes the dependency inspectable (modcompile --deps) and
	// cross-compilable (PKG_CONFIG_PATH/_SYSROOT_DIR/_LIBDIR apply).
	//
	// CFlags/LDFlags are the escape hatch for a library with no .pc file.
	// They are literal, split on whitespace, and never handed to a shell —
	// `modcompile --install` runs as root, so a .comp must stay data rather
	// than becoming a script.  When neither fits (llvm-config and friends),
	// build the module from a Makefile with `modcompile --preprocess` plus
	// --cflags/--ldflags: a Makefile is expected to run programs.
	PkgConfig []PkgConfigDep
	CFlags    []string
	LDFlags   []string

	// VerbatimC holds the raw C code from after the ";;" separator
	// in .comp files.  Empty for ST modules.
	VerbatimC string

	// VerbatimCPos is where VerbatimC's first line sits in the .comp file.
	// The backend turns it into #line directives so the compiler, gdb and
	// gcov report user code against the .comp the developer wrote rather
	// than the generated C nobody keeps.  Zero when there is no verbatim C.
	VerbatimCPos Pos

	// GenPrologue and GenEpilogue are C generated by the frontend, emitted
	// directly before and after the user code while the convenience macros
	// are in scope.  The prologue is for declarations the user code calls,
	// the epilogue for definitions that may call the user's helpers.  The
	// backend knows nothing about what they contain.
	GenPrologue []CodeFragment `json:",omitempty"`
	GenEpilogue []CodeFragment `json:",omitempty"`

	// FSMs describes the fsm blocks of a .comp, for documentation only; the
	// code they need is already in GenPrologue/GenEpilogue.
	FSMs []FSM `json:",omitempty"`
}

// CodeFragment is a piece of generated C.  A zero Pos marks text the
// frontend wrote; a set Pos marks user C copied verbatim from that place in
// the source, which the backend brackets with #line directives so compiler
// errors land on the line the developer wrote.  User fragments always start
// and end on a line of their own in the output.
type CodeFragment struct {
	Pos  Pos `json:",omitempty"`
	Text string
}

// FSM describes one fsm block.
type FSM struct {
	Pos      Pos
	Name     string
	Initial  string
	Inputs   []string
	Outputs  []string // "name" or "name = default", as written
	Latched  []string
	Reset    string // condition text, empty if none
	Enable   string
	StateVar string // empty: hidden variable
	TimerVar string
	Any      []FSMTransition
	States   []FSMState
}

// FSMState is one state of an FSM; Number is its value in the state
// variable.
type FSMState struct {
	Name        string
	Number      int
	OnEnter     bool
	OnExit      bool
	During      bool
	Transitions []FSMTransition // "on" items in source order, then the timeout
}

// FSMTransition is an "on" or "timeout" item.  For a timeout, Cond holds the
// timeout expression in seconds, and an empty Target hands the timeout to the
// any block.
type FSMTransition struct {
	Timeout bool
	Cond    string
	Target  string
	Action  bool
}

// GMIConsumeEntry describes a consumed API with an optional default provider instance.
type GMIConsumeEntry struct {
	API  string // API name (e.g. "mot")
	From string // Default provider instance name (e.g. "motmod"); empty means use API name
}

// ArchMacros maps an "arch" declaration name to the C preprocessor condition
// that is true exactly when the compiler targets that architecture.  A module
// restricted to one or more archs compiles to the real module only where one
// of these conditions holds; on any other target modcompile emits a stub whose
// New() refuses to load.  The condition follows the *target* compiler, so a
// cross build guards itself correctly with no host-side architecture logic.
//
// Aliases map to the same condition as their canonical name.
var ArchMacros = map[string]string{
	"x86_64":  "defined(__x86_64__)",
	"amd64":   "defined(__x86_64__)",
	"i386":    "defined(__i386__)",
	"x86":     "defined(__i386__)",
	"arm":     "defined(__arm__)",
	"aarch64": "defined(__aarch64__)",
	"arm64":   "defined(__aarch64__)",
	"riscv64": "(defined(__riscv) && __riscv_xlen == 64)",
	"ppc64":   "(defined(__powerpc64__) || defined(__ppc64__))",
}

// CName converts a HAL-style name to the C identifier user code uses for it:
// runs of # and their adjacent separators are stripped, - and . become _, and
// runs of _ collapse to one.
func CName(halName string) string {
	// Strip runs of # and their adjacent separators.
	s := stripHashMarkers(halName)
	// Replace . and - with _.
	var b strings.Builder
	prevUnderscore := false
	for _, c := range s {
		switch c {
		case '-', '.', '_':
			if !prevUnderscore {
				b.WriteByte('_')
				prevUnderscore = true
			}
		default:
			b.WriteRune(c)
			prevUnderscore = false
		}
	}
	return b.String()
}

// stripHashMarkers removes runs of # and their directly-adjacent separators.
// For middle ##: "joint.##.offset" → "joint.offset" (keep one separator).
// For trailing ##: "x-val-##" → "x-val".
func stripHashMarkers(s string) string {
	isSep := func(c byte) bool {
		return c == '-' || c == '_' || c == '.'
	}

	var b strings.Builder
	i := 0
	for i < len(s) {
		if isSep(s[i]) && i+1 < len(s) && s[i+1] == '#' {
			// Separator before a hash run — consume sep + all hashes.
			leadingSep := s[i]
			i++ // skip separator
			for i < len(s) && s[i] == '#' {
				i++
			}
			// If there's a trailing separator AND more content after, keep one separator.
			if i < len(s) && isSep(s[i]) && i+1 < len(s) {
				b.WriteByte(leadingSep)
				i++ // skip trailing separator
			}
		} else if s[i] == '#' {
			// Hash at start of string (no leading sep).
			for i < len(s) && s[i] == '#' {
				i++
			}
			if i < len(s) && isSep(s[i]) {
				i++
			}
		} else {
			b.WriteByte(s[i])
			i++
		}
	}
	return b.String()
}

// ---------------------------------------------------------------------------
// HAL types and directions
// ---------------------------------------------------------------------------

// HALType represents a HAL data type.
type HALType int

const (
	HALBit HALType = iota
	HALFloat
	HALS32
	HALU32
	HALPort
)

func (t HALType) String() string {
	switch t {
	case HALBit:
		return "bit"
	case HALFloat:
		return "float"
	case HALS32:
		return "s32"
	case HALU32:
		return "u32"
	case HALPort:
		return "port"
	default:
		return "unknown"
	}
}

// CType returns the C typedef name used in generated code.
func (t HALType) CType() string {
	switch t {
	case HALBit:
		return "stmak_hal_bit_t"
	case HALFloat:
		return "stmak_hal_float_t"
	case HALS32:
		return "stmak_hal_s32_t"
	case HALU32:
		return "stmak_hal_u32_t"
	case HALPort:
		return "stmak_hal_port_t"
	default:
		return "void"
	}
}

// PinDir represents a pin direction.
type PinDir int

const (
	PinIn PinDir = iota
	PinOut
	PinIO
)

func (d PinDir) String() string {
	switch d {
	case PinIn:
		return "in"
	case PinOut:
		return "out"
	case PinIO:
		return "io"
	default:
		return "unknown"
	}
}

// ParamDir represents a parameter direction.
type ParamDir int

const (
	ParamR ParamDir = iota
	ParamRW
)

func (d ParamDir) String() string {
	switch d {
	case ParamR:
		return "r"
	case ParamRW:
		return "rw"
	default:
		return "unknown"
	}
}

// ---------------------------------------------------------------------------
// Pin, Param, Function, Variable, Modparam
// ---------------------------------------------------------------------------

// Pin represents a HAL pin declaration.
type Pin struct {
	Pos  Pos
	Name string // HAL-style name (may contain #, -, .)
	Type HALType
	Dir  PinDir

	// Array support. ArraySize > 0 means this is an array pin.
	// ArrayPersonality, if non-empty, is a C expression giving the
	// actual count (ArraySize is then the maximum).
	ArraySize        int
	ArrayPersonality string

	// Default is the default value expression (empty if none).
	Default string

	// Personality is the "if <expr>" condition (empty if unconditional).
	Personality string

	Doc string
}

// Param represents a HAL parameter declaration.
type Param struct {
	Pos  Pos
	Name string
	Type HALType
	Dir  ParamDir

	ArraySize        int
	ArrayPersonality string
	Default          string
	Personality      string
	Doc              string
}

// Function represents an exported HAL function.
type Function struct {
	Pos  Pos
	Name string
	FP   bool // true if function uses floating point (default true)
	Doc  string
}

// Variable represents a per-instance C variable.
type Variable struct {
	Pos     Pos
	CType   string // C type name (e.g. "double", "unsigned", "hal_bit_t")
	Name    string // variable name (may include leading * for pointers)
	Array   int    // element count; 0 if not an array
	Default string // initial value expression (empty if none)
}

// Modparam represents a module parameter (becomes argv parsing in cmod).
type Modparam struct {
	Pos     Pos
	Type    string // "int", "float", "string" or "dummy"
	Name    string
	Default string
	Doc     string
}

// PkgConfigDep is one external library named by its pkg-config module.
type PkgConfigDep struct {
	Pos Pos
	// Spec is the module spec exactly as written, which is what pkg-config
	// is handed: a bare name ("libcurl"), or a name with a version
	// constraint ("libcurl >= 7.60.0").
	Spec string
}

// Name returns the bare module name, without any version constraint — what
// `modcompile --deps` prints and what a packager turns into a build
// dependency.
func (d PkgConfigDep) Name() string {
	if i := strings.IndexAny(d.Spec, " \t<>=!"); i >= 0 {
		return d.Spec[:i]
	}
	return d.Spec
}

// ---------------------------------------------------------------------------
// Future ST support — placeholder types
// ---------------------------------------------------------------------------

// TypeDefKind classifies user-defined types.
type TypeDefKind int

const (
	TypeStruct TypeDefKind = iota
	TypeEnum
	TypeAlias
	TypeArray
)

// TypeDef represents a user-defined type (ST).
type TypeDef struct {
	Pos  Pos
	Name string
	Kind TypeDefKind
}

// FunctionBlock represents a reusable sub-module (ST FUNCTION_BLOCK).
type FunctionBlock struct {
	Pos  Pos
	Name string
}

// PureFunction represents a stateless helper function (ST FUNCTION).
type PureFunction struct {
	Pos  Pos
	Name string
}
