// Copyright (C) 2026 Sascha Ittner <sascha.ittner@modusoft.de>
// License: GPL Version 2
// Package pkgreg manages the packages.conf registry and generates
// imports_generated.go for the stmakd binary.
package pkgreg

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// EntryType identifies the kind of package in the registry.
type EntryType string

const (
	TypeGMI   EntryType = "gmi"
	TypeGomod EntryType = "gomod"
)

// isValidType reports whether t is a recognised registry entry type. Only these
// types are emitted by GenerateImports, so an unrecognised type in
// packages.conf would otherwise be parsed but silently dropped from the
// generated imports, making the module vanish at runtime with a green build.
func isValidType(t EntryType) bool {
	return t == TypeGMI || t == TypeGomod
}

// Entry is one line in packages.conf.
type Entry struct {
	Type       EntryType // "gmi" or "gomod"
	ImportPath string    // relative import path (e.g. "generated/gmi/kins" or "external/mymodule")
}

// Registry holds the parsed contents of packages.conf.
type Registry struct {
	Entries []Entry
}

// GoModule is the Go module path for the stmakd module.
const GoModule = "github.com/stratuMAK/stratumak/src/stmak"

func (r *Registry) entriesByType(t EntryType) []Entry {
	var out []Entry
	for _, e := range r.Entries {
		if e.Type == t {
			out = append(out, e)
		}
	}
	return out
}

// Add adds a new entry to the registry. Returns false if already present.
func (r *Registry) Add(e Entry) bool {
	for _, existing := range r.Entries {
		if existing.Type == e.Type && existing.ImportPath == e.ImportPath {
			return false
		}
	}
	r.Entries = append(r.Entries, e)
	return true
}

// GenerateImports generates cmd/stmakd/imports_generated.go from the registry.
// The file is only written if its content has changed, to avoid unnecessary
// recompilation.
func (r *Registry) GenerateImports(serverDir string) error {
	path := filepath.Join(serverDir, "cmd", "stmakd", "imports_generated.go")

	var buf strings.Builder
	buf.WriteString("// Code generated by modcompile. DO NOT EDIT.\n")
	buf.WriteString("package main\n\n")
	buf.WriteString("import (\n")

	gmi := r.entriesByType(TypeGMI)
	gomod := r.entriesByType(TypeGomod)

	if len(gmi) > 0 {
		buf.WriteString("\t// GMI dispatch packages\n")
		for _, e := range gmi {
			buf.WriteString(fmt.Sprintf("\t_ \"%s/%s\"\n", GoModule, e.ImportPath))
		}
	}

	if len(gomod) > 0 {
		if len(gmi) > 0 {
			buf.WriteString("\n")
		}
		buf.WriteString("\t// Go modules\n")
		for _, e := range gomod {
			buf.WriteString(fmt.Sprintf("\t_ \"%s/%s\"\n", GoModule, e.ImportPath))
		}
	}

	buf.WriteString(")\n")

	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	return writeIfChanged(path, []byte(buf.String()))
}

// writeIfChanged writes data to path only if the existing content differs.
func writeIfChanged(path string, data []byte) error {
	existing, err := os.ReadFile(path)
	if err == nil && bytes.Equal(existing, data) {
		return nil
	}
	return os.WriteFile(path, data, 0644)
}

// ---------------------------------------------------------------------------
// Auto-discovery: build a Registry from the filesystem without packages.conf
// ---------------------------------------------------------------------------

// markerRe matches @GOMOD:TAG@ markers in packages.conf lines.
var markerRe = regexp.MustCompile(`@GOMOD:([A-Z0-9_]+)@`)

// ReadConfIn reads packages.conf and filters entries based on enabled build
// flags.  Lines with @GOMOD:TAG@ markers are included only if TAG is in the
// enabledFlags set; the marker text is stripped.  Lines without markers are
// always included.
func ReadConfIn(path string, enabledFlags map[string]bool) (*Registry, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer func() { _ = f.Close() }()

	var reg Registry
	scanner := bufio.NewScanner(f)
	lineNo := 0
	for scanner.Scan() {
		lineNo++
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Check for conditional marker.
		if m := markerRe.FindStringSubmatch(line); m != nil {
			tag := m[1]
			if !enabledFlags[tag] {
				continue // disabled, skip
			}
			// Strip the marker from the line.
			line = strings.TrimSpace(markerRe.ReplaceAllString(line, ""))
		}

		fields := strings.Fields(line)
		if len(fields) < 2 {
			return nil, fmt.Errorf("pkgreg: %s:%d: malformed entry %q (want: TYPE IMPORT_PATH)", path, lineNo, line)
		}
		t := EntryType(fields[0])
		if !isValidType(t) {
			return nil, fmt.Errorf("pkgreg: %s:%d: unknown type %q (want %q or %q)", path, lineNo, fields[0], TypeGMI, TypeGomod)
		}
		reg.Entries = append(reg.Entries, Entry{
			Type:       t,
			ImportPath: fields[1],
		})
	}
	return &reg, scanner.Err()
}

// initFuncRe detects func init() declarations in Go source. Anchored at the
// start of a line, which is what keeps it from matching a mention inside a
// comment or an ordinary string; only a raw string literal containing a line
// that itself begins with "func init()" could fool it, and these files are
// gofmt'd generated code. Not worth a go/parser dependency (which would also
// have to decide what a syntactically invalid file means for discovery).
var initFuncRe = regexp.MustCompile(`(?m)^func init\(\)`)

// DiscoverGMI scans directories for generated GMI dispatch packages that
// contain an init() function (i.e. register themselves).  It looks in:
//   - <stmakDir>/generated/gmi/*/
//   - <stmakDir>/external/*/gmi/*/
func DiscoverGMI(stmakDir string) []Entry {
	var entries []Entry

	// In-tree generated GMI packages.
	scanGMIDir(filepath.Join(stmakDir, "generated", "gmi"), "generated/gmi", &entries)

	// External module GMI packages.
	extDir := filepath.Join(stmakDir, "external")
	extEntries, _ := os.ReadDir(extDir)
	for _, mod := range extEntries {
		if !mod.IsDir() {
			continue
		}
		gmiBase := filepath.Join(extDir, mod.Name(), "gmi")
		prefix := "external/" + mod.Name() + "/gmi"
		scanGMIDir(gmiBase, prefix, &entries)
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].ImportPath < entries[j].ImportPath
	})
	return entries
}

// scanGMIDir scans subdirectories of dir for Go packages with init().
func scanGMIDir(dir, prefix string, entries *[]Entry) {
	subs, err := os.ReadDir(dir)
	if err != nil {
		return
	}
	for _, sub := range subs {
		if !sub.IsDir() {
			continue
		}
		pkgDir := filepath.Join(dir, sub.Name())
		if hasInitFunc(pkgDir) {
			*entries = append(*entries, Entry{
				Type:       TypeGMI,
				ImportPath: prefix + "/" + sub.Name(),
			})
		}
	}
}

// hasInitFunc returns true if any .go file in dir declares func init().
func hasInitFunc(dir string) bool {
	files, err := os.ReadDir(dir)
	if err != nil {
		return false
	}
	for _, f := range files {
		if f.IsDir() || !strings.HasSuffix(f.Name(), ".go") || strings.HasSuffix(f.Name(), "_test.go") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, f.Name()))
		if err != nil {
			continue
		}
		if initFuncRe.Match(data) {
			return true
		}
	}
	return false
}

// DiscoverExternal scans <stmakDir>/external/ for Go module packages.
// Each subdirectory with .go files is treated as a gomod entry.
func DiscoverExternal(stmakDir string) []Entry {
	var entries []Entry
	extDir := filepath.Join(stmakDir, "external")
	subs, err := os.ReadDir(extDir)
	if err != nil {
		return nil
	}
	for _, sub := range subs {
		if !sub.IsDir() {
			continue
		}
		pkgDir := filepath.Join(extDir, sub.Name())
		if hasGoFiles(pkgDir) {
			entries = append(entries, Entry{
				Type:       TypeGomod,
				ImportPath: "external/" + sub.Name(),
			})
		}
	}
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].ImportPath < entries[j].ImportPath
	})
	return entries
}

// hasGoFiles returns true if dir contains at least one .go file.
func hasGoFiles(dir string) bool {
	files, err := os.ReadDir(dir)
	if err != nil {
		return false
	}
	for _, f := range files {
		// Discover a package only by its buildable (non-test) sources: a dir
		// with only *_test.go files is not a compilable package, and
		// blank-importing it would break the build with "no non-test Go files".
		if !f.IsDir() && strings.HasSuffix(f.Name(), ".go") && !strings.HasSuffix(f.Name(), "_test.go") {
			return true
		}
	}
	return false
}

// ParseBuildFlags parses a comma-separated build flags string into a set.
func ParseBuildFlags(flags string) map[string]bool {
	m := make(map[string]bool)
	for _, f := range strings.Split(flags, ",") {
		f = strings.TrimSpace(f)
		if f != "" {
			m[f] = true
		}
	}
	return m
}
