// Copyright (C) 2026 Sascha Ittner <sascha.ittner@modusoft.de>
// License: GPL Version 2
package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stratuMAK/stratumak/src/stmak/internal/config"
	"github.com/stratuMAK/stratumak/src/stmak/internal/pkgreg"
)

// These tests cover the parts of the modcompile CLI that are pure logic: the
// non-compiling processFile modes (--preprocess / --document / --parse and the
// name check), compiler resolution, and the tree-mirroring helpers used when
// vendoring an external gomod. The modes that shell out to a C compiler are
// covered by the build itself, which regenerates and compiles every shipped
// .comp on each run.

// writeComp writes a minimal valid .comp whose declared name matches basename.
func writeComp(t *testing.T, dir, basename, body string) string {
	t.Helper()
	name := strings.ReplaceAll(basename, "-", "_")
	if body == "" {
		body = "component " + name + " \"a test component\";\n" +
			"pin in bit ok;\n" +
			"pin out float value;\n" +
			"function _;\n" +
			"license \"GPL\";\n;;\nFUNCTION(_) { }\n"
	}
	path := filepath.Join(dir, basename+".comp")
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatalf("writing %s: %v", path, err)
	}
	return path
}

// TestProcessFilePreprocess covers --preprocess to a named output file, which
// is the mode the build uses to turn a .comp into C.
func TestProcessFilePreprocess(t *testing.T) {
	dir := t.TempDir()
	src := writeComp(t, dir, "tcomp", "")
	out := filepath.Join(dir, "tcomp.c")

	if err := processFile(src, "--preprocess", out); err != nil {
		t.Fatalf("processFile --preprocess: %v", err)
	}
	data, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("reading generated C: %v", err)
	}
	got := string(data)
	for _, want := range []string{"Autogenerated by modcompile", "int New(const cmod_env_t *env", "ok", "value"} {
		if !strings.Contains(got, want) {
			t.Errorf("generated C is missing %q:\n%s", want, got)
		}
	}
}

// TestProcessFileDocument covers --document, including the default output name
// (basename + man section) and the userspace option that moves a component from
// section 9 to section 1.
func TestProcessFileDocument(t *testing.T) {
	dir := t.TempDir()

	// Explicit output file.
	src := writeComp(t, dir, "tdoc", "")
	out := filepath.Join(dir, "tdoc.9")
	if err := processFile(src, "--document", out); err != nil {
		t.Fatalf("processFile --document: %v", err)
	}
	data, err := os.ReadFile(out)
	if err != nil {
		t.Fatalf("reading generated man page: %v", err)
	}
	if !strings.Contains(string(data), ".TH") || !strings.Contains(string(data), "tdoc") {
		t.Errorf("generated man page looks wrong:\n%s", data)
	}

	// Default output name: the man section comes from the userspace option, and
	// the file lands in the working directory.
	wd, err := os.Getwd()
	if err != nil {
		t.Fatalf("Getwd: %v", err)
	}
	if err := os.Chdir(dir); err != nil {
		t.Fatalf("Chdir: %v", err)
	}
	t.Cleanup(func() { _ = os.Chdir(wd) })

	rt := writeComp(t, dir, "trt", "")
	if err := processFile(rt, "--document", ""); err != nil {
		t.Fatalf("processFile --document (default name): %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "trt.9")); err != nil {
		t.Errorf("realtime component man page not written to trt.9: %v", err)
	}

	us := writeComp(t, dir, "tus", "component tus \"userspace\";\n"+
		"option userspace yes;\n"+
		"pin in bit ok;\n"+
		"license \"GPL\";\n;;\nint main(void) { return 0; }\n")
	if err := processFile(us, "--document", ""); err != nil {
		t.Fatalf("processFile --document (userspace): %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "tus.1")); err != nil {
		t.Errorf("userspace component man page not written to tus.1: %v", err)
	}
}

// TestProcessFileNameMustMatchFilename covers the copy/paste guard: the
// declared component name must equal the filename, with '-' in the filename
// accepted where the name has '_' (HAL names cannot contain '-').
func TestProcessFileNameMustMatchFilename(t *testing.T) {
	dir := t.TempDir()

	// A hyphenated filename matching an underscored component name is accepted.
	ok := writeComp(t, dir, "svd-ps_vfd", "")
	if err := processFile(ok, "--preprocess", filepath.Join(dir, "ok.c")); err != nil {
		t.Errorf("hyphenated filename with an underscored component name must be accepted: %v", err)
	}

	// A genuine mismatch is rejected.
	bad := filepath.Join(dir, "myname.comp")
	if err := os.WriteFile(bad, []byte("component othername \"x\";\npin in bit ok;\nfunction _;\nlicense \"GPL\";\n;;\nFUNCTION(_) { }\n"), 0o644); err != nil {
		t.Fatalf("writing: %v", err)
	}
	err := processFile(bad, "--preprocess", filepath.Join(dir, "bad.c"))
	if err == nil {
		t.Fatal("a component name that does not match the filename was accepted")
	}
	if !strings.Contains(err.Error(), "does not match file name") {
		t.Errorf("error = %q; want the name-mismatch message", err.Error())
	}
}

// TestProcessFileErrors covers the remaining rejections: an unknown mode, a
// missing file, a .comp that does not parse, and a raw .c file in a mode that
// does not accept one.
func TestProcessFileErrors(t *testing.T) {
	dir := t.TempDir()
	src := writeComp(t, dir, "terr", "")

	if err := processFile(src, "--nosuchmode", ""); err == nil {
		t.Error("an unknown mode was accepted")
	}
	if err := processFile(filepath.Join(dir, "nosuchfile.comp"), "--preprocess", ""); err == nil {
		t.Error("a missing file was accepted")
	}

	broken := filepath.Join(dir, "tbroken.comp")
	if err := os.WriteFile(broken, []byte("this is not a comp file\n"), 0o644); err != nil {
		t.Fatalf("writing: %v", err)
	}
	if err := processFile(broken, "--preprocess", ""); err == nil {
		t.Error("an unparsable .comp was accepted")
	}

	cfile := filepath.Join(dir, "raw.c")
	if err := os.WriteFile(cfile, []byte("int main(void){return 0;}\n"), 0o644); err != nil {
		t.Fatalf("writing: %v", err)
	}
	err := processFile(cfile, "--preprocess", "")
	if err == nil {
		t.Fatal("a .c file was accepted in --preprocess mode")
	}
	if !strings.Contains(err.Error(), "--compile and --install") {
		t.Errorf("error = %q; want the .c-modes message", err.Error())
	}
}

// TestResolveCompilers covers the CC/CXX resolution order: the environment wins
// over the baked-in configure value, which wins over the built-in default. The
// build bakes config.* in via ldflags, so only the env override and the
// fallback are observable here — and the env override is the one a packager
// actually uses.
func TestResolveCompilers(t *testing.T) {
	t.Setenv("CC", "my-special-cc")
	if got := resolveCC(); got != "my-special-cc" {
		t.Errorf("resolveCC with CC set = %q; want my-special-cc", got)
	}
	t.Setenv("CXX", "my-special-cxx")
	if got := resolveCXX(); got != "my-special-cxx" {
		t.Errorf("resolveCXX with CXX set = %q; want my-special-cxx", got)
	}

	// Whitespace-only is treated as unset, not as a compiler named " ".
	t.Setenv("CC", "   ")
	if got := resolveCC(); strings.TrimSpace(got) == "" {
		t.Error("resolveCC with a blank CC returned a blank compiler")
	}
	t.Setenv("CXX", "   ")
	if got := resolveCXX(); strings.TrimSpace(got) == "" {
		t.Error("resolveCXX with a blank CXX returned a blank compiler")
	}
}

// unsetEnv removes a variable for the rest of the test. t.Setenv cannot
// express "unset", which is the state this test has to distinguish from
// set-empty, and t.Cleanup restores whatever the process started with.
func unsetEnv(t *testing.T, key string) {
	t.Helper()
	prev, had := os.LookupEnv(key)
	if err := os.Unsetenv(key); err != nil {
		t.Fatalf("unset %s: %v", key, err)
	}
	t.Cleanup(func() {
		if had {
			_ = os.Setenv(key, prev)
		}
	})
}

// TestResolveCWarnFlags covers the warning-policy override that carries
// --enable-werror into a module compile. The distinction that matters is
// unset (use the configure-time value) versus set-empty (the developer's
// opt-out inside a tree that WAS configured with --enable-werror) — a
// Getenv-based implementation cannot tell those apart and would ignore the
// opt-out.
func TestResolveCWarnFlags(t *testing.T) {
	orig := config.CWarnFlags
	t.Cleanup(func() { config.CWarnFlags = orig })
	config.CWarnFlags = "-Werror"

	t.Setenv(config.CWarnFlagsEnv, "")
	if got := resolveCWarnFlags(); len(got) != 0 {
		t.Errorf("set-empty %s = %q; want no flags (the opt-out)", config.CWarnFlagsEnv, got)
	}

	unsetEnv(t, config.CWarnFlagsEnv)
	if got := resolveCWarnFlags(); len(got) != 1 || got[0] != "-Werror" {
		t.Errorf("unset %s = %q; want the baked-in [-Werror]", config.CWarnFlagsEnv, got)
	}

	// Multi-flag values split on whitespace, so they reach exec as separate
	// argv entries rather than one unparsable argument.
	t.Setenv(config.CWarnFlagsEnv, "-Werror -Wextra")
	if got := resolveCWarnFlags(); len(got) != 2 || got[1] != "-Wextra" {
		t.Errorf("multi-flag override = %q; want [-Werror -Wextra]", got)
	}

	// A modcompile built without a configure-time policy -- which is every
	// packaged one -- still enforces the built-in default. This is what
	// holds an external module to the same standard as an in-tree one.
	config.CWarnFlags = ""
	unsetEnv(t, config.CWarnFlagsEnv)
	if got := resolveCWarnFlags(); len(got) != 1 || got[0] != "-Werror" {
		t.Errorf("unconfigured modcompile = %q; want the built-in [-Werror]", got)
	}

	// The opt-out has to survive that fallback, or a module that cannot
	// meet the standard yet would have no way out.
	t.Setenv(config.CWarnFlagsEnv, "")
	if got := resolveCWarnFlags(); len(got) != 0 {
		t.Errorf("opt-out with no configure policy = %q; want no flags", got)
	}
}

// TestModuleCFlagsMatchesEnforcement pins the invariant that the flags
// modcompile advertises to out-of-tree projects are the flags it would apply
// itself. If these drift, a module compiled by a project's own Makefile is
// held to a weaker standard than the same file passed to modcompile --install.
func TestModuleCFlagsMatchesEnforcement(t *testing.T) {
	orig := config.CWarnFlags
	t.Cleanup(func() { config.CWarnFlags = orig })
	config.CWarnFlags = ""
	unsetEnv(t, config.CWarnFlagsEnv)

	got := moduleCFlags()
	for _, want := range append(strings.Fields(defaultCFlags), "-Werror") {
		if !strings.Contains(got, want) {
			t.Errorf("moduleCFlags() = %q; missing %q", got, want)
		}
	}
}

// TestCopyFile covers the file copy used when vendoring an external gomod:
// content and mode must survive, and a missing source must be an error rather
// than an empty destination.
func TestCopyFile(t *testing.T) {
	dir := t.TempDir()
	src := filepath.Join(dir, "src.txt")
	dst := filepath.Join(dir, "sub", "dst.txt")
	if err := os.WriteFile(src, []byte("hello"), 0o644); err != nil {
		t.Fatalf("writing: %v", err)
	}
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}

	if err := copyFile(src, dst, 0o600); err != nil {
		t.Fatalf("copyFile: %v", err)
	}
	data, err := os.ReadFile(dst)
	if err != nil {
		t.Fatalf("reading copy: %v", err)
	}
	if string(data) != "hello" {
		t.Errorf("copied content = %q; want hello", data)
	}
	fi, err := os.Stat(dst)
	if err != nil {
		t.Fatalf("stat: %v", err)
	}
	if fi.Mode().Perm() != 0o600 {
		t.Errorf("copied mode = %v; want 0600", fi.Mode().Perm())
	}

	if err := copyFile(filepath.Join(dir, "nosuch"), dst, 0o644); err == nil {
		t.Error("copying a missing file returned nil")
	}
}

// TestDirMirror covers the two-phase mirror: new/changed files are copied in,
// files that disappeared from the source are deleted from the destination, and
// excluded entries are left alone in both directions. Exclusion matches the
// path relative to the source root, so a nested directory can be excluded
// without taking its parent with it.
func TestDirMirror(t *testing.T) {
	base := t.TempDir()
	src := filepath.Join(base, "src")
	dst := filepath.Join(base, "dst")
	for _, d := range []string{
		src, dst,
		filepath.Join(src, "pkg"),
		filepath.Join(src, "skipme"),
		filepath.Join(src, "keep", "nested"),
	} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			t.Fatalf("mkdir %s: %v", d, err)
		}
	}
	write := func(p, content string) {
		t.Helper()
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			t.Fatalf("writing %s: %v", p, err)
		}
	}
	write(filepath.Join(src, "a.go"), "package a")
	write(filepath.Join(src, "pkg", "b.go"), "package b")
	write(filepath.Join(src, "skipme", "c.go"), "package c")
	write(filepath.Join(src, "keep", "d.go"), "package d")
	write(filepath.Join(src, "keep", "nested", "e.go"), "package e")
	// A file only in the destination — must be removed by the mirror.
	write(filepath.Join(dst, "stale.go"), "package stale")
	// The .origin marker is preserved by contract.
	write(filepath.Join(dst, ".origin"), "/somewhere")

	exclude := map[string]bool{"skipme": true, filepath.Join("keep", "nested"): true}
	if err := dirMirror(src, dst, exclude); err != nil {
		t.Fatalf("dirMirror: %v", err)
	}

	// "keep/d.go" proves excluding keep/nested did not exclude its parent.
	for _, rel := range []string{"a.go", "pkg/b.go", "keep/d.go", ".origin"} {
		if _, err := os.Stat(filepath.Join(dst, rel)); err != nil {
			t.Errorf("%s missing from the mirror: %v", rel, err)
		}
	}
	for _, rel := range []string{"stale.go", "skipme", "keep/nested"} {
		if _, err := os.Stat(filepath.Join(dst, rel)); err == nil {
			t.Errorf("%s should not be present in the mirror", rel)
		}
	}

	// A second run is a no-op and must not delete what it just copied.
	if err := dirMirror(src, dst, exclude); err != nil {
		t.Fatalf("dirMirror (second run): %v", err)
	}
	if _, err := os.Stat(filepath.Join(dst, "pkg", "b.go")); err != nil {
		t.Errorf("second mirror run removed pkg/b.go: %v", err)
	}
}

// TestPrintMakeInc covers the make-fragment emitter the build sources: it must
// print assignments, not an empty file.
func TestPrintMakeInc(t *testing.T) {
	old := os.Stdout
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatalf("os.Pipe: %v", err)
	}
	os.Stdout = w
	done := make(chan string, 1)
	go func() {
		buf := make([]byte, 0, 4096)
		tmp := make([]byte, 512)
		for {
			n, err := r.Read(tmp)
			buf = append(buf, tmp[:n]...)
			if err != nil {
				break
			}
		}
		done <- string(buf)
	}()
	printMakeInc()
	_ = w.Close()
	os.Stdout = old
	out := <-done

	if !strings.Contains(out, "=") {
		t.Errorf("printMakeInc produced no assignments:\n%s", out)
	}
}

// TestLocalReplaceDirs covers the mapping from an external module's local
// replace directives to the directories the mirror must skip. Only targets
// inside the module are ours to exclude, and the module root itself never is —
// honouring that would exclude everything.
func TestLocalReplaceDirs(t *testing.T) {
	moduleDir := "/home/dev/formula"
	m := &extGoMod{}
	add := func(old, new string) {
		var r struct {
			Old struct{ Path string }
			New struct{ Path string }
		}
		r.Old.Path = old
		r.New.Path = new
		m.Replace = append(m.Replace, r)
	}
	add("example.com/stub", "./stmak-stub")            // direct child
	add("example.com/deep", "./internal/fake")         // nested child
	add("example.com/abs", moduleDir+"/absolute-stub") // absolute, inside
	add("example.com/outside", "../shared-stub")       // outside the tree
	add("example.com/elsewhere", "/opt/other")         // absolute, outside
	add("example.com/self", ".")                       // the module root
	add("example.com/versioned", "example.com/other")  // not a local replace

	got := m.localReplaceDirs(moduleDir)
	want := map[string]bool{
		"stmak-stub":                      true,
		filepath.Join("internal", "fake"): true,
		"absolute-stub":                   true,
	}
	if len(got) != len(want) {
		t.Fatalf("localReplaceDirs() = %v; want %v", got, want)
	}
	for dir := range want {
		if !got[dir] {
			t.Errorf("localReplaceDirs() missing %q (got %v)", dir, got)
		}
	}
}

// TestWriteGoDeps covers the two requirements deliberately left out of go.deps:
// a module backed by a local stub directory, and stratuMAK itself — emitting
// the latter would have the module require the module it is compiled into.
func TestWriteGoDeps(t *testing.T) {
	m := &extGoMod{}
	addReq := func(path, version string) {
		var r struct {
			Path    string
			Version string
		}
		r.Path, r.Version = path, version
		m.Require = append(m.Require, r)
	}
	addRep := func(old, new string) {
		var r struct {
			Old struct{ Path string }
			New struct{ Path string }
		}
		r.Old.Path, r.New.Path = old, new
		m.Replace = append(m.Replace, r)
	}

	addReq("github.com/eclipse/paho.golang", "v0.22.0")
	addReq(pkgreg.GoModule, "v0.0.0")
	addReq(pkgreg.GoModule+"/pkg/hal", "v0.0.0")
	addReq("example.com/stubbed", "v1.0.0")
	addReq("gopkg.in/yaml.v3", "v3.0.1")
	addRep(pkgreg.GoModule, "./stmak-stub")
	addRep("example.com/stubbed", "./other-stub")

	dir := t.TempDir()
	writeGoDeps(m, dir)

	data, err := os.ReadFile(filepath.Join(dir, "go.deps"))
	if err != nil {
		t.Fatalf("reading go.deps: %v", err)
	}
	got := string(data)

	for _, want := range []string{
		"github.com/eclipse/paho.golang v0.22.0",
		"gopkg.in/yaml.v3 v3.0.1",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("go.deps missing %q; got:\n%s", want, got)
		}
	}
	for _, unwanted := range []string{pkgreg.GoModule, "example.com/stubbed"} {
		if strings.Contains(got, unwanted) {
			t.Errorf("go.deps must not carry %q; got:\n%s", unwanted, got)
		}
	}
}

// TestWriteGoDepsRemovesStale covers the case where a module that once had
// third-party requirements no longer does: the old go.deps must go, or the
// stratuMAK go.mod keeps being regenerated with dependencies nothing needs.
func TestWriteGoDepsRemovesStale(t *testing.T) {
	dir := t.TempDir()
	depsPath := filepath.Join(dir, "go.deps")
	if err := os.WriteFile(depsPath, []byte("stale.example/dep v1.0.0\n"), 0o644); err != nil {
		t.Fatalf("seeding go.deps: %v", err)
	}

	writeGoDeps(&extGoMod{}, dir)

	if _, err := os.Stat(depsPath); !os.IsNotExist(err) {
		t.Errorf("stale go.deps survived (stat error: %v)", err)
	}
}

// pkg-config escapes a space inside an install prefix with a backslash;
// splitting its output on whitespace alone hands gcc a nonexistent include
// dir and a stray input file.
func TestSplitPkgConfigOutput(t *testing.T) {
	for _, tc := range []struct {
		in   string
		want []string
	}{
		{"-I/usr/include -lfoo\n", []string{"-I/usr/include", "-lfoo"}},
		{`-I/opt/Vendor\ SDK/include -L/opt/Vendor\ SDK/lib -lvendor`,
			[]string{"-I/opt/Vendor SDK/include", "-L/opt/Vendor SDK/lib", "-lvendor"}},
		{"", nil},
		{"  \n\t ", nil},
		// A backslash before anything but a space is an ordinary character.
		{`-DPATH=a\b`, []string{`-DPATH=a\b`}},
	} {
		got := splitPkgConfigOutput(tc.in)
		if len(got) != len(tc.want) {
			t.Errorf("splitPkgConfigOutput(%q) = %+v, want %+v", tc.in, got, tc.want)
			continue
		}
		for i := range got {
			if got[i] != tc.want[i] {
				t.Errorf("splitPkgConfigOutput(%q)[%d] = %q, want %q", tc.in, i, got[i], tc.want[i])
			}
		}
	}
}
