// Copyright (C) 2026 Sascha Ittner <sascha.ittner@modusoft.de>
// License: GPL Version 2
package cgen

import (
	"bytes"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/sittner/linuxcnc/src/gomc/internal/modcompile/comp"
	"github.com/sittner/linuxcnc/src/gomc/internal/modcompile/docgen"
)

// compRoots are the in-tree directories holding shipped .comp sources, relative
// to this package's directory.
var compRoots = []string{
	"../../../../hal/components",
	"../../../../hal/user_comps",
	"../../../../hal/drivers",
}

// findComps collects every .comp file under compRoots.
func findComps(t *testing.T) []string {
	t.Helper()
	var files []string
	for _, root := range compRoots {
		if _, err := os.Stat(root); err != nil {
			continue
		}
		err := filepath.Walk(root, func(p string, fi os.FileInfo, err error) error {
			if err != nil {
				return err
			}
			if !fi.IsDir() && strings.HasSuffix(p, ".comp") {
				files = append(files, p)
			}
			return nil
		})
		if err != nil {
			t.Fatalf("walking %s: %v", root, err)
		}
	}
	return files
}

// TestGenerateOverShippedComps is the risk-class-3 guard: one wrong emission
// pattern in cgen replicates into every generated component, so the whole
// shipped .comp corpus is run through parse → C generation → man-page
// generation on every test run. Anything that stops parsing, stops generating,
// or emits obviously malformed C fails here instead of at build time in a
// customer's tree.
func TestGenerateOverShippedComps(t *testing.T) {
	files := findComps(t)
	if len(files) == 0 {
		t.Skip("no in-tree .comp sources found (running outside the linuxcnc tree)")
	}
	// A tripwire on the corpus size: if a future refactor moves the sources,
	// the test must fail rather than silently pass over an empty set.
	if len(files) < 50 {
		t.Fatalf("found only %d .comp files under %v; expected the full shipped corpus", len(files), compRoots)
	}

	for _, path := range files {
		t.Run(filepath.Base(path), func(t *testing.T) {
			src, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("reading: %v", err)
			}
			pkg, err := comp.Parse(path, string(src))
			if err != nil {
				t.Fatalf("parse: %v", err)
			}
			if pkg.Component.Name == "" {
				t.Fatal("parsed component has no name")
			}

			var buf bytes.Buffer
			if err := Generate(&buf, pkg); err != nil {
				t.Fatalf("generate: %v", err)
			}
			out := buf.String()
			checkGeneratedC(t, pkg.Component.Name, out)

			var doc bytes.Buffer
			if err := docgen.Generate(&doc, pkg); err != nil {
				t.Fatalf("docgen: %v", err)
			}
			checkGeneratedMan(t, pkg.Component.Name, doc.String())
		})
	}
}

// unbalanced counts the #if/#endif nesting of the generated C. An arch guard
// that opens without closing (or vice versa) still "generates fine" but breaks
// every downstream compile, so it is checked structurally.
var (
	ifRe    = regexp.MustCompile(`(?m)^\s*#\s*if(n?def)?\b`)
	endifRe = regexp.MustCompile(`(?m)^\s*#\s*endif\b`)
)

// checkGeneratedC asserts the invariants every generated component must hold,
// regardless of what the .comp declared.
func checkGeneratedC(t *testing.T, name, out string) {
	t.Helper()

	if strings.TrimSpace(out) == "" {
		t.Fatal("generated C is empty")
	}
	// The symbol the cmod loader dlsym()s, plus the instance vtable hooks it
	// calls, must always be emitted — this is the whole ABI contract.
	if !strings.Contains(out, "int New(const cmod_env_t *env") {
		t.Errorf("generated C has no New() entry point")
	}
	for _, hook := range []string{"inst_start", "inst_stop", "inst_destroy"} {
		if !strings.Contains(out, hook) {
			t.Errorf("generated C is missing the %s hook", hook)
		}
	}
	// Preprocessor nesting must balance.
	if o, c := len(ifRe.FindAllString(out, -1)), len(endifRe.FindAllString(out, -1)); o != c {
		t.Errorf("unbalanced preprocessor guards: %d #if vs %d #endif", o, c)
	}
	// No template placeholder may survive into the output.
	for _, marker := range []string{"%!", "<no value>", "%!s(", "%!d("} {
		if strings.Contains(out, marker) {
			t.Errorf("generated C contains an unformatted placeholder %q", marker)
		}
	}
	// The generated file is machine output: it must carry the do-not-edit
	// banner so a hand edit is obviously wrong.
	if !strings.Contains(out, "Autogenerated by modcompile") {
		t.Errorf("generated C is missing the do-not-edit banner")
	}
	_ = name
}

// checkGeneratedMan asserts the man page carries the sections halcompile's
// output has; an empty or headerless page is a silent docs regression.
func checkGeneratedMan(t *testing.T, name, out string) {
	t.Helper()
	if strings.TrimSpace(out) == "" {
		t.Fatal("generated man page is empty")
	}
	if !strings.Contains(out, ".TH") {
		t.Errorf("generated man page has no .TH header:\n%s", firstLines(out, 5))
	}
	if !strings.Contains(out, name) {
		t.Errorf("generated man page never mentions the component name %q", name)
	}
	for _, marker := range []string{"%!", "<no value>"} {
		if strings.Contains(out, marker) {
			t.Errorf("generated man page contains an unformatted placeholder %q", marker)
		}
	}
}

func firstLines(s string, n int) string {
	lines := strings.SplitN(s, "\n", n+1)
	if len(lines) > n {
		lines = lines[:n]
	}
	return strings.Join(lines, "\n")
}

// TestGenerateIsDeterministic: the build regenerates C from .comp sources, so a
// map-iteration-order dependency in the emitter would produce spurious diffs
// (and defeat build caching). Generating the same source twice must be
// byte-identical.
func TestGenerateIsDeterministic(t *testing.T) {
	files := findComps(t)
	if len(files) == 0 {
		t.Skip("no in-tree .comp sources found")
	}
	// A handful of the larger comps is enough to catch ordering instability.
	if len(files) > 12 {
		files = files[:12]
	}
	for _, path := range files {
		src, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("reading %s: %v", path, err)
		}
		var first string
		for i := 0; i < 3; i++ {
			pkg, err := comp.Parse(path, string(src))
			if err != nil {
				t.Fatalf("%s parse: %v", path, err)
			}
			var buf bytes.Buffer
			if err := Generate(&buf, pkg); err != nil {
				t.Fatalf("%s generate: %v", path, err)
			}
			if i == 0 {
				first = buf.String()
				continue
			}
			if buf.String() != first {
				t.Fatalf("%s: generation is not deterministic (run %d differs)", path, i+1)
			}
		}
	}
}
