// Copyright (C) 2026 Sascha Ittner <sascha.ittner@modusoft.de>
// License: GPL Version 2
package task

// Go-side provider for the mcode_handler GMI API. A cmod calls
// mcode_handler_api_get(env->api, "<milltask>") + register_handler(mcode, fn, ud),
// which the generated cgo bridge routes into RegisterHandler below; that installs
// a wrapper in the Go mcodeHandler registry. When the interpreter hits M100-M199,
// the sequencer submits the call and the wrapper invokes the cmod's C handler.
//
// The registration bridge (BuildMcodeHandlerCallbacks / the //export trampoline)
// is generated by gmicompile --server-go — this file provides only the milltask-
// specific pieces: the McodeHandlerCallbacks impl and the Go->C invocation of the
// registered handler (with the abort channel bridged to a pollable fd).

/*
#cgo CFLAGS: -I${SRCDIR}/../../generated/gmi/mcode_handler -I${SRCDIR}/../../pkg/cmodule
#define MCODE_HANDLER_API_CGO
#include "mcode_handler_api.h"

// Go -> C: invoke a registered handler with a freshly built call struct. fn and
// user_data arrive as uintptr_t (the opaque-pointer transit type the generated
// bridge hands the provider) and are cast back to the real function pointer /
// void* here in C, so Go never performs a uintptr->unsafe.Pointer conversion
// (which -race / -d=checkptr flags).
static int32_t invoke_mcode_handler(uintptr_t fn, uintptr_t user_data,
                                    int32_t abort_fd, int32_t mcode, double p, double q) {
    mcode_handler_mcode_call_t call;
    call.abort_fd = abort_fd;
    call.mcode = mcode;
    call.p_number = p;
    call.q_number = q;
    return ((mcode_handler_handler_cb)fn)(&call, (void *)user_data);
}
*/
import "C"

import (
	"os"

	"github.com/stratuMAK/stratumak/src/stmak/generated/gmi/mcode_handler"
	"github.com/stratuMAK/stratumak/src/stmak/internal/apiserver"
)

// mcodeProviderBridge implements the generated mcode_handler.McodeHandlerCallbacks
// interface, backed by the milltask mcodeHandler registry.
type mcodeProviderBridge struct {
	h *mcodeHandler
}

// RegisterHandler is invoked (via the generated cgo bridge) when a cmod registers
// an M-code handler. fn is the cmod's C callback function pointer and userData its
// opaque context, both as uintptr_t. It installs a Go wrapper that invokes the C
// handler when the M-code fires, bridging the Go abort channel to a pollable fd.
func (b *mcodeProviderBridge) RegisterHandler(mcode int32, fn uint64, userData uint64) (int32, error) {
	cFn := C.uintptr_t(fn)
	cUser := C.uintptr_t(userData)
	wrapper := func(call *McodeCall) int {
		rfd, wfd, err := os.Pipe()
		if err != nil {
			return -1
		}
		defer func() { _ = rfd.Close() }()
		stop := make(chan struct{})
		go func() {
			select {
			case <-call.abortCh:
				_, _ = wfd.Write([]byte{1})
			case <-stop:
			}
			_ = wfd.Close()
		}()
		rc := C.invoke_mcode_handler(cFn, cUser, C.int32_t(rfd.Fd()),
			C.int32_t(call.Mcode), C.double(call.P), C.double(call.Q))
		close(stop)
		return int(rc)
	}

	if err := b.h.RegisterHandler(int(mcode), wrapper); err != nil {
		return 0, err
	}
	return 0, nil
}

// registerMcodeHandlerProvider registers the mcode_handler GMI API under the given
// milltask instance name, backed by the mcodeHandler registry h. Returns a cleanup
// func that frees the generated C callbacks struct (and releases its cgo.Handle).
func registerMcodeHandlerProvider(reg *apiserver.Registry, instance string, h *mcodeHandler) (func(), error) {
	ptr := mcode_handler.BuildMcodeHandlerCallbacks(&mcodeProviderBridge{h: h})
	if err := reg.Register("mcode_handler", 1, instance, ptr); err != nil {
		mcode_handler.FreeMcodeHandlerCallbacks(ptr)
		return nil, err
	}
	return func() {
		mcode_handler.FreeMcodeHandlerCallbacks(ptr)
	}, nil
}
