// Shared ESLint flat config for the gomc webapps.
//
// Scope: the five non-deferred apps' hand-written source. classicladder is
// excluded (frozen/mid-migration — same reason the review skipped it), and so
// is every app's src/generated/** (code-generated by gmicompile — reviewed via
// the generator, not linted here) and build config.
//
// Non-type-aware: this is a correctness/consistency gate layered on top of the
// per-app `vue-tsc` type check, not a replacement for it. Keeping it off the
// type graph means one config lints all apps without wiring five tsconfigs.
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import pluginVue from 'eslint-plugin-vue';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/src/generated/**',
      '**/*.config.ts',
      '**/*.config.mjs',
      'classicladder/**',
      'eslint.config.mjs',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  // 'essential' = Vue's Priority-A error-prevention rules only. This is a
  // correctness gate layered on vue-tsc, not a template formatter — the
  // 'recommended' preset's attribute-per-line / self-closing / newline rules
  // are style the codebase never adopted and there is no webapp formatter.
  ...pluginVue.configs['flat/essential'],
  {
    files: ['**/*.vue'],
    languageOptions: {
      parserOptions: { parser: tseslint.parser },
    },
  },
  {
    rules: {
      // App.vue / single-purpose components are intentionally single-word.
      'vue/multi-word-component-names': 'off',
      // A leading underscore marks an intentionally-unused binding (unused
      // event-handler args, caught errors kept for shape).
      '@typescript-eslint/no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
      }],
    },
  },
);
