.\"
.TH CLASSICLADDER "9" "2008-11-23" "LinuxCNC Documentation" "HAL Component"

.SH NAME
ClassicLadder \- realtime software plc based on ladder logic
.SH SYNOPSIS
\fBload classicladder  [numRungs=\fIN\fB] [numBits=\fIN\fB] [numWords=\fIN\fB] [numTimers=\fIN\fB] [numMonostables=\fIN\fB] [numCounters=\fIN\fB] [numPhysInputs=\fIN\fB] [numPhysOutputs=\fIN\fB] [numArithmExpr=\fIN\fB] [numSections=\fIN\fB] [numSymbols=\fIN\fB] [numS32in=\fIN\fB] [numS32out=\fIN\fB] [numFloatIn=\fIN\fB] [numFloatOut=\fIN\fB] [modbus_port=\fIN\fB] [\fIfile name\fB]

.SH DESCRIPTION
ClassicLadder is a single module.  It provides the HAL pins and the realtime
scan function, loads the ladder program, and serves the editor and variable
monitor over the web interface.  The trailing argument names the \fB.clp\fR
project to load; when it is given, the PLC starts running as soon as the
program is loaded.  Without it the module comes up stopped, and a project can
be loaded later through the API.
.P
Each period (minimum 1000000 ns), ClassicLadder reads the inputs, evaluates the
ladder logic, and then writes the outputs.  Adding the scan function to a
faster thread does not make the ladder scan faster than once per millisecond;
the leftover time is carried into the next scan.

.SH PINS

.TP
\fBclassicladder.0.in\-\fINN\fB\fR IN bit
These bit signal pins map to \fB%I\fINN\fR variables in ClassicLadder.

.TP
\fBclassicladder.0.out\-\fINN\fB\fR OUT bit
These bit signal pins map to \fB%Q\fINN\fR variables in ClassicLadder.
Output from ClassicLadder.

.TP
\fBclassicladder.0.s32in\-\fINN\fB\fR IN s32
Integer input from ClassicLadder.
These s32 signal pins map to \fB%IW\fINN\fR variables in ClassicLadder.

.TP
\fBclassicladder.0.s32out\-\fINN\fB\fR OUT s32
Integer output from ClassicLadder.
These s32 signal pins map to \fB%QW\fINN\fR variables in ClassicLadder.

.TP
\fBclassicladder.0.floatin\-\fINN\fB\fR IN float
Integer input from ClassicLadder.
These float signal pins map to \fB%IF\fINN\fR variables in ClassicLadder.
These are truncated to S32 values internally. eg 7.5 will be 7.

.TP
\fBclassicladder.0.floatout\-\fINN\fB\fR OUT float
Float output from ClassicLadder.
These float signal pins map to \fB%QF\fINN\fR variables in ClassicLadder.

.SH FUNCTIONS

.TP
\fBclassicladder.0.refresh\fR FP
The rung update rate. Add this to the servo thread.
You can added it to a faster thread but it.
Will update no faster than once every 1 millisecond (1000000 ns).

.SH BUGS
See http://wiki.linuxcnc.org/cgi\-bin/wiki.pl?ClassicLadder_Ver_7.124 for the latest.

.SH SEE ALSO
\fIClassicLadder\fR chapters in the LinuxCNC documentation for a full description of the \fBClassicLadder\fR syntax and examples.

http://wiki.linuxcnc.org/cgi\-bin/wiki.pl?ClassicLadder_Ver_7.124
