#!/bin/bash
# rt-effects-check.sh — verify the RT path with clang's function-effects
# analysis (see RT_HARDENING_CHECKLIST.md §2.1).
#
# Compiles the RT translation units with -Wfunction-effects (treated as an
# error) using the pinned clang provided by scripts/rt-clang.sh:
#
#   1. the core RTAPI/HAL library TUs (thread creation, funct dispatch),
#   2. the halscope RT sampler,
#   3. motmod — the motion controller (servo cycle + command handler),
#   4. tpmod + homemod (+cia402) — trajectory planner and homing,
#   5. lcec — the EtherCAT driver (masters, slaves, all device drivers),
#   6. hostmot2 — the Mesa FPGA driver (core, modules, eth/pci/epp transports),
#   7. every .comp component, freshly generated by modcompile (their functs
#      are typed GOMC_NONBLOCKING by the generator).
#
# Anything RTAPI_NONBLOCKING/GOMC_NONBLOCKING is verified transitively:
# allocation, locking, blocking calls, and static locals in the RT path
# are diagnosed.  Trust boundaries (RTAPI_NONBLOCKING_TRUSTED_*) are
# deliberate, justified exemptions — grep for them to audit.
#
# Usage: scripts/rt-effects-check.sh   (from the top-level directory,
# after a build: needs bin/modcompile and the generated GMI headers).
#
# Copyright (C) 2026 Sascha Ittner <sascha.ittner@modusoft.de>
# License: GPL Version 2

set -eu

TOP="$(cd "$(dirname "$0")/.." && pwd)"
cd "$TOP"

CLANG="$("$TOP/scripts/rt-clang.sh")"
echo "rt-effects-check: using $CLANG"

if [ ! -x "$TOP/bin/modcompile" ]; then
    echo "rt-effects-check: bin/modcompile not found — run make first" >&2
    exit 1
fi

CFLAGS_COMMON="-std=gnu11 -fsyntax-only -Wfunction-effects -Werror=function-effects"

fail=0
checked=0
skipped=0

# Scratch root for generated comps and per-TU depfiles (merged at the end).
SCRATCH="$(mktemp -d)"
trap 'rm -rf "$SCRATCH"' EXIT
DEPDIR="$SCRATCH/deps"
mkdir -p "$DEPDIR"

check_tu() {
    # check_tu <file> <extra include flags...>
    local tu="$1"; shift
    checked=$((checked+1))
    # -MMD records exactly which headers this TU includes (works under
    # -fsyntax-only).  The staleness guard at the end reads these to check the
    # generated GMI headers against their IDLs — the set is discovered by the
    # compiler, never a hand-kept list.
    if ! "$CLANG" $CFLAGS_COMMON -MMD -MF "$DEPDIR/dep-$checked.d" \
            -MT rt-effects-check "$@" "$tu"; then
        echo "rt-effects-check: FAILED: $tu" >&2
        fail=1
    fi
}

# --- 1+2. Core RTAPI/HAL library + halscope RT sampler ---------------------

CORE_INC="-Isrc/hal -Isrc -Isrc/rtapi -Iinclude"
check_tu src/gomc/internal/hallib/uspace_rtapi_lib.c   $CORE_INC
check_tu src/gomc/internal/hallib/uspace_rtapi_string.c $CORE_INC
check_tu src/gomc/internal/hallib/hal_lib.c            $CORE_INC
check_tu src/gomc/internal/halscope/halscope_rt.c \
    $CORE_INC -Isrc/gomc/generated/gmi/halscope -Isrc/gomc/pkg/cmodule

# --- 3. motmod — the motion controller cmod --------------------------------
# Same defines/includes as the motmod.so rule in src/emc/motion/Submakefile.

MOTMOD_INC="-DUSPACE -D_GNU_SOURCE -Drealtime -DSEQUENTIAL_SUPPORT \
    -DMOTMOD_INTERNAL \
    -fno-builtin-sin -fno-builtin-cos -fno-builtin-sincos \
    -fno-strict-aliasing -fwrapv \
    -Isrc -Iinclude -Isrc/rtapi -Isrc/gomc/pkg/cmodule \
    -Isrc/gomc/generated/gmi/kins -Isrc/gomc/generated/gmi/tp \
    -Isrc/gomc/generated/gmi/home -Isrc/gomc/generated/gmi/mot \
    -Isrc/gomc/generated/gmi/motctl -Isrc/gomc/generated/gmi/motstat \
    -Isrc/emc/tp -Isrc/emc/motion"

for tu in src/emc/motion/motion.c src/emc/motion/command.c \
          src/emc/motion/control.c src/emc/motion/axis.c \
          src/emc/motion/simple_tp.c src/emc/motion/motctl_handlers.c \
          src/emc/motion/motstat_handlers.c src/emc/kinematics/cubic.c; do
    check_tu "$tu" $MOTMOD_INC
done

# --- 4. tpmod + homemod — trajectory planner and homing cmods --------------
# Same defines/includes as their rules in src/Makefile.  posemath is
# in-scope (annotated + verified, not trusted).  -fno-builtin-sin/-cos
# from the production rule is intentionally NOT passed: it would make
# libm sin/cos non-builtin and thus non-inferrable for the analysis.

TPMOD_INC="-DUSPACE -D_GNU_SOURCE -Drealtime \
    -fno-strict-aliasing -fwrapv \
    -Isrc -Isrc/libnml/posemath -Isrc/emc/nml_intf -Iinclude \
    -Isrc/gomc/pkg/cmodule -Isrc/gomc/generated/gmi/tp \
    -Isrc/gomc/generated/gmi/mot -Isrc/emc/motion -Isrc/emc/tp"

for tu in src/emc/tp/tp.c src/emc/tp/tc.c src/emc/tp/tcq.c \
          src/emc/tp/spherical_arc.c src/emc/tp/blendmath.c \
          src/emc/nml_intf/emcpose.c src/libnml/posemath/_posemath.c; do
    check_tu "$tu" $TPMOD_INC
done

HOMEMOD_INC="-DUSPACE -D_GNU_SOURCE -Drealtime \
    -fno-strict-aliasing -fwrapv \
    -Isrc -Iinclude -Isrc/gomc/pkg/cmodule \
    -Isrc/gomc/generated/gmi/home -Isrc/gomc/generated/gmi/mot \
    -Isrc/emc/motion"

for tu in src/emc/motion/homing.c src/emc/motion/homemod_cia402.c; do
    check_tu "$tu" $HOMEMOD_INC
done

# --- 5. lcec — the EtherCAT master driver ----------------------------------
# Same defines/includes as the ethercat.so rule.  The EtherLab master
# library itself is a separate audit item; its RT API is trusted via
# src/hal/drivers/ethercat/ecrt_rt_api.h.

LCEC_INC="-DULAPI -URTAPI \
    -Isrc/hal/drivers/ethercat -Isrc -Iinclude \
    -Isrc/gomc/generated/gmi/ethercat -Isrc/gomc/pkg/cmodule"

for tu in src/hal/drivers/ethercat/main.c src/hal/drivers/ethercat/master.c \
          src/hal/drivers/ethercat/slave.c src/hal/drivers/ethercat/util.c \
          src/hal/drivers/ethercat/dcsync_r2m.c src/hal/drivers/ethercat/dcsync_m2r.c \
          src/hal/drivers/ethercat/typelist.c \
          src/hal/drivers/ethercat/classes/class_enc.c \
          src/hal/drivers/ethercat/classes/class_ax5.c \
          src/hal/drivers/ethercat/devices/*.c; do
    check_tu "$tu" $LCEC_INC
done

# --- 6. hostmot2 — Mesa FPGA driver core + transports -----------------------
# Same defines/includes as the rules in the mesa-hostmot2 Submakefile.
# Every .c in the driver directory is checked (glob, so new TUs cannot
# silently escape the gate).  The board register exchange of the eth and
# spi/spix transports (raw LBP16 from the servo thread over UDP or spidev)
# is those transports' documented architecture — trusted at the
# eth_socket_send/recv, spi_ioc_message and spidev_ioc_message seams.

HM2_INC="-DUSPACE -D_GNU_SOURCE -Drealtime \
    -fno-strict-aliasing -fwrapv \
    -Isrc/rtapi/pci -Isrc/rtapi/parport -Isrc -Iinclude \
    -Isrc/hal/drivers/mesa-hostmot2 -Isrc/gomc/pkg/cmodule \
    -Isrc/gomc/generated/gmi/hm2_llio -Isrc/gomc/generated/gmi/hm2_serial"

for tu in src/hal/drivers/mesa-hostmot2/*.c; do
    check_tu "$tu" $HM2_INC
done

# --- 7. All .comp components (generated by modcompile) ---------------------

COMP_INC="-Isrc/gomc/pkg/cmodule \
    -Isrc/gomc/generated/gmi/kins \
    -Isrc/gomc/generated/gmi/home \
    -Isrc/gomc/generated/gmi/mot \
    -Isrc/gomc/generated/gmi/manualtoolchange \
    -Isrc/gomc/generated/gmi/hm2_serial"

GEN_DIR="$SCRATCH/gen"
mkdir -p "$GEN_DIR"

for comp in src/hal/components/*.comp src/hal/drivers/*.comp; do
    name="$(basename "$comp" .comp)"
    gen="$GEN_DIR/$name.c"
    # Comps that modcompile cannot generate (unsupported legacy features)
    # are skipped — they are not part of the gomc build either.
    if ! ./bin/modcompile --preprocess "$comp" > "$gen" 2>/dev/null; then
        echo "rt-effects-check: skipping $name (modcompile cannot generate it)"
        skipped=$((skipped+1))
        continue
    fi
    check_tu "$gen" $COMP_INC
done

# Read-only staleness guard.  The per-TU depfiles name exactly the generated GMI
# headers the RT TUs #include (discovered by the compiler, not a hand list).  If
# any is older than its IDL, a full build has not regenerated it — a pull or
# branch switch left it stale — and the check above just compiled against a
# stale header, so its verdict is unreliable.  Report that instead of a silent
# pass.  This only READS mtimes: it never writes to or regenerates the tree, so
# it cannot perturb a subsequent make.  Header gomc/generated/gmi/<api>/... maps
# to IDL gmi/idl/<api>.gmi by directory name.
stale=""
for h in $(cat "$DEPDIR"/*.d 2>/dev/null \
        | grep -oE 'src/gomc/generated/gmi/[A-Za-z0-9_]+/[A-Za-z0-9_]+_api\.h' \
        | sort -u); do
    api="$(basename "$(dirname "$h")")"
    idl="src/gmi/idl/$api.gmi"
    if [ -f "$idl" ] && [ "$idl" -nt "$h" ]; then
        case " $stale " in *" $api "*) ;; *) stale="$stale $api" ;; esac
    fi
done
if [ -n "$stale" ]; then
    echo "rt-effects-check: ERROR: stale generated GMI header(s):$stale" >&2
    echo "rt-effects-check: their IDL is newer — run 'make' first, then re-run" >&2
    fail=1
fi

if [ "$fail" -ne 0 ]; then
    echo "rt-effects-check: FAILED ($checked TUs checked)" >&2
    exit 1
fi
echo "rt-effects-check: OK — $checked TUs verified, $skipped skipped"
