#!/bin/bash
# rt-effects-check.sh — verify the RT path with clang's function-effects
# analysis (see RT_HARDENING_CHECKLIST.md §2.1).
#
# Compiles the RT translation units with -Wfunction-effects (treated as an
# error) using the pinned clang provided by scripts/rt-clang.sh:
#
#   1. the core RTAPI/HAL library TUs (thread creation, funct dispatch),
#   2. the halscope RT sampler,
#   3. every .comp component, freshly generated by modcompile (their functs
#      are typed GOMC_NONBLOCKING by the generator).
#
# Anything RTAPI_NONBLOCKING/GOMC_NONBLOCKING is verified transitively:
# allocation, locking, blocking calls, and static locals in the RT path
# are diagnosed.  Trust boundaries (RTAPI_NONBLOCKING_TRUSTED_*) are
# deliberate, justified exemptions — grep for them to audit.
#
# Usage: scripts/rt-effects-check.sh   (from the top-level directory,
# after a build: needs bin/modcompile and the generated GMI headers).
#
# Copyright (C) 2026 Sascha Ittner <sascha.ittner@modusoft.de>
# License: GPL Version 2

set -eu

TOP="$(cd "$(dirname "$0")/.." && pwd)"
cd "$TOP"

CLANG="$("$TOP/scripts/rt-clang.sh")"
echo "rt-effects-check: using $CLANG"

if [ ! -x "$TOP/bin/modcompile" ]; then
    echo "rt-effects-check: bin/modcompile not found — run make first" >&2
    exit 1
fi

CFLAGS_COMMON="-std=gnu11 -fsyntax-only -Wfunction-effects -Werror=function-effects"

fail=0
checked=0
skipped=0

check_tu() {
    # check_tu <file> <extra include flags...>
    local tu="$1"; shift
    checked=$((checked+1))
    if ! "$CLANG" $CFLAGS_COMMON "$@" "$tu"; then
        echo "rt-effects-check: FAILED: $tu" >&2
        fail=1
    fi
}

# --- 1+2. Core RTAPI/HAL library + halscope RT sampler ---------------------

CORE_INC="-Isrc/hal -Isrc -Isrc/rtapi -Iinclude"
check_tu src/gomc/internal/hallib/uspace_rtapi_lib.c   $CORE_INC
check_tu src/gomc/internal/hallib/uspace_rtapi_string.c $CORE_INC
check_tu src/gomc/internal/hallib/hal_lib.c            $CORE_INC
check_tu src/gomc/internal/halscope/halscope_rt.c \
    $CORE_INC -Isrc/gomc/generated/gmi/halscope -Isrc/gomc/pkg/cmodule

# --- 3. All .comp components (generated by modcompile) ---------------------

COMP_INC="-Isrc/gomc/pkg/cmodule \
    -Isrc/gomc/generated/gmi/kins \
    -Isrc/gomc/generated/gmi/home \
    -Isrc/gomc/generated/gmi/mot \
    -Isrc/gomc/generated/gmi/manualtoolchange \
    -Isrc/gomc/generated/gmi/hm2_serial"

GEN_DIR="$(mktemp -d)"
trap 'rm -rf "$GEN_DIR"' EXIT

for comp in src/hal/components/*.comp src/hal/drivers/*.comp; do
    name="$(basename "$comp" .comp)"
    gen="$GEN_DIR/$name.c"
    # Comps that modcompile cannot generate (unsupported legacy features)
    # are skipped — they are not part of the gomc build either.
    if ! ./bin/modcompile --preprocess "$comp" > "$gen" 2>/dev/null; then
        echo "rt-effects-check: skipping $name (modcompile cannot generate it)"
        skipped=$((skipped+1))
        continue
    fi
    check_tu "$gen" $COMP_INC
done

if [ "$fail" -ne 0 ]; then
    echo "rt-effects-check: FAILED ($checked TUs checked)" >&2
    exit 1
fi
echo "rt-effects-check: OK — $checked TUs verified, $skipped skipped"
