/* confdefs.h */
#define PACKAGE_NAME "LinuxCNC"
#define PACKAGE_TARNAME "linuxcnc"
#define PACKAGE_VERSION "0.1.0"
#define PACKAGE_STRING "LinuxCNC 0.1.0"
#define PACKAGE_BUGREPORT "emc-developers@lists.sourceforge.net"
#define PACKAGE_URL ""
#define HAVE_CXX17 1
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define STDC_HEADERS 1
#define HAVE_LIBTIRPC 1
#define RTAPI_USPACE /**/
#define RTDIR "/home/sascha/source/linuxcnc/src"
#define HIDRAW_H_USABLE /**/
#define HAVE_LIBMODBUS3 yes
#define HAVE_LIBUSB10 yes
#define LIBGPIOD_VER 202
#define MODULE_EXT ".so"
#define EMC2_DEFAULT_NMLFILE "/usr/share/linuxcnc/linuxcnc.nml"
#define EMC2_DEFAULT_TOOLTABLE "/usr/share/doc/linuxcnc/examples/sample-configs/common/tool.tbl"
#define EMC2_HOME "/usr"
#define EMC2_BIN_DIR "/usr/bin"
#define EMC2_TCL_DIR "/usr/lib/tcltk/linuxcnc"
#define EMC2_HELP_DIR "/usr/share/doc/linuxcnc"
#define EMC2_RTLIB_DIR "/usr/lib/linuxcnc/modules"
#define EMC2_GOMOD_DIR "/usr/lib/linuxcnc/gomod"
#define EMC2_CMOD_DIR "/usr/lib/linuxcnc/cmod"
#define EMC2_LANG_DIR "/usr/lib/tcltk/linuxcnc/msgs"
#define EMC2_PO_DIR "/usr/share/locale"
#define EMC2_NCFILES_DIR "/usr/share/linuxcnc/ncfiles"
#define EMC2_IMAGE_DIR "/usr/share/linuxcnc"
#define HAVE_BOOST /**/
#define HAVE_PYTHON "3.13"
#define HAVE_BOOST_PYTHON /**/
#define HAVE_SYS_IO_H 1
#define HAVE_SYS_WAIT_H 1
#define HAVE_SEMTIMEDOP 1
#define LIBDL $LIBDL
#define HAVE_CLOCK_NANOSLEEP 1
