// Copyright (C) 2026 Sascha Ittner <sascha.ittner@modusoft.de>
// License: GPL Version 2
package cgen

import (
	"fmt"
	"io"
	"strings"

	"github.com/sittner/linuxcnc/src/gomc/internal/gmicompile/ast"
)

// GenerateBridgeGo writes a Go file that provides:
//   - A Go interface (<Api>Callbacks) for Go providers to implement
//   - Build<Api>Callbacks(impl) — allocates a C callbacks_t with //export trampolines
//   - //export trampoline functions that dispatch to the Go interface via cgo.Handle
//
// This file goes into the SAME package as the --server-meta output (the cgo dispatch
// package). It uses the same C header and shares types with the _cgo.go file.
func GenerateBridgeGo(w io.Writer, api *ast.API, packageName string) error {
	g := &bridgeGoGen{api: api, w: w, pkg: packageName}
	return g.generate()
}

type bridgeGoGen struct {
	w   io.Writer
	api *ast.API
	pkg string
	err error
}

func (g *bridgeGoGen) printf(format string, args ...interface{}) {
	if g.err != nil {
		return
	}
	_, g.err = fmt.Fprintf(g.w, format, args...)
}

func (g *bridgeGoGen) generate() error {
	g.emitPreamble()
	g.emitInterface()
	g.emitBuildCallbacks()
	g.emitTrampolines()
	return g.err
}

// --- Preamble ---

func (g *bridgeGoGen) emitPreamble() {
	apiUpper := strings.ToUpper(g.api.Name)
	apiName := g.api.Name

	g.printf("// Code generated by gmicompile --server-go - DO NOT EDIT.\n")
	EmitMeta(g.w, g.api, "//")
	g.printf("\n")
	g.printf("package %s\n\n", g.pkg)

	// cgo preamble — references same header for callbacks_t type.
	if len(g.api.Imports) > 0 {
		var flags []string
		for _, imp := range g.api.Imports {
			flags = append(flags, fmt.Sprintf("-I../%s", imp.Name))
		}
		g.printf("// #cgo CFLAGS: %s\n", strings.Join(flags, " "))
	}

	g.printf("/*\n")
	g.printf("#define %s_API_CGO\n", apiUpper)
	for _, imp := range g.api.Imports {
		g.printf("#define %s_API_CGO\n", strings.ToUpper(imp.Name))
	}
	g.printf("#include \"%s_api.h\"\n", g.api.Name)
	g.printf("#include <stdlib.h>\n")
	g.printf("#include <string.h>\n")
	g.printf("#include <stdint.h>\n")

	// Emit extern declarations for //export trampoline functions.
	// Without these, cgo cannot resolve the function pointer references
	// used in BuildXxxCallbacks.
	g.printf("\n// Forward declarations of //export trampolines\n")
	for _, fn := range g.api.Funcs {
		if fn.Publish {
			continue
		}
		if fn.Watch && fn.Method == "" {
			continue
		}
		g.emitExternDecl(apiName, fn)
	}

	// Emit a static C helper that builds the callbacks struct.
	// This avoids cgo type-system issues with function pointer assignments.
	// ctx is a cgo.Handle (an opaque integer, NOT a real address). It must
	// only ever exist on the Go side as a uintptr_t scalar: a handle value
	// sitting in a Go pointer-typed slot (unsafe.Pointer) is fatal when a GC
	// stack scan hits it ("invalid pointer found on stack"), and uintptr →
	// unsafe.Pointer is also flagged by -race/-d=checkptr. We cast it into
	// the void* ctx field here in C; the trampolines receive it back as
	// uintptr_t and Free reads it out via _bridge_*_get_ctx.
	g.printf("\nstatic %s_callbacks_t *_bridge_build_%s_callbacks(uintptr_t ctx) {\n", apiName, apiName)
	g.printf("\t%s_callbacks_t *cbs = calloc(1, sizeof(%s_callbacks_t));\n", apiName, apiName)
	g.printf("\tcbs->ctx = (void *)ctx;\n")
	for _, fn := range g.api.Funcs {
		if fn.Publish {
			continue
		}
		if fn.Watch && fn.Method == "" {
			continue
		}
		fnSnake := toSnakeCase(fn.Name)
		// Cast to silence type mismatches between cgo export signatures and typedef fn ptrs
		g.printf("\tcbs->%s = (%s_%s_fn)%s_bridge_%s;\n", fnSnake, apiName, fnSnake, apiName, fnSnake)
	}
	g.printf("\treturn cbs;\n")
	g.printf("}\n")

	g.printf("\nstatic uintptr_t _bridge_%s_get_ctx(const %s_callbacks_t *cbs) {\n", apiName, apiName)
	g.printf("\treturn (uintptr_t)cbs->ctx;\n")
	g.printf("}\n")

	g.printf("\n*/\n")
	g.printf("import \"C\"\n\n")

	g.printf("import (\n")
	g.printf("\t\"encoding/json\"\n")
	g.printf("\t\"fmt\"\n")
	g.printf("\t\"runtime/cgo\"\n")
	if g.hasWatchFuncs() {
		g.printf("\t\"time\"\n")
	}
	g.printf("\t\"unsafe\"\n")
	g.printf("\n")
	g.printf("\t\"github.com/sittner/linuxcnc/src/gomc/internal/apiserver\"\n")
	g.printf(")\n\n")

	g.printf("var _ = unsafe.Pointer(nil) // suppress unused\n")
	g.printf("var _ = json.Marshal // suppress unused\n")
	g.printf("var _ = fmt.Sprintf // suppress unused\n")
	if g.hasWatchFuncs() {
		g.printf("var _ time.Duration // suppress unused\n")
	}
	g.printf("\n")
}

// --- Interface ---

func (g *bridgeGoGen) emitInterface() {
	apiPascal := toPascalCase(g.api.Name)
	ifaceName := apiPascal + "Callbacks"

	g.printf("// --- Provider Interface ---\n\n")
	g.printf("// %s defines the API methods that Go providers must implement.\n", ifaceName)
	g.printf("type %s interface {\n", ifaceName)

	for _, fn := range g.api.Funcs {
		if fn.Publish {
			continue
		}
		if fn.Watch && fn.Method == "" {
			continue // watch-only, not part of the callback vtable
		}
		methodName := toPascalCase(fn.Name)
		params := g.goMethodParams(fn)
		ret := g.goMethodReturn(fn)
		g.printf("\t%s(%s) %s\n", methodName, params, ret)
	}
	g.printf("}\n\n")
}

// --- BuildCallbacks ---

func (g *bridgeGoGen) emitBuildCallbacks() {
	apiName := g.api.Name
	apiPascal := toPascalCase(apiName)
	cbsType := fmt.Sprintf("C.%s_callbacks_t", apiName)
	ifaceName := apiPascal + "Callbacks"
	funcName := "Build" + apiPascal + "Callbacks"

	g.printf("// --- Callback Builder ---\n\n")
	g.printf("// %s allocates a C %s_callbacks_t struct with function pointers\n", funcName, apiName)
	g.printf("// pointing to //export trampolines that dispatch to the Go interface.\n")
	g.printf("// The returned pointer must be freed with Free%sCallbacks when done.\n", apiPascal)
	g.printf("func %s(impl %s) unsafe.Pointer {\n", funcName, ifaceName)
	g.printf("\th := cgo.NewHandle(impl)\n")
	// Pass the handle as an integer (C.uintptr_t), not unsafe.Pointer(h): a
	// cgo.Handle is a uintptr, and uintptr->unsafe.Pointer is bad pointer
	// arithmetic under -d=checkptr (enabled by -race).
	g.printf("\tcbs := C._bridge_build_%s_callbacks(C.uintptr_t(h))\n", apiName)
	g.printf("\treturn unsafe.Pointer(cbs)\n")
	g.printf("}\n\n")

	// Free function
	freeName := "Free" + apiPascal + "Callbacks"
	g.printf("// %s releases the cgo.Handle and frees the C struct.\n", freeName)
	g.printf("func %s(ptr unsafe.Pointer) {\n", freeName)
	g.printf("\tcbs := (*%s)(ptr)\n", cbsType)
	g.printf("\tcgo.Handle(C._bridge_%s_get_ctx(cbs)).Delete()\n", apiName)
	g.printf("\tC.free(unsafe.Pointer(cbs))\n")
	g.printf("}\n\n")

	// Register function — convenience wrapper that builds callbacks and registers
	regName := "Register" + apiPascal + "API"
	g.printf("// %s registers a Go implementation of the %s API with the apiserver registry.\n", regName, apiName)
	g.printf("func %s(registry *apiserver.Registry, instance string, impl %s) error {\n", regName, ifaceName)
	g.printf("\tptr := %s(impl)\n", funcName)
	g.printf("\treturn registry.Register(%q, %d, instance, ptr)\n", apiName, g.api.Version)
	g.printf("}\n\n")
}

// --- Trampolines ---

func (g *bridgeGoGen) emitTrampolines() {
	apiName := g.api.Name
	apiPascal := toPascalCase(apiName)
	ifaceName := apiPascal + "Callbacks"

	g.printf("// --- //export Trampolines ---\n\n")

	for _, fn := range g.api.Funcs {
		if fn.Publish {
			continue
		}
		if fn.Watch && fn.Method == "" {
			continue
		}
		g.emitOneTrampoline(apiName, ifaceName, fn)
	}
}

func (g *bridgeGoGen) emitOneTrampoline(apiName, ifaceName string, fn ast.Func) {
	fnSnake := toSnakeCase(fn.Name)
	exportName := fmt.Sprintf("%s_bridge_%s", apiName, fnSnake)
	methodName := toPascalCase(fn.Name)

	// Build C parameter list: ctx + C-typed params. ctx carries a cgo.Handle
	// integer, so it is typed uintptr_t — never unsafe.Pointer, which would
	// put a non-address value in a GC-scanned pointer slot.
	var cParams []string
	cParams = append(cParams, "ctx C.uintptr_t")

	for _, p := range fn.Params {
		cParams = append(cParams, g.trampolineParam(apiName, p))
		if p.Type.Kind == ast.TypeSlice && !p.IsOut {
			cParams = append(cParams, fmt.Sprintf("%s_len C.size_t", escapeGoKeyword(p.Name)))
		}
	}

	// Determine C return type
	cRet := ""
	if fn.Return != nil {
		if fn.Return.Kind == ast.TypeSlice {
			cRet = fmt.Sprintf(" C.%s_%s_result_t", apiName, fnSnake)
		} else {
			cRet = " " + cTypeForAPICgo(apiName, *fn.Return)
		}
	}

	// Check for out-params
	var outParams []ast.Param
	for _, p := range fn.Params {
		if p.IsOut {
			outParams = append(outParams, p)
		}
	}
	hasOutParams := len(outParams) > 0

	g.printf("//export %s\n", exportName)
	g.printf("func %s(%s)%s {\n", exportName, strings.Join(cParams, ", "), cRet)

	// Recover the Go impl from cgo.Handle
	g.printf("\timpl := cgo.Handle(ctx).Value().(%s)\n", ifaceName)

	// Convert C params → Go (out params return "" and are skipped)
	var goArgs []string
	for _, p := range fn.Params {
		goArg := g.emitParamCToGo(apiName, p)
		if goArg != "" {
			goArgs = append(goArgs, goArg)
		}
	}
	callArgs := strings.Join(goArgs, ", ")

	// If there are out-params, use a unified multi-return call pattern
	if hasOutParams {
		g.emitTrampolineWithOutParams(apiName, fn, methodName, callArgs, outParams)
	} else {
		g.emitTrampolineStandardCall(apiName, fn, methodName, callArgs)
	}

	g.printf("}\n\n")
}

// emitTrampolineWithOutParams handles trampolines where the Go method returns
// extra values for out-params, which must be written back to C pointers.
func (g *bridgeGoGen) emitTrampolineWithOutParams(apiName string, fn ast.Func, methodName, callArgs string, outParams []ast.Param) {
	// @rc_error: the rc is the error channel, so the provider never spells one
	// out — it returns (payload..., error) and the trampoline encodes it. This
	// is the whole point of the shape: the provider's error reaches the caller
	// instead of being flattened into a zero-valued payload.
	if fn.RcError {
		lhsParts := make([]string, 0, len(outParams)+1)
		for i := range outParams {
			lhsParts = append(lhsParts, fmt.Sprintf("_out%d", i))
		}
		lhsParts = append(lhsParts, "_err")
		g.printf("\t%s := impl.%s(%s)\n", strings.Join(lhsParts, ", "), methodName, callArgs)
		g.printf("\tif _err != nil {\n")
		g.printf("\t\treturn -1\n")
		g.printf("\t}\n")
		for i, p := range outParams {
			g.emitOutParamWriteback(apiName, p, fmt.Sprintf("_out%d", i), escapeGoKeyword(p.Name))
		}
		g.printf("\treturn 0\n")
		return
	}

	// Build the LHS of the multi-return assignment
	var lhsParts []string
	if fn.Return != nil {
		lhsParts = append(lhsParts, "_result")
	}
	for i := range outParams {
		lhsParts = append(lhsParts, fmt.Sprintf("_out%d", i))
	}
	// Only include error if C function has a return type
	if fn.Return != nil {
		lhsParts = append(lhsParts, "_err")
	}

	if len(lhsParts) == 1 {
		g.printf("\t%s := impl.%s(%s)\n", lhsParts[0], methodName, callArgs)
	} else {
		lhs := strings.Join(lhsParts, ", ")
		g.printf("\t%s := impl.%s(%s)\n", lhs, methodName, callArgs)
	}

	// Error handling (only for non-void functions)
	if fn.Return != nil {
		if fn.Return.Kind == ast.TypeSlice {
			fnSnake := toSnakeCase(fn.Name)
			resultType := fmt.Sprintf("C.%s_%s_result_t", apiName, fnSnake)
			g.printf("\tif _err != nil {\n")
			g.printf("\t\tvar zero %s\n", resultType)
			g.printf("\t\treturn zero\n")
			g.printf("\t}\n")
		} else {
			g.printf("\tif _err != nil {\n")
			g.printf("\t\treturn -1\n")
			g.printf("\t}\n")
		}
	}

	// Write back out-params to C pointers
	for i, p := range outParams {
		outVar := fmt.Sprintf("_out%d", i)
		cName := escapeGoKeyword(p.Name)
		g.emitOutParamWriteback(apiName, p, outVar, cName)
	}

	// Return the primary result (only for non-void functions)
	if fn.Return != nil {
		if fn.Return.Kind == ast.TypePrimitive && fn.Return.Name == ast.PrimI32 {
			g.printf("\treturn C.int32_t(_result)\n")
		} else if fn.Return.Kind == ast.TypePrimitive && fn.Return.Name == ast.PrimString {
			g.printf("\treturn C.CString(_result)\n")
		} else if fn.Return.Kind == ast.TypeNamed {
			converter := toLowerCamelRaw(fn.Return.Name) + "GoToC"
			g.printf("\tvar _retAllocs []unsafe.Pointer\n")
			g.printf("\treturn %s(*_result, &_retAllocs)\n", converter)
		} else {
			cType := cTypeForAPICgo(apiName, *fn.Return)
			g.printf("\treturn %s(_result)\n", cType)
		}
	}
}

// emitOutParamWriteback writes code to copy a Go return value back into a C out-pointer.
func (g *bridgeGoGen) emitOutParamWriteback(apiName string, p ast.Param, goVar, cName string) {
	switch p.Type.Kind {
	case ast.TypePrimitive:
		switch p.Type.Name {
		case ast.PrimString:
			// string out: char **buf → *buf = C.CString(val)
			g.printf("\tif %s != nil {\n", cName)
			g.printf("\t\t*%s = C.CString(%s)\n", cName, goVar)
			g.printf("\t}\n")
		case ast.PrimI32:
			g.printf("\tif %s != nil {\n", cName)
			g.printf("\t\t*%s = C.int32_t(%s)\n", cName, goVar)
			g.printf("\t}\n")
		case ast.PrimU32:
			g.printf("\tif %s != nil {\n", cName)
			g.printf("\t\t*%s = C.uint32_t(%s)\n", cName, goVar)
			g.printf("\t}\n")
		case ast.PrimI64:
			g.printf("\tif %s != nil {\n", cName)
			g.printf("\t\t*%s = C.int64_t(%s)\n", cName, goVar)
			g.printf("\t}\n")
		case ast.PrimU64:
			g.printf("\tif %s != nil {\n", cName)
			g.printf("\t\t*%s = C.uint64_t(%s)\n", cName, goVar)
			g.printf("\t}\n")
		case ast.PrimF32:
			g.printf("\tif %s != nil {\n", cName)
			g.printf("\t\t*%s = C.float(%s)\n", cName, goVar)
			g.printf("\t}\n")
		case ast.PrimF64:
			g.printf("\tif %s != nil {\n", cName)
			g.printf("\t\t*%s = C.double(%s)\n", cName, goVar)
			g.printf("\t}\n")
		default:
			cType := cTypeForAPICgo(apiName, p.Type)
			g.printf("\tif %s != nil {\n", cName)
			g.printf("\t\t*%s = %s(%s)\n", cName, cType, goVar)
			g.printf("\t}\n")
		}
	case ast.TypeArray:
		// Fixed array out: write elements back to C pointer
		n := p.Type.ArrayLen
		g.printf("\t{\n")
		g.printf("\t\t_arr := unsafe.Slice(%s, %d)\n", cName, n)
		elemCType := cTypeForAPICgo(apiName, *p.Type.Elem)
		g.printf("\t\tfor i := range _arr {\n")
		g.printf("\t\t\t_arr[i] = %s(%s[i])\n", elemCType, goVar)
		g.printf("\t\t}\n")
		g.printf("\t}\n")
	case ast.TypeNamed:
		// Struct out: use GoToC converter and write back
		converter := toLowerCamelRaw(p.Type.Name) + "GoToC"
		g.printf("\t{\n")
		g.printf("\t\tvar _freeList []unsafe.Pointer\n")
		g.printf("\t\t*%s = %s(%s, &_freeList)\n", cName, converter, goVar)
		g.printf("\t}\n")
	case ast.TypeSlice:
		g.emitSliceOutWriteback(apiName, p, goVar, cName)
	}
}

// emitSliceOutWriteback fills a slice out param's {data, len} struct from a Go
// slice. The buffer (and every string in it) is malloc'd and handed to the
// caller, which frees it — the same ownership rule as a slice return, so the
// consuming client code is unchanged by the conversion.
func (g *bridgeGoGen) emitSliceOutWriteback(apiName string, p ast.Param, goVar, cName string) {
	elem := *p.Type.Elem
	g.printf("\tif %s != nil {\n", cName)
	g.printf("\t\t%s.len = C.size_t(len(%s))\n", cName, goVar)
	g.printf("\t\t%s.data = nil\n", cName)
	g.printf("\t\tif len(%s) > 0 {\n", goVar)

	switch {
	case elem.Kind == ast.TypePrimitive && elem.Name == ast.PrimString:
		g.printf("\t\t\t_arr := (**C.char)(C.calloc(C.size_t(len(%s)), C.size_t(unsafe.Sizeof((*C.char)(nil)))))\n", goVar)
		g.printf("\t\t\t_slice := unsafe.Slice(_arr, len(%s))\n", goVar)
		g.printf("\t\t\tfor i := range %s {\n", goVar)
		g.printf("\t\t\t\t_slice[i] = C.CString(%s[i])\n", goVar)
		g.printf("\t\t\t}\n")
		g.printf("\t\t\t%s.data = _arr\n", cName)
	case elem.Kind == ast.TypeNamed && !g.isEnum(elem.Name):
		elemCType := cTypeForAPICgo(apiName, elem)
		converter := toLowerCamelRaw(elem.Name) + "GoToC"
		g.printf("\t\t\t_arr := (*%s)(C.calloc(C.size_t(len(%s)), C.size_t(unsafe.Sizeof(%s{}))))\n", elemCType, goVar, elemCType)
		g.printf("\t\t\t_slice := unsafe.Slice(_arr, len(%s))\n", goVar)
		g.printf("\t\t\tvar _retAllocs []unsafe.Pointer // not freed: caller owns return data\n")
		g.printf("\t\t\tfor i := range %s {\n", goVar)
		g.printf("\t\t\t\t_slice[i] = %s(%s[i], &_retAllocs)\n", converter, goVar)
		g.printf("\t\t\t}\n")
		g.printf("\t\t\t%s.data = _arr\n", cName)
	default:
		elemCType := cTypeForAPICgo(apiName, elem)
		g.printf("\t\t\t_arr := (*%s)(C.calloc(C.size_t(len(%s)), C.size_t(unsafe.Sizeof(%s(0)))))\n", elemCType, goVar, elemCType)
		g.printf("\t\t\t_slice := unsafe.Slice(_arr, len(%s))\n", goVar)
		g.printf("\t\t\tfor i := range %s {\n", goVar)
		g.printf("\t\t\t\t_slice[i] = %s(%s[i])\n", elemCType, goVar)
		g.printf("\t\t\t}\n")
		g.printf("\t\t\t%s.data = _arr\n", cName)
	}

	g.printf("\t\t}\n")
	g.printf("\t}\n")
}

// emitTrampolineStandardCall handles the original trampoline pattern (no out-params).
func (g *bridgeGoGen) emitTrampolineStandardCall(apiName string, fn ast.Func, methodName, callArgs string) {
	// Call the Go method
	if fn.Return == nil {
		// Void function — just call, no return
		g.printf("\timpl.%s(%s)\n", methodName, callArgs)
	} else if fn.Return.Kind == ast.TypeSlice {
		// Slice return — allocate C array, convert elements, return _result_t
		fnSnake := toSnakeCase(fn.Name)
		resultType := fmt.Sprintf("C.%s_%s_result_t", apiName, fnSnake)
		elemCType := cTypeForAPICgo(apiName, *fn.Return.Elem)
		isStringSlice := fn.Return.Elem.Kind == ast.TypePrimitive && fn.Return.Elem.Name == ast.PrimString
		g.printf("\tresult, err := impl.%s(%s)\n", methodName, callArgs)
		g.printf("\tif err != nil {\n")
		g.printf("\t\tvar zero %s\n", resultType)
		g.printf("\t\treturn zero\n")
		g.printf("\t}\n")
		g.printf("\tn := len(result)\n")
		g.printf("\tif n == 0 {\n")
		g.printf("\t\treturn %s{}\n", resultType)
		g.printf("\t}\n")
		if isStringSlice {
			g.printf("\tcArr := (**C.char)(C.calloc(C.size_t(n), C.size_t(unsafe.Sizeof((*C.char)(nil)))))\n")
		} else {
			g.printf("\tcArr := (*%s)(C.calloc(C.size_t(n), C.size_t(unsafe.Sizeof(%s{}))))\n", elemCType, elemCType)
		}
		g.printf("\tcSlice := unsafe.Slice(cArr, n)\n")
		if fn.Return.Elem.Kind == ast.TypePrimitive && fn.Return.Elem.Name == ast.PrimString {
			g.printf("\tfor i := range result {\n")
			g.printf("\t\tcSlice[i] = C.CString(result[i])\n")
			g.printf("\t}\n")
		} else if fn.Return.Elem.Kind == ast.TypeNamed && !g.isEnum(fn.Return.Elem.Name) {
			converter := toLowerCamelRaw(fn.Return.Elem.Name) + "GoToC"
			g.printf("\tvar _retFreeList []unsafe.Pointer // not freed: caller owns return data\n")
			g.printf("\tfor i := range result {\n")
			g.printf("\t\tcSlice[i] = %s(result[i], &_retFreeList)\n", converter)
			g.printf("\t}\n")
		} else {
			g.printf("\tfor i := range result {\n")
			g.printf("\t\tcSlice[i] = %s(result[i])\n", elemCType)
			g.printf("\t}\n")
		}
		g.printf("\tvar out %s\n", resultType)
		g.printf("\tout.data = cArr\n")
		g.printf("\tout.len = C.size_t(n)\n")
		g.printf("\treturn out\n")
	} else if fn.Return.Kind == ast.TypePrimitive && fn.Return.Name == ast.PrimI32 {
		g.printf("\tresult, err := impl.%s(%s)\n", methodName, callArgs)
		g.printf("\tif err != nil {\n")
		g.printf("\t\treturn -1\n")
		g.printf("\t}\n")
		g.printf("\treturn C.int32_t(result)\n")
	} else if fn.Return.Kind == ast.TypeNamed {
		converter := toLowerCamelRaw(fn.Return.Name) + "GoToC"
		g.printf("\tvar _retAllocs []unsafe.Pointer // caller owns returned data\n")
		g.printf("\tresult, err := impl.%s(%s)\n", methodName, callArgs)
		g.printf("\tif err != nil {\n")
		g.printf("\t\tvar zero %s\n", cTypeForAPICgo(apiName, *fn.Return))
		g.printf("\t\treturn zero\n")
		g.printf("\t}\n")
		g.printf("\treturn %s(*result, &_retAllocs)\n", converter)
	} else if fn.Return.Kind == ast.TypePrimitive && fn.Return.Name == ast.PrimString {
		g.printf("\tresult, err := impl.%s(%s)\n", methodName, callArgs)
		g.printf("\tif err != nil {\n")
		g.printf("\t\treturn nil\n")
		g.printf("\t}\n")
		g.printf("\treturn C.CString(result)\n")
	} else {
		cType := cTypeForAPICgo(apiName, *fn.Return)
		g.printf("\tresult, err := impl.%s(%s)\n", methodName, callArgs)
		g.printf("\tif err != nil {\n")
		g.printf("\t\tvar zero %s\n", cType)
		g.printf("\t\treturn zero\n")
		g.printf("\t}\n")
		g.printf("\treturn %s(result)\n", cType)
	}
}

// trampolineParam returns the Go parameter declaration for a trampoline (C types).
// isOpaquePtrParam reports whether a param crosses the cgo bridge boundary as an
// opaque pointer: the `ptr` keyword modifier (IsPtr), a `ptr`-typed param, or a
// callback-typed param. All three are emitted as unsafe.Pointer in the //export
// trampoline and void* in the extern, and surfaced to the Go provider as uint64 —
// never truncated to C.int, which would drop the high 32 bits of a 64-bit
// pointer / function pointer on any 64-bit target.
func isOpaquePtrParam(p ast.Param) bool {
	return p.IsPtr ||
		p.Type.Kind == ast.TypeCallback ||
		(p.Type.Kind == ast.TypePrimitive && p.Type.Name == ast.PrimPtr)
}

func (g *bridgeGoGen) trampolineParam(apiName string, p ast.Param) string {
	name := escapeGoKeyword(p.Name)

	if isOpaquePtrParam(p) {
		// opaque pointer — pass through as unsafe.Pointer
		return fmt.Sprintf("%s unsafe.Pointer", name)
	}

	switch p.Type.Kind {
	case ast.TypePrimitive:
		cType := cTypeForAPICgo(apiName, p.Type)
		if p.ByRef || p.IsOut {
			return fmt.Sprintf("%s *%s", name, cType)
		}
		if p.Type.Nullable && p.Type.Name != ast.PrimString {
			// Nullable scalar arrives as a pointer (NULL = absent). Strings are
			// already *C.char (nullability via NULL), so are not double-pointered.
			return fmt.Sprintf("%s *%s", name, cType)
		}
		return fmt.Sprintf("%s %s", name, cType)
	case ast.TypeNamed:
		cType := cTypeForAPICgo(apiName, p.Type)
		if g.isEnum(p.Type.Name) {
			// Enums pass by value
			if p.ByRef || p.IsOut {
				return fmt.Sprintf("%s *%s", name, cType)
			}
			return fmt.Sprintf("%s %s", name, cType)
		}
		// Structs pass by pointer (matches _api.h: const T *param)
		return fmt.Sprintf("%s *%s", name, cType)
	case ast.TypeSlice:
		if p.IsOut {
			// Callee-allocated payload: an owning {data, len} struct.
			return fmt.Sprintf("%s *C.%s", name, sliceOutCTypeName(apiName, p.Type))
		}
		elemCType := cTypeForAPICgo(apiName, *p.Type.Elem)
		return fmt.Sprintf("%s *%s", name, elemCType)
	case ast.TypeArray:
		// Fixed arrays: in C they decay to pointers. Always passed as pointer.
		elemCType := cTypeForAPICgo(apiName, *p.Type.Elem)
		return fmt.Sprintf("%s *%s", name, elemCType)
	}
	return fmt.Sprintf("%s C.int", name)
}

// emitNullableScalarCToGo converts a nullable scalar param that arrives as a C
// pointer (name, e.g. a `*C.int32_t`) into a nil-preserving Go `*goType`, so the
// provider sees "absent" (nil) rather than a fabricated zero. goType is the Go
// primitive name, e.g. "int32". Returns the Go variable to pass to the impl.
func (g *bridgeGoGen) emitNullableScalarCToGo(goVar, goType, name string) string {
	g.printf("\tvar %s *%s\n", goVar, goType)
	g.printf("\tif %s != nil { _v := %s(*%s); %s = &_v }\n", name, goType, name, goVar)
	return goVar
}

// emitParamCToGo emits conversion code for a single parameter from C to Go
// and returns the Go variable name to pass to the method call.
func (g *bridgeGoGen) emitParamCToGo(apiName string, p ast.Param) string {
	name := escapeGoKeyword(p.Name)
	goVar := "go" + toPascalCase(name)

	// Out params: no input conversion needed — they're written back after the call.
	if p.IsOut {
		return ""
	}

	if isOpaquePtrParam(p) {
		// opaque ptr: pass as uint64 (same as client_cgo convention)
		g.printf("\t%s := uint64(uintptr(%s))\n", goVar, name)
		return goVar
	}

	switch p.Type.Kind {
	case ast.TypePrimitive:
		switch p.Type.Name {
		case ast.PrimString:
			if p.Type.Nullable {
				// A C caller signals "not supplied" with NULL; keep that as nil
				// rather than handing the Go provider an empty string it cannot
				// tell apart from a supplied one.
				g.printf("\tvar %s *string\n", goVar)
				g.printf("\tif %s != nil { _v := C.GoString(%s); %s = &_v }\n", name, name, goVar)
				return goVar
			}
			g.printf("\t%s := C.GoString(%s)\n", goVar, name)
			return goVar
		case ast.PrimBool:
			if p.Type.Nullable {
				return g.emitNullableScalarCToGo(goVar, "bool", name)
			}
			g.printf("\t%s := bool(%s)\n", goVar, name)
			return goVar
		case ast.PrimI32:
			if p.Type.Nullable {
				return g.emitNullableScalarCToGo(goVar, "int32", name)
			}
			g.printf("\t%s := int32(%s)\n", goVar, name)
			return goVar
		case ast.PrimU32:
			if p.Type.Nullable {
				return g.emitNullableScalarCToGo(goVar, "uint32", name)
			}
			g.printf("\t%s := uint32(%s)\n", goVar, name)
			return goVar
		case ast.PrimI64:
			if p.Type.Nullable {
				return g.emitNullableScalarCToGo(goVar, "int64", name)
			}
			g.printf("\t%s := int64(%s)\n", goVar, name)
			return goVar
		case ast.PrimU64:
			if p.Type.Nullable {
				return g.emitNullableScalarCToGo(goVar, "uint64", name)
			}
			g.printf("\t%s := uint64(%s)\n", goVar, name)
			return goVar
		case ast.PrimF32:
			if p.Type.Nullable {
				return g.emitNullableScalarCToGo(goVar, "float32", name)
			}
			g.printf("\t%s := float32(%s)\n", goVar, name)
			return goVar
		case ast.PrimF64:
			if p.Type.Nullable {
				return g.emitNullableScalarCToGo(goVar, "float64", name)
			}
			g.printf("\t%s := float64(%s)\n", goVar, name)
			return goVar
		case ast.PrimI8:
			if p.Type.Nullable {
				return g.emitNullableScalarCToGo(goVar, "int8", name)
			}
			g.printf("\t%s := int8(%s)\n", goVar, name)
			return goVar
		case ast.PrimU8:
			if p.Type.Nullable {
				return g.emitNullableScalarCToGo(goVar, "uint8", name)
			}
			g.printf("\t%s := uint8(%s)\n", goVar, name)
			return goVar
		case ast.PrimI16:
			if p.Type.Nullable {
				return g.emitNullableScalarCToGo(goVar, "int16", name)
			}
			g.printf("\t%s := int16(%s)\n", goVar, name)
			return goVar
		case ast.PrimU16:
			if p.Type.Nullable {
				return g.emitNullableScalarCToGo(goVar, "uint16", name)
			}
			g.printf("\t%s := uint16(%s)\n", goVar, name)
			return goVar
		}
	case ast.TypeNamed:
		if g.isEnum(p.Type.Name) {
			goType := toPascalCase(p.Type.Name)
			g.printf("\t%s := %s(%s)\n", goVar, goType, name)
			return goVar
		}
		// Struct: use CToGo converter (defined in _cgo.go)
		// Note: struct params are always pointers in the trampoline signature.
		converter := toLowerCamelRaw(p.Type.Name) + "CToGo"
		if p.ByRef {
			g.printf("\t%s := %s(%s)\n", goVar, converter, name)
			return "&" + goVar
		}
		g.printf("\t%s := %s(%s)\n", goVar, converter, name)
		return goVar
	case ast.TypeSlice:
		// Slice params come with a _len companion
		lenVar := name + "_len"
		if p.Type.Elem.Kind == ast.TypePrimitive && p.Type.Elem.Name == ast.PrimString {
			// String slice: **C.char → []string via C.GoString
			g.printf("\t%sRaw := unsafe.Slice(%s, int(%s))\n", goVar, name, lenVar)
			g.printf("\t%s := make([]string, len(%sRaw))\n", goVar, goVar)
			g.printf("\tfor i := range %sRaw {\n", goVar)
			g.printf("\t\t%s[i] = C.GoString(%sRaw[i])\n", goVar, goVar)
			g.printf("\t}\n")
		} else {
			g.printf("\t%s := unsafe.Slice((*%s)(unsafe.Pointer(%s)), int(%s))\n",
				goVar+"Raw", cTypeForAPICgo(apiName, *p.Type.Elem), name, lenVar)
			// Convert element by element if needed
			if p.Type.Elem.Kind == ast.TypeNamed && !g.isEnum(p.Type.Elem.Name) {
				goElemType := toPascalCase(p.Type.Elem.Name)
				converter := toLowerCamelRaw(p.Type.Elem.Name) + "CToGo"
				g.printf("\t%s := make([]%s, len(%s))\n", goVar, goElemType, goVar+"Raw")
				g.printf("\tfor i := range %s {\n", goVar+"Raw")
				g.printf("\t\t%s[i] = %s(&%s[i])\n", goVar, converter, goVar+"Raw")
				g.printf("\t}\n")
			} else {
				// Primitive slice — direct cast
				goElemType := primitiveToGoType(p.Type.Elem.Name)
				g.printf("\t%s := make([]%s, len(%s))\n", goVar, goElemType, goVar+"Raw")
				g.printf("\tfor i := range %s {\n", goVar+"Raw")
				g.printf("\t\t%s[i] = %s(%s[i])\n", goVar, goElemType, goVar+"Raw")
				g.printf("\t}\n")
			}
		}
		return goVar
	case ast.TypeArray:
		// Fixed-size array: pointer in C → Go fixed array
		n := p.Type.ArrayLen
		goElemType := primitiveToGoType(p.Type.Elem.Name)
		if p.Type.Elem.Kind == ast.TypeNamed {
			goElemType = toPascalCase(p.Type.Elem.Name)
		}
		if p.ByRef {
			// in/out: read current value, pass as pointer to Go
			g.printf("\tvar %s [%d]%s\n", goVar, n, goElemType)
			g.printf("\t{\n")
			g.printf("\t\t_arr := unsafe.Slice(%s, %d)\n", name, n)
			g.printf("\t\tfor i := range _arr {\n")
			g.printf("\t\t\t%s[i] = %s(_arr[i])\n", goVar, goElemType)
			g.printf("\t\t}\n")
			g.printf("\t}\n")
			return "&" + goVar
		}
		// by-value: convert C array to Go array
		g.printf("\tvar %s [%d]%s\n", goVar, n, goElemType)
		g.printf("\t{\n")
		g.printf("\t\t_arr := unsafe.Slice(%s, %d)\n", name, n)
		g.printf("\t\tfor i := range _arr {\n")
		g.printf("\t\t\t%s[i] = %s(_arr[i])\n", goVar, goElemType)
		g.printf("\t\t}\n")
		g.printf("\t}\n")
		return goVar
	}
	return name
}

// --- Helpers ---

func (g *bridgeGoGen) goMethodParams(fn ast.Func) string {
	parts := make([]string, 0, len(fn.Params))
	for _, p := range fn.Params {
		if p.IsOut {
			continue // out params are returned, not in signature
		}
		paramName := toLowerCamel(p.Name)
		var paramType string
		if isOpaquePtrParam(p) {
			paramType = "uint64"
		} else if p.ByRef && p.Type.Kind == ast.TypeNamed && !g.isEnum(p.Type.Name) {
			paramType = "*" + toPascalCase(p.Type.Name)
		} else if p.ByRef && p.Type.Kind == ast.TypeArray {
			paramType = "*" + goTypeForDispatch(p.Type)
		} else if p.ByRef && p.Type.Kind == ast.TypePrimitive && p.Type.Name == ast.PrimString {
			paramType = "*string"
		} else {
			paramType = goTypeForDispatch(p.Type)
		}
		parts = append(parts, paramName+" "+paramType)
	}
	return strings.Join(parts, ", ")
}

func (g *bridgeGoGen) goMethodReturn(fn ast.Func) string {
	// Collect return types: declared return + out-params + optional error.
	// Error is only included if the C function returns a value (non-void).
	var rets []string
	// @rc_error: the rc is generated from the error, so it is not part of the
	// provider's signature — the implementation returns (payload..., error) and
	// looks exactly like the value-returning method it replaced.
	if fn.Return != nil && !fn.RcError {
		retType := goTypeForDispatch(*fn.Return)
		if fn.Return.Kind == ast.TypeNamed {
			rets = append(rets, "*"+retType)
		} else {
			rets = append(rets, retType)
		}
	}
	for _, p := range fn.Params {
		if p.IsOut {
			rets = append(rets, goTypeForDispatch(p.Type))
		}
	}
	// Only add error if the C function has a return type (non-void).
	// Void functions cannot signal errors through the C ABI.
	if fn.Return != nil {
		rets = append(rets, "error")
	}
	if len(rets) == 0 {
		return "" // void, no out-params
	}
	if len(rets) == 1 {
		return rets[0]
	}
	return "(" + strings.Join(rets, ", ") + ")"
}

func (g *bridgeGoGen) isEnum(name string) bool {
	for _, e := range g.api.Enums {
		if e.Name == name {
			return true
		}
	}
	return false
}

func (g *bridgeGoGen) hasWatchFuncs() bool {
	for _, fn := range g.api.Funcs {
		if fn.Watch {
			return true
		}
	}
	return false
}

// emitExternDecl writes an extern C declaration for a trampoline function.
func (g *bridgeGoGen) emitExternDecl(apiName string, fn ast.Func) {
	fnSnake := toSnakeCase(fn.Name)
	exportName := fmt.Sprintf("%s_bridge_%s", apiName, fnSnake)

	// Return type — void if no return declared, else the declared C type
	retType := "void"
	if fn.Return != nil {
		if fn.Return.Kind == ast.TypeSlice {
			retType = fmt.Sprintf("%s_%s_result_t", apiName, fnSnake)
		} else {
			retType = g.cReturnType(apiName, *fn.Return)
		}
	}

	// Parameters: always starts with the ctx handle (uintptr_t, see preamble)
	params := []string{"uintptr_t ctx"}
	for _, p := range fn.Params {
		params = append(params, g.cParamDecl(apiName, p))
		// A slice out param carries its length in the owning result struct, so
		// it takes no _len companion (see sliceOutCTypeName).
		if p.Type.Kind == ast.TypeSlice && !p.IsOut {
			params = append(params, "size_t "+p.Name+"_len")
		}
	}

	g.printf("extern %s %s(%s);\n", retType, exportName, strings.Join(params, ", "))
}

// cReturnType returns the C type string for a function return type.
// Uses cgo-compatible types (no const qualifiers) since these are for extern declarations.
func (g *bridgeGoGen) cReturnType(apiName string, t ast.TypeRef) string {
	switch t.Kind {
	case ast.TypePrimitive:
		if t.Name == ast.PrimString {
			return "char *"
		}
		return primitiveToCType(t.Name)
	case ast.TypeNamed:
		return fmt.Sprintf("%s_%s_t", apiName, toSnakeCase(t.Name))
	case ast.TypeSlice:
		return fmt.Sprintf("%s_%s_t", apiName, toSnakeCase(t.Elem.Name))
	}
	return "int32_t"
}

// cParamDecl returns a C parameter declaration string.
func (g *bridgeGoGen) cParamDecl(apiName string, p ast.Param) string {
	name := p.Name
	if isOpaquePtrParam(p) {
		return "void *" + name
	}

	switch p.Type.Kind {
	case ast.TypePrimitive:
		cType := primitiveToCType(p.Type.Name)
		if p.Type.Name == ast.PrimString {
			if p.ByRef || p.IsOut {
				return "char **" + name
			}
			return "char *" + name
		}
		if p.ByRef || p.IsOut {
			return cType + " *" + name
		}
		if p.Type.Nullable && p.Type.Name != ast.PrimString {
			// Nullable scalar → pointer. Non-const to match the cgo //export
			// signature (the callbacks builder casts to the const typedef).
			// Strings are excluded (handled as char* above).
			return cType + " *" + name
		}
		return cType + " " + name
	case ast.TypeNamed:
		cType := fmt.Sprintf("%s_%s_t", apiName, toSnakeCase(p.Type.Name))
		if g.isEnum(p.Type.Name) {
			// Enums pass by value
			if p.ByRef || p.IsOut {
				return cType + " *" + name
			}
			return cType + " " + name
		}
		// Structs always pass by pointer (matches _api.h convention)
		return cType + " *" + name
	case ast.TypeSlice:
		if p.IsOut {
			return sliceOutCTypeName(apiName, p.Type) + " *" + name
		}
		elemCType := fmt.Sprintf("%s_%s_t", apiName, toSnakeCase(p.Type.Elem.Name))
		if p.Type.Elem.Kind == ast.TypePrimitive {
			ct := primitiveToCType(p.Type.Elem.Name)
			if p.Type.Elem.Name == ast.PrimString {
				// cgo exports string slices as char ** (no const)
				return "char **" + name
			}
			elemCType = ct
		}
		return elemCType + " *" + name
	case ast.TypeArray:
		// Fixed arrays: C declaration uses array syntax or pointer
		elemCType := primitiveToCType(p.Type.Elem.Name)
		if p.Type.Elem.Kind == ast.TypeNamed {
			elemCType = fmt.Sprintf("%s_%s_t", apiName, toSnakeCase(p.Type.Elem.Name))
		}
		return elemCType + " " + name + fmt.Sprintf("[%s]", cArraySizeStr(apiName, p.Type))
	}
	return "int " + name
}
