// Copyright (C) 2026 Sascha Ittner <sascha.ittner@modusoft.de>
// License: GPL Version 2
package cgen

import (
	"fmt"
	"io"

	"github.com/sittner/linuxcnc/src/gomc/internal/gmicompile/ast"
)

// GenerateClientPythonWS writes a Python WebSocket watch client module.
// Uses the `websockets` library (asyncio) for the connection, with a
// threaded wrapper for use from synchronous code (e.g. Tkinter mainloop).
func GenerateClientPythonWS(w io.Writer, api *ast.API) error {
	if err := checkPyWSNested64Bit(api); err != nil {
		return err
	}
	g := &clientPyWSGen{w: w, api: api}
	return g.generate()
}

// checkPyWSNested64Bit fails loud when a 64-bit field is reachable only through
// a collection (slice/array/map) of named types. Unlike the REST client (see
// checkPyNested64Bit), this client's from_dict DOES recurse into a direct
// named-type field, so that shape converts fine — but collection elements stay
// raw dicts, so a 64-bit value inside them would remain an unconverted wire
// string. Rather than emit a silently-wrong client, reject it — the Go and TS
// clients handle the shape, so this is a Python-target limitation.
func checkPyWSNested64Bit(api *ast.API) error {
	set := tsReviveSet(api) // types transitively containing a 64-bit field
	for i := range api.Types {
		t := &api.Types[i]
		for _, f := range t.Fields {
			collection := f.Type.Kind == ast.TypeSlice || f.Type.Kind == ast.TypeArray || f.Type.Kind == ast.TypeMap
			if collection && f.Type.Elem != nil && f.Type.Elem.Kind == ast.TypeNamed && set[f.Type.Elem.Name] {
				return fmt.Errorf("python-ws client: type %s.%s references %s inside a collection; %s contains a 64-bit int, which the Python WS client cannot convert there (from_dict does not recurse into collection elements)", t.Name, f.Name, f.Type.Elem.Name, f.Type.Elem.Name)
			}
		}
	}
	return nil
}

type clientPyWSGen struct {
	w   io.Writer
	api *ast.API
	err error
}

func (g *clientPyWSGen) printf(format string, args ...interface{}) {
	if g.err != nil {
		return
	}
	_, g.err = fmt.Fprintf(g.w, format, args...)
}

// hasStructDelta reports whether any watch needs the delta-merge helper.
// See structDelta (client_ts_ws.go) for why only struct returns get it.
func (g *clientPyWSGen) hasStructDelta() bool {
	for _, fn := range g.api.Funcs {
		if structDelta(fn) {
			return true
		}
	}
	return false
}

func (g *clientPyWSGen) generate() error {
	g.emitHeader()
	g.emit64BitHelpers()
	g.emitConstants()
	g.emitEnums()
	g.emitTypes()
	g.emitClient()
	g.emitCommands()
	g.emitThreadedWrapper()
	return g.err
}

func (g *clientPyWSGen) emitHeader() {
	g.printf("# Code generated by gmicompile --client-python-ws - DO NOT EDIT.\n")
	EmitMeta(g.w, g.api, "#")
	g.printf("#\n")
	g.printf("# WebSocket watch client for %s API v%d\n\n", g.api.Name, g.api.Version)
	g.printf("from __future__ import annotations\n\n")
	g.printf("import asyncio\n")
	g.printf("import json\n")
	g.printf("import threading\n")
	g.printf("from dataclasses import dataclass, field\n")
	g.printf("from enum import IntEnum\n")
	g.printf("from typing import Any, Callable, Optional\n\n")
	g.printf("import websockets\n\n\n")
}

// emit64BitHelpers mirrors clientPyGen.emit64BitHelpers: 64-bit ints cross the
// wire as JSON strings (they exceed a JS client's 2^53 number range; see
// is64BitScalarInt and the ",string" Go struct tag), so the client converts at
// the (de)serialization seam.
func (g *clientPyWSGen) emit64BitHelpers() {
	if !apiNeeds64BitConv(g.api) {
		return
	}
	g.printf("def _gmi_to_int(v):\n")
	g.printf("    return None if v is None else int(v)\n\n\n")
	g.printf("def _gmi_from_int(v):\n")
	g.printf("    return None if v is None else str(v)\n\n\n")
}

func (g *clientPyWSGen) emitConstants() {
	if len(g.api.Consts) == 0 {
		return
	}
	g.printf("# --- Constants ---\n\n")
	for _, c := range g.api.Consts {
		g.printf("%s = %d\n", c.Name, c.Value)
	}
	g.printf("\n\n")
}

func (g *clientPyWSGen) emitEnums() {
	if len(g.api.Enums) == 0 {
		return
	}
	g.printf("# --- Enums ---\n\n")
	for _, e := range g.api.Enums {
		className := toPascalCase(e.Name)
		g.printf("class %s(IntEnum):\n", className)
		for _, v := range e.Values {
			g.printf("    %s = %d\n", v.Name, v.Value)
		}
		g.printf("\n\n")
	}
}

func (g *clientPyWSGen) emitTypes() {
	if len(g.api.Types) == 0 {
		return
	}
	g.printf("# --- Types ---\n\n")
	for _, t := range g.api.Types {
		className := toPascalCase(t.Name)
		g.printf("@dataclass\n")
		g.printf("class %s:\n", className)
		for _, f := range t.Fields {
			fieldName := f.Name
			pyType := g.toPyType(f.Type)
			g.printf("    %s: %s = %s\n", fieldName, pyType, g.pyDefault(f.Type))
		}
		g.printf("\n")

		// from_dict class method
		g.printf("    @classmethod\n")
		g.printf("    def from_dict(cls, d: dict) -> %s:\n", className)
		g.printf("        return cls(\n")
		for _, f := range t.Fields {
			fieldName := f.Name
			g.printf("            %s=%s,\n", fieldName, g.pyFromDict(f))
		}
		g.printf("        )\n\n")
	}
	g.printf("\n")
}

func (g *clientPyWSGen) emitClient() {
	className := toPascalCase(g.api.Name) + "WatchClient"

	g.printf("# --- Async WebSocket Client ---\n\n")
	g.printf("class %s:\n", className)
	g.printf("    \"\"\"WebSocket watch client for the %s API.\n\n", g.api.Name)
	g.printf("    Connects to the gomc-server watch endpoint and supports:\n")
	g.printf("    - Subscribing to watch functions (server pushes updates at a configured rate)\n")
	g.printf("    - Calling command functions (request/response over the same connection)\n")
	g.printf("    \"\"\"\n\n")
	g.printf("    def __init__(self, url: str, api: str = %q, instance: str = %q):\n", g.api.Name, g.api.Name)
	g.printf("        self.url = url\n")
	g.printf("        self.api = api\n")
	g.printf("        self.instance = instance\n")
	g.printf("        self._ws = None\n")
	g.printf("        self._callbacks: dict[str, Callable] = {}\n")
	g.printf("        self._pending: dict[int, asyncio.Future] = {}\n")
	g.printf("        self._next_id = 1\n")
	g.printf("        self._recv_task = None\n")
	if g.hasStructDelta() {
		// @watch_delta on a struct return: see _merge_delta below.
		g.printf("        self._delta_state: dict[str, dict] = {}\n")
	}
	g.printf("\n")

	if g.hasStructDelta() {
		g.printf("    def _merge_delta(self, func_name: str, data):\n")
		g.printf("        \"\"\"Merge a @watch_delta frame onto the last object seen for this watch.\n\n")
		g.printf("        The server sends the whole object on the first push of a connection and\n")
		g.printf("        only the changed top-level keys after that. A partial struct is not a\n")
		g.printf("        valid value of the declared type, so replacing instead of merging hands\n")
		g.printf("        the caller an object missing most of its fields.\n")
		g.printf("        \"\"\"\n")
		g.printf("        if not isinstance(data, dict):\n")
		g.printf("            # A non-dict frame has nothing to merge onto: drop the base and\n")
		g.printf("            # pass it through (a later dict frame starts a fresh base).\n")
		g.printf("            self._delta_state.pop(func_name, None)\n")
		g.printf("            return data\n")
		g.printf("        merged = dict(self._delta_state.get(func_name, {}))\n")
		g.printf("        merged.update(data)\n")
		g.printf("        self._delta_state[func_name] = merged\n")
		g.printf("        # The returned dict IS the stored merge base: callers must not\n")
		g.printf("        # mutate it, or later frames merge onto corrupted state.\n")
		g.printf("        return merged\n\n")
	}

	// connect
	g.printf("    async def connect(self):\n")
	g.printf("        \"\"\"Connect to the WebSocket endpoint.\"\"\"\n")
	g.printf("        self._ws = await websockets.connect(self.url)\n")
	g.printf("        self._recv_task = asyncio.create_task(self._recv_loop())\n\n")

	// close
	g.printf("    async def close(self):\n")
	g.printf("        \"\"\"Close the WebSocket connection.\"\"\"\n")
	g.printf("        if self._recv_task:\n")
	g.printf("            self._recv_task.cancel()\n")
	g.printf("        if self._ws:\n")
	g.printf("            await self._ws.close()\n\n")

	// subscribe (generic)
	g.printf("    async def subscribe(self, func_name: str, rate_ms: int, callback: Callable):\n")
	g.printf("        \"\"\"Subscribe to a watch function.\"\"\"\n")
	g.printf("        self._callbacks[func_name] = callback\n")
	g.printf("        msg = {\n")
	g.printf("            \"action\": \"subscribe\",\n")
	g.printf("            \"api\": self.api,\n")
	g.printf("            \"instance\": self.instance,\n")
	g.printf("            \"func\": func_name,\n")
	g.printf("            \"rate_ms\": rate_ms,\n")
	g.printf("        }\n")
	g.printf("        await self._ws.send(json.dumps(msg))\n\n")

	// unsubscribe
	g.printf("    async def unsubscribe(self, func_name: str):\n")
	g.printf("        \"\"\"Unsubscribe from a watch function.\"\"\"\n")
	g.printf("        self._callbacks.pop(func_name, None)\n")
	if g.hasStructDelta() {
		// Same rule as the TS WS client: a resubscribe gets a fresh full
		// frame from the server (the diff state is per-subscription), so
		// carrying the old base forward could only resurrect stale fields.
		g.printf("        self._delta_state.pop(func_name, None)\n")
	}
	g.printf("        msg = {\n")
	g.printf("            \"action\": \"unsubscribe\",\n")
	g.printf("            \"api\": self.api,\n")
	g.printf("            \"instance\": self.instance,\n")
	g.printf("            \"func\": func_name,\n")
	g.printf("        }\n")
	g.printf("        await self._ws.send(json.dumps(msg))\n\n")

	// _call (generic command invocation)
	g.printf("    async def _call(self, func_name: str, args: dict = None) -> Any:\n")
	g.printf("        \"\"\"Call a command function and wait for the result.\"\"\"\n")
	g.printf("        call_id = self._next_id\n")
	g.printf("        self._next_id += 1\n")
	g.printf("        msg = {\n")
	g.printf("            \"action\": \"call\",\n")
	g.printf("            \"api\": self.api,\n")
	g.printf("            \"instance\": self.instance,\n")
	g.printf("            \"func\": func_name,\n")
	g.printf("            \"id\": call_id,\n")
	g.printf("            \"args\": args or {},\n")
	g.printf("        }\n")
	g.printf("        loop = asyncio.get_event_loop()\n")
	g.printf("        future = loop.create_future()\n")
	g.printf("        self._pending[call_id] = future\n")
	g.printf("        await self._ws.send(json.dumps(msg))\n")
	g.printf("        return await future\n\n")

	// _recv_loop
	g.printf("    async def _recv_loop(self):\n")
	g.printf("        \"\"\"Read messages from the WebSocket and dispatch.\"\"\"\n")
	g.printf("        try:\n")
	g.printf("            async for raw in self._ws:\n")
	g.printf("                msg = json.loads(raw)\n")
	g.printf("                msg_type = msg.get(\"type\")\n\n")
	g.printf("                if msg_type == \"update\":\n")
	g.printf("                    func_name = msg.get(\"func\")\n")
	g.printf("                    cb = self._callbacks.get(func_name)\n")
	g.printf("                    if cb:\n")
	g.printf("                        cb(msg.get(\"data\"))\n\n")
	g.printf("                elif msg_type == \"result\":\n")
	g.printf("                    call_id = msg.get(\"id\")\n")
	g.printf("                    future = self._pending.pop(call_id, None)\n")
	g.printf("                    if future and not future.done():\n")
	g.printf("                        if msg.get(\"error\"):\n")
	g.printf("                            future.set_exception(RuntimeError(msg[\"error\"]))\n")
	g.printf("                        else:\n")
	g.printf("                            future.set_result(msg.get(\"data\"))\n\n")
	g.printf("                elif msg_type == \"error\":\n")
	g.printf("                    pass  # protocol error — could log\n\n")
	g.printf("        except asyncio.CancelledError:\n")
	g.printf("            pass\n")
	g.printf("        except websockets.ConnectionClosed:\n")
	g.printf("            pass\n\n")

	// Typed subscribe helpers for @watch functions
	for _, fn := range g.api.Funcs {
		if !fn.Watch {
			continue
		}
		methodName := toSnakeCase(fn.Name)
		g.printf("    async def subscribe_%s(self, rate_ms: int = %s, callback: Callable = None):\n",
			methodName, g.defaultRateMS(fn))
		g.printf("        \"\"\"Subscribe to %s updates.\"\"\"\n", fn.Name)

		// Wrap callback with typed deserialization if there's a return type
		if fn.Return != nil && fn.Return.Kind == ast.TypeNamed {
			typeName := toPascalCase(fn.Return.Name)
			g.printf("        def _typed_cb(data):\n")
			if structDelta(fn) {
				g.printf("            data = self._merge_delta(%q, data)\n", fn.Name)
			}
			g.printf("            if callback:\n")
			g.printf("                callback(%s.from_dict(data) if isinstance(data, dict) else data)\n", typeName)
			g.printf("        await self.subscribe(%q, rate_ms, _typed_cb)\n\n", fn.Name)
		} else if fn.Return != nil && fn.Return.Kind == ast.TypeMap &&
			fn.Return.Elem != nil && fn.Return.Elem.Kind == ast.TypeNamed {
			// map[string]NamedType — deserialize each value. Works for delta
			// frames too: a partial map is still a dict of the same shape.
			typeName := toPascalCase(fn.Return.Elem.Name)
			g.printf("        def _typed_cb(data):\n")
			g.printf("            if callback:\n")
			g.printf("                callback({k: %s.from_dict(v) if isinstance(v, dict) else v for k, v in data.items()} if isinstance(data, dict) else data)\n", typeName)
			g.printf("        await self.subscribe(%q, rate_ms, _typed_cb)\n\n", fn.Name)
		} else {
			g.printf("        await self.subscribe(%q, rate_ms, callback)\n\n", fn.Name)
		}
	}
}

func (g *clientPyWSGen) emitCommands() {
	g.printf("    # --- Command methods ---\n\n")

	for _, fn := range g.api.Funcs {
		if fn.Watch {
			continue
		}
		// See clientGoGen.emitClientMethod: the REST view is the marshaled shape.
		fn = restView(fn)
		methodName := toSnakeCase(fn.Name)
		params := g.methodParams(fn)
		retAnnot := g.methodReturnAnnotation(fn)

		g.printf("    async def %s(%s)%s:\n", methodName, params, retAnnot)
		g.printf("        \"\"\"Call %s.\"\"\"\n", fn.Name)

		if len(fn.Params) > 0 {
			g.printf("        args = {\n")
			for _, p := range fn.Params {
				g.printf("            %q: %s,\n", p.Name, g.pyArgSend(p))
			}
			g.printf("        }\n")
			g.printf("        _r = await self._call(%q, args)\n", fn.Name)
		} else {
			g.printf("        _r = await self._call(%q)\n", fn.Name)
		}
		g.printf("        return %s\n\n", g.pyRetRecv(fn))
	}
}

// pyRetRecv returns the expression converting a command result _r to its
// declared shape, mirroring the REST client: named types through from_dict,
// scalar i64/u64 from the wire string (the server's ,string tag), everything
// else raw. Collections of 64-bit ints do not exist on the wire (see
// is64BitScalarInt), so no deeper shape needs handling here.
func (g *clientPyWSGen) pyRetRecv(fn ast.Func) string {
	r := fn.Return
	switch {
	case r == nil:
		return "_r"
	case r.Kind == ast.TypeSlice && r.Elem != nil && r.Elem.Kind == ast.TypeNamed:
		return fmt.Sprintf("[%s.from_dict(item) for item in (_r or [])]", toPascalCase(r.Elem.Name))
	case r.Kind == ast.TypeNamed:
		return fmt.Sprintf("%s.from_dict(_r) if _r else None", toPascalCase(r.Name))
	case is64BitScalarInt(*r):
		return "_gmi_to_int(_r)"
	default:
		return "_r"
	}
}

func (g *clientPyWSGen) emitThreadedWrapper() {
	className := toPascalCase(g.api.Name) + "WatchClient"
	wrapperName := toPascalCase(g.api.Name) + "WatchThread"

	g.printf("\n# --- Threaded wrapper for synchronous UI (Tkinter, etc.) ---\n\n")
	g.printf("class %s:\n", wrapperName)
	g.printf("    \"\"\"Runs %s in a background thread with its own event loop.\n\n", className)
	g.printf("    Use from Tkinter or other synchronous UI frameworks:\n")
	g.printf("        thread = %s(url)\n", wrapperName)
	g.printf("        thread.subscribe_%s(callback=on_update)\n", "get_status")
	g.printf("        thread.start()\n")
	g.printf("        # Later: thread.call_%s(...)\n", "jog_start")
	g.printf("        thread.stop()\n")
	g.printf("    \"\"\"\n\n")

	g.printf("    def __init__(self, url: str, api: str = %q, instance: str = %q):\n", g.api.Name, g.api.Name)
	g.printf("        self._url = url\n")
	g.printf("        self._api = api\n")
	g.printf("        self._instance = instance\n")
	g.printf("        self._loop = None\n")
	g.printf("        self._thread = None\n")
	g.printf("        self._client = None\n")
	g.printf("        self._pending_subs: list[tuple] = []\n")
	g.printf("        self._started = threading.Event()\n\n")

	// start
	g.printf("    def start(self):\n")
	g.printf("        \"\"\"Start the background thread and connect.\"\"\"\n")
	g.printf("        self._thread = threading.Thread(target=self._run, daemon=True)\n")
	g.printf("        self._thread.start()\n")
	g.printf("        self._started.wait()\n\n")

	// stop
	g.printf("    def stop(self):\n")
	g.printf("        \"\"\"Stop the background thread.\"\"\"\n")
	g.printf("        if self._loop:\n")
	g.printf("            self._loop.call_soon_threadsafe(self._loop.stop)\n")
	g.printf("        if self._thread:\n")
	g.printf("            self._thread.join(timeout=2)\n")
	g.printf("        if self._thread and self._thread.is_alive() and self._loop:\n")
	g.printf("            # Force-close the event loop if thread didn't stop cleanly\n")
	g.printf("            self._loop.call_soon_threadsafe(self._loop.stop)\n\n")

	// _run
	g.printf("    def _run(self):\n")
	g.printf("        self._loop = asyncio.new_event_loop()\n")
	g.printf("        asyncio.set_event_loop(self._loop)\n")
	g.printf("        self._loop.run_until_complete(self._connect_and_subscribe())\n")
	g.printf("        self._started.set()\n")
	g.printf("        self._loop.run_forever()\n")
	g.printf("        try:\n")
	g.printf("            self._loop.run_until_complete(asyncio.wait_for(self._client.close(), timeout=1))\n")
	g.printf("        except Exception:\n")
	g.printf("            pass\n")
	g.printf("        self._loop.close()\n\n")

	// _connect_and_subscribe
	g.printf("    async def _connect_and_subscribe(self):\n")
	g.printf("        self._client = %s(self._url, self._api, self._instance)\n", className)
	g.printf("        await self._client.connect()\n")
	g.printf("        for func_name, rate_ms, callback in self._pending_subs:\n")
	g.printf("            await self._client.subscribe(func_name, rate_ms, callback)\n\n")

	// Typed subscribe helpers (called before start(), queues subscription)
	for _, fn := range g.api.Funcs {
		if !fn.Watch {
			continue
		}
		methodName := toSnakeCase(fn.Name)
		g.printf("    def subscribe_%s(self, rate_ms: int = %s, callback: Callable = None):\n",
			methodName, g.defaultRateMS(fn))
		g.printf("        \"\"\"Queue subscription to %s (call before start()).\"\"\"\n", fn.Name)

		if fn.Return != nil && fn.Return.Kind == ast.TypeNamed {
			typeName := toPascalCase(fn.Return.Name)
			g.printf("        def _typed_cb(data):\n")
			if structDelta(fn) {
				// The merge base lives on the wrapped async client
				// (_merge_delta/_delta_state are class members there, not
				// here). _client is assigned in _connect_and_subscribe
				// before connect(), and this callback only runs from that
				// client's _recv_loop — so _client always exists by then.
				// This is also the ONLY merge on the wrapper path: the
				// queued subscription goes through the client's generic
				// subscribe(), never its typed subscribe_* (which merges
				// for direct async users), so each frame merges once.
				g.printf("            # Merge on the wrapped client: the delta base lives there, and\n")
				g.printf("            # _client is always set before a frame can arrive.\n")
				g.printf("            data = self._client._merge_delta(%q, data)\n", fn.Name)
			}
			g.printf("            if callback:\n")
			g.printf("                callback(%s.from_dict(data) if isinstance(data, dict) else data)\n", typeName)
			g.printf("        self._pending_subs.append((%q, rate_ms, _typed_cb))\n\n", fn.Name)
		} else {
			g.printf("        self._pending_subs.append((%q, rate_ms, callback))\n\n", fn.Name)
		}
	}

	// Typed command helpers (called after start(), uses loop.call_soon_threadsafe)
	for _, fn := range g.api.Funcs {
		if fn.Watch {
			continue
		}
		methodName := toSnakeCase(fn.Name)
		params := g.threadMethodParams(fn)
		g.printf("    def %s(%s):\n", methodName, params)
		g.printf("        \"\"\"Call %s (fire-and-forget from main thread).\"\"\"\n", fn.Name)
		if len(fn.Params) > 0 {
			g.printf("        args = {\n")
			for _, p := range fn.Params {
				g.printf("            %q: %s,\n", p.Name, g.pyArgSend(p))
			}
			g.printf("        }\n")
			g.printf("        asyncio.run_coroutine_threadsafe(\n")
			g.printf("            self._client._call(%q, args), self._loop\n", fn.Name)
			g.printf("        )\n\n")
		} else {
			g.printf("        asyncio.run_coroutine_threadsafe(\n")
			g.printf("            self._client._call(%q), self._loop\n", fn.Name)
			g.printf("        )\n\n")
		}
	}
}

// --- Helpers ---

// pyArgSend returns the expression to place a command argument into the JSON
// args dict. 64-bit ints go out as JSON strings — the server's ",string"
// struct fields reject a JSON number (see _gmi_from_int / is64BitScalarInt).
func (g *clientPyWSGen) pyArgSend(p ast.Param) string {
	if is64BitScalarInt(p.Type) {
		return fmt.Sprintf("_gmi_from_int(%s)", p.Name)
	}
	return p.Name
}

func (g *clientPyWSGen) defaultRateMS(fn ast.Func) string {
	if fn.WatchDefaultRate != "" {
		return parseRateToMS(fn.WatchDefaultRate)
	}
	return "100"
}

// parseRateToMS converts "50ms" → "50", "1s" → "1000".
func parseRateToMS(s string) string {
	if len(s) > 2 && s[len(s)-2:] == "ms" {
		return s[:len(s)-2]
	}
	if len(s) > 1 && s[len(s)-1:] == "s" {
		// Simple multiply — only handles integer seconds
		return s[:len(s)-1] + "000"
	}
	return s
}

func (g *clientPyWSGen) methodParams(fn ast.Func) string {
	parts := []string{"self"}
	for _, p := range fn.Params {
		pName := p.Name
		pyType := g.toPyType(p.Type)
		parts = append(parts, fmt.Sprintf("%s: %s", pName, pyType))
	}
	return joinStrings(parts, ", ")
}

func (g *clientPyWSGen) threadMethodParams(fn ast.Func) string {
	parts := []string{"self"}
	for _, p := range fn.Params {
		pName := p.Name
		pyType := g.toPyType(p.Type)
		parts = append(parts, fmt.Sprintf("%s: %s", pName, pyType))
	}
	return joinStrings(parts, ", ")
}

func (g *clientPyWSGen) methodReturnAnnotation(fn ast.Func) string {
	if fn.Return == nil {
		return ""
	}
	return " -> Any"
}

func (g *clientPyWSGen) toPyType(t ast.TypeRef) string {
	switch t.Kind {
	case ast.TypePrimitive:
		// Delegate to the single Python primitive mapper (shared with client_py)
		// so the two never drift — this is where i16/u16 previously fell to Any.
		return primitiveToPyType(t.Name)
	case ast.TypeNamed:
		return toPascalCase(t.Name)
	case ast.TypeArray, ast.TypeSlice:
		return fmt.Sprintf("list[%s]", g.toPyType(*t.Elem))
	case ast.TypeMap:
		return fmt.Sprintf("dict[str, %s]", g.toPyType(*t.Elem))
	}
	return "Any"
}

func (g *clientPyWSGen) pyDefault(t ast.TypeRef) string {
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case "bool":
			return "False"
		case "string":
			return "''"
		default:
			return "0"
		}
	case ast.TypeNamed:
		return fmt.Sprintf("field(default_factory=%s)", toPascalCase(t.Name))
	case ast.TypeArray, ast.TypeSlice:
		return "field(default_factory=list)"
	}
	if t.Nullable {
		return "None"
	}
	return "None"
}

func (g *clientPyWSGen) pyFromDict(f ast.Field) string {
	fieldName := f.Name
	switch {
	case f.Type.Kind == ast.TypeNamed:
		typeName := toPascalCase(f.Type.Name)
		return fmt.Sprintf("%s.from_dict(d[%q]) if %q in d else %s()",
			typeName, fieldName, fieldName, typeName)
	case is64BitScalarInt(f.Type):
		// 64-bit ints arrive as JSON strings (see _gmi_to_int).
		return fmt.Sprintf("_gmi_to_int(d.get(%q, %s))", fieldName, g.pyDefault(f.Type))
	default:
		return fmt.Sprintf("d.get(%q, %s)", fieldName, g.pyDefault(f.Type))
	}
}

func joinStrings(parts []string, sep string) string {
	result := ""
	for i, p := range parts {
		if i > 0 {
			result += sep
		}
		result += p
	}
	return result
}
