// Copyright (C) 2026 Sascha Ittner <sascha.ittner@modusoft.de>
// License: GPL Version 2
package cgen

import (
	"fmt"
	"io"
	"strings"

	"github.com/sittner/linuxcnc/src/gomc/internal/gmicompile/ast"
)

// GenerateDispatchC writes a Go file with cgo that bridges C callbacks
// to the apiserver. This file:
//   - Includes the C header via cgo preamble
//   - Generates static C call wrappers for function pointers
//   - Generates Go types matching the C types
//   - Generates CToGo struct converters
//   - Generates DispatchFunc wrappers for REST
//   - Generates APIMeta with embedded dispatch
//   - Generates //export register function callable from C
func GenerateDispatchC(w io.Writer, api *ast.API, packageName, headerFile string) error {
	g := &dispatchCGen{w: w, api: api, pkg: packageName, header: headerFile}
	return g.generate()
}

type dispatchCGen struct {
	w      io.Writer
	api    *ast.API
	pkg    string
	header string // C header filename, e.g. "hal_api.h"
	err    error
	tmpSeq int // counter for unique temp variable names
	ce     *constraintEmitter
}

func (g *dispatchCGen) printf(format string, args ...interface{}) {
	if g.err != nil {
		return
	}
	_, g.err = fmt.Fprintf(g.w, format, args...)
}

func (g *dispatchCGen) generate() error {
	g.ce = newConstraintEmitter(g.api)
	g.emitCgoPreamble()
	g.emitImports()
	g.emitConstants()
	g.emitGoTypes()
	g.emitConverters()
	g.emitGoToCConverters()
	g.printf("%s", g.ce.regexVarDecls())
	// One package-level validate<Api><Fn> per function; both this REST dispatch
	// and the WS command handler (server_go.go) call them instead of inlining
	// the same checks twice (D8).
	g.printf("%s", g.ce.allValidationFuncs())
	g.emitDispatchFuncs()
	g.emitMeta()
	g.emitRegister()
	return g.err
}

// --- cgo Preamble ---

func (g *dispatchCGen) emitCgoPreamble() {
	g.printf("// Code generated by gmicompile - DO NOT EDIT.\n")
	EmitMeta(g.w, g.api, "//")
	g.printf("\n")
	g.printf("package %s\n\n", g.pkg)

	// Add cgo CFLAGS for imported APIs so their headers can be found
	if len(g.api.Imports) > 0 {
		var flags []string
		for _, imp := range g.api.Imports {
			flags = append(flags, fmt.Sprintf("-I../%s", imp.Name))
		}
		g.printf("// #cgo CFLAGS: %s\n", strings.Join(flags, " "))
	}

	g.printf("/*\n")
	g.printf("#define %s_API_CGO\n", strings.ToUpper(g.api.Name))
	// Also define CGO guards for imported APIs to skip their gomc_api.h sections
	for _, imp := range g.api.Imports {
		g.printf("#define %s_API_CGO\n", strings.ToUpper(imp.Name))
	}
	g.printf("#include \"%s\"\n", g.header)
	g.printf("#include <stdlib.h>\n")
	g.printf("#include <string.h>\n")
	g.printf("\n")

	// Static call wrappers — cgo cannot call C function pointers directly,
	// so we generate a static wrapper for each callback.
	for _, fn := range g.api.Funcs {
		if fn.Publish {
			continue // publish functions use ring buffers, not callbacks
		}
		g.emitCallWrapper(fn)
	}

	g.printf("*/\n")
	g.printf("import \"C\"\n\n")
}

func (g *dispatchCGen) emitCallWrapper(fn ast.Func) {
	apiName := g.api.Name
	fnSnake := toSnakeCase(fn.Name)
	wrapperName := fmt.Sprintf("call_%s_%s", apiName, fnSnake)

	// Determine return type: direct return or void
	retCType := "void"
	if fn.Return != nil {
		if fn.Return.Kind == ast.TypeSlice {
			retCType = fmt.Sprintf("%s_%s_result_t", apiName, fnSnake)
		} else {
			retCType = toCTypeForAPI(apiName, *fn.Return)
		}
	}

	// Build parameter list: callbacks struct + same params as callback typedef.
	// The function pointer and ctx are dereferenced INSIDE C, never passed from
	// Go: for Go providers ctx holds a cgo.Handle (a small integer, not a real
	// address), and carrying it through a Go unsafe.Pointer slot is fatal when
	// a GC stack scan hits that slot (runtime: invalid pointer found on stack).
	params := []string{fmt.Sprintf("const %s_callbacks_t *cbs", apiName)}
	args := []string{"cbs->ctx"}

	for _, p := range fn.Params {
		name := p.Name
		params = append(params, g.cgoParamDecl(apiName, p))
		args = append(args, name)
		// Slice params also pass a length arg — except a slice out param, whose
		// length comes back inside the owning result struct.
		if p.Type.Kind == ast.TypeSlice && !p.IsOut {
			args = append(args, name+"_len")
		}
	}

	g.printf("static %s %s(%s) {\n", retCType, wrapperName, strings.Join(params, ", "))
	if fn.Return != nil {
		g.printf("    return cbs->%s(%s);\n", cSafeName(fnSnake), strings.Join(args, ", "))
	} else {
		g.printf("    cbs->%s(%s);\n", cSafeName(fnSnake), strings.Join(args, ", "))
	}
	g.printf("}\n\n")
}

// cgoParamDecl returns the C parameter declaration for use in cgo preamble wrappers.
func (g *dispatchCGen) cgoParamDecl(apiName string, p ast.Param) string {
	name := p.Name

	// ptr qualifier: pass-through typed pointer, no marshaling.
	if p.IsPtr {
		switch p.Type.Kind {
		case ast.TypePrimitive:
			return fmt.Sprintf("%s *%s", primitiveToCType(p.Type.Name), name)
		default:
			cType := fmt.Sprintf("%s_%s_t", apiName, toSnakeCase(p.Type.Name))
			return fmt.Sprintf("%s *%s", cType, name)
		}
	}

	switch p.Type.Kind {
	case ast.TypePrimitive:
		cType := primitiveToCType(p.Type.Name)
		if p.ByRef || p.IsOut {
			return fmt.Sprintf("%s *%s", cType, name)
		}
		if p.Type.Nullable && p.Type.Name != ast.PrimString {
			// Nullable scalar → pointer (NULL = absent); matches the api.h typedef.
			// Strings are excluded (already char*, nullability via NULL).
			return fmt.Sprintf("const %s *%s", cType, name)
		}
		return fmt.Sprintf("%s %s", cType, name)

	case ast.TypeNamed:
		cType := fmt.Sprintf("%s_%s_t", apiName, toSnakeCase(p.Type.Name))
		if p.ByRef || p.IsOut {
			return fmt.Sprintf("%s *%s", cType, name)
		}
		if g.isEnum(p.Type.Name) {
			return fmt.Sprintf("%s %s", cType, name)
		}
		return fmt.Sprintf("const %s *%s", cType, name)

	case ast.TypeSlice:
		elemCType := toCTypeForAPI(apiName, *p.Type.Elem)
		if p.IsOut {
			// Callee-allocated payload — an owning {data, len} struct, not a
			// caller-provided buffer (see sliceOutCTypeName).
			return fmt.Sprintf("%s *%s", sliceOutCTypeName(apiName, p.Type), name)
		}
		if p.ByRef {
			return fmt.Sprintf("%s *%s, size_t %s_len", elemCType, name, name)
		}
		return fmt.Sprintf("%s *%s, size_t %s_len", constType(elemCType), name, name)

	case ast.TypeArray:
		elemCType := toCTypeForAPI(apiName, *p.Type.Elem)
		sizeStr := cArraySizeStr(apiName, p.Type)
		if p.ByRef || p.IsOut {
			return fmt.Sprintf("%s %s[%s]", elemCType, name, sizeStr)
		}
		return fmt.Sprintf("%s %s[%s]", constType(elemCType), name, sizeStr)
	}

	return fmt.Sprintf("void *%s", name)
}

// cArraySizeStr returns the C array-size expression for a fixed-array type. It
// is the single source of truth for C array bounds: it emits the #define symbol
// name (e.g. MOTSTAT_MAX_JOINTS) whenever the length came from a named const, so
// every C declaration/copy of the same array agrees — and an unresolved
// ArrayLenName can never silently emit a "[0]" bound. Go array bounds must stay
// numeric literals (a C #define is not visible to Go), so Go-emitting sites use
// t.ArrayLen directly and do not call this.
func cArraySizeStr(apiName string, t ast.TypeRef) string {
	if t.ArrayLenName != "" {
		return fmt.Sprintf("%s_%s", strings.ToUpper(apiName), t.ArrayLenName)
	}
	return fmt.Sprintf("%d", t.ArrayLen)
}

// --- Go Imports ---

func (g *dispatchCGen) emitImports() {
	g.printf("import (\n")
	g.printf("\t\"encoding/json\"\n")
	g.printf("\t\"fmt\"\n")
	g.printf("\t\"syscall\"\n")
	g.printf("\t\"unsafe\"\n")
	g.printf("\n")
	g.printf("\t\"github.com/sittner/linuxcnc/src/gomc/internal/apiserver\"\n")
	g.printf(")\n\n")

	// Suppress unused import warnings
	g.printf("var _ = json.Marshal\n")
	g.printf("var _ = fmt.Sprintf\n")
	g.printf("var _ = syscall.EINVAL\n")
	g.printf("var _ unsafe.Pointer\n\n")
}

// --- Go Constants ---

func (g *dispatchCGen) emitConstants() {
	if len(g.api.Consts) == 0 {
		return
	}
	g.printf("// --- Constants ---\n\n")
	g.printf("const (\n")
	for _, c := range g.api.Consts {
		g.printf("\t%s = %d\n", c.Name, c.Value)
	}
	g.printf(")\n\n")
}

// --- Go Types (same as server_go, needed in the cgo package) ---

func (g *dispatchCGen) emitGoTypes() {
	// Enums
	if len(g.api.Enums) > 0 {
		g.printf("// --- Enums ---\n\n")
		for _, e := range g.api.Enums {
			goName := toPascalCase(e.Name)
			g.printf("type %s int32\n\n", goName)
			g.printf("const (\n")
			for _, v := range e.Values {
				g.printf("\t%s_%s %s = %d\n", goName, v.Name, goName, v.Value)
			}
			g.printf(")\n\n")
		}
	}

	// Structs
	if len(g.api.Types) > 0 {
		g.printf("// --- Types ---\n\n")
		for _, t := range g.api.Types {
			goName := toPascalCase(t.Name)
			g.printf("type %s struct {\n", goName)
			for _, f := range t.Fields {
				fieldName := toPascalCase(f.Name)
				fieldType := goTypeForDispatch(f.Type)
				jsonTag := f.Name
				omit := ""
				if f.Type.Nullable {
					omit = ",omitempty"
				}
				g.printf("\t%s %s `json:\"%s%s%s\"`\n", fieldName, fieldType, jsonTag, omit, jsonStringOpt(f.Type))
			}
			g.printf("}\n\n")
		}
	}
}

// --- CToGo Converters ---

func (g *dispatchCGen) emitConverters() {
	if len(g.api.Types) == 0 {
		return
	}
	g.printf("// --- CToGo Converters ---\n\n")

	for _, t := range g.api.Types {
		goName := toPascalCase(t.Name)
		cType := fmt.Sprintf("C.%s_%s_t", g.api.Name, toSnakeCase(t.Name))
		funcName := toLowerCamelRaw(t.Name) + "CToGo"

		g.printf("func %s(src *%s) %s {\n", funcName, cType, goName)
		g.printf("\treturn %s{\n", goName)
		for _, f := range t.Fields {
			goField := toPascalCase(f.Name)
			cField := cgoFieldAccess(f.Name)
			g.emitFieldCToGo(goField, "src."+cField, f.Type)
		}
		g.printf("\t}\n")
		g.printf("}\n\n")
	}

}

// findType returns the API type definition for a named type, or nil.
func (g *dispatchCGen) findType(name string) *ast.Type {
	for i := range g.api.Types {
		if g.api.Types[i].Name == name {
			return &g.api.Types[i]
		}
	}
	return nil
}

// typeHasCAllocs reports whether a C value of the named type owns heap
// allocations (strings or slice buffers, possibly nested) that the caller
// must free under the "caller owns returned data" convention.
func (g *dispatchCGen) typeHasCAllocs(name string, seen map[string]bool) bool {
	if seen[name] {
		return false
	}
	seen[name] = true
	t := g.findType(name)
	if t == nil {
		return false
	}
	for _, f := range t.Fields {
		switch f.Type.Kind {
		case ast.TypeSlice:
			return true
		case ast.TypePrimitive:
			if f.Type.Name == ast.PrimString {
				return true
			}
		case ast.TypeNamed:
			if !g.isEnum(f.Type.Name) && g.typeHasCAllocs(f.Type.Name, seen) {
				return true
			}
		case ast.TypeArray:
			// Fixed arrays are inline (no buffer of their own), but a
			// named-struct element can still carry string/slice allocations.
			// This mirrors what emitFieldGoToC allocates for array elements.
			if f.Type.Elem != nil && f.Type.Elem.Kind == ast.TypeNamed &&
				!g.isEnum(f.Type.Elem.Name) && g.typeHasCAllocs(f.Type.Elem.Name, seen) {
				return true
			}
		}
	}
	return false
}

// emitFreeCAllocs emits C.free calls for every C allocation reachable from
// expr, a C struct value of type t: string fields, slice buffers, and any of
// those nested in named fields, slice elements, or fixed-array elements.
// Element allocations are freed before their containing buffer. Providers hand
// these out under the "caller owns returned data" convention (the Go bridges
// C.CString/calloc them), so the client must free them after converting to Go
// values.
func (g *dispatchCGen) emitFreeCAllocs(expr string, t *ast.Type, depth int, indent string) {
	for _, f := range t.Fields {
		fexpr := expr + "." + cgoFieldAccess(f.Name)
		switch f.Type.Kind {
		case ast.TypePrimitive:
			if f.Type.Name == ast.PrimString {
				g.printf("%sif %s != nil {\n", indent, fexpr)
				g.printf("%s\tC.free(unsafe.Pointer(%s))\n", indent, fexpr)
				g.printf("%s}\n", indent)
			}
		case ast.TypeNamed:
			if !g.isEnum(f.Type.Name) {
				if ft := g.findType(f.Type.Name); ft != nil {
					g.emitFreeCAllocs(fexpr, ft, depth, indent)
				}
			}
		case ast.TypeSlice:
			lenExpr := expr + "." + cgoFieldAccess(f.Name+"_len")
			inner := indent + "\t"
			g.printf("%sif %s != nil {\n", indent, fexpr)
			if f.Type.Elem.Kind == ast.TypePrimitive && f.Type.Elem.Name == ast.PrimString {
				sv := fmt.Sprintf("_fs%d", depth)
				g.printf("%s%s := unsafe.Slice(%s, int(%s))\n", inner, sv, fexpr, lenExpr)
				g.printf("%sfor _i%d := range %s {\n", inner, depth, sv)
				g.printf("%s\tif %s[_i%d] != nil {\n", inner, sv, depth)
				g.printf("%s\t\tC.free(unsafe.Pointer(%s[_i%d]))\n", inner, sv, depth)
				g.printf("%s\t}\n", inner)
				g.printf("%s}\n", inner)
			} else if f.Type.Elem.Kind == ast.TypeNamed && !g.isEnum(f.Type.Elem.Name) {
				if et := g.findType(f.Type.Elem.Name); et != nil && g.typeHasCAllocs(f.Type.Elem.Name, map[string]bool{}) {
					sv := fmt.Sprintf("_fs%d", depth)
					g.printf("%s%s := unsafe.Slice(%s, int(%s))\n", inner, sv, fexpr, lenExpr)
					g.printf("%sfor _i%d := range %s {\n", inner, depth, sv)
					g.emitFreeCAllocs(fmt.Sprintf("%s[_i%d]", sv, depth), et, depth+1, inner+"\t")
					g.printf("%s}\n", inner)
				}
			}
			g.printf("%sC.free(unsafe.Pointer(%s))\n", inner, fexpr)
			g.printf("%s}\n", indent)
		case ast.TypeArray:
			// Inline fixed array: no buffer to free, but named-struct elements
			// can own string/slice allocations. Free each element's; primitive
			// and enum elements allocate nothing (see emitFieldGoToC).
			if f.Type.Elem != nil && f.Type.Elem.Kind == ast.TypeNamed && !g.isEnum(f.Type.Elem.Name) {
				if et := g.findType(f.Type.Elem.Name); et != nil && g.typeHasCAllocs(f.Type.Elem.Name, map[string]bool{}) {
					g.printf("%sfor _i%d := 0; _i%d < %d; _i%d++ {\n", indent, depth, depth, f.Type.ArrayLen, depth)
					g.emitFreeCAllocs(fmt.Sprintf("%s[_i%d]", fexpr, depth), et, depth+1, indent+"\t")
					g.printf("%s}\n", indent)
				}
			}
		}
	}
}

func (g *dispatchCGen) emitFieldCToGo(goField, cExpr string, t ast.TypeRef) {
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case ast.PrimString:
			if t.Nullable {
				// NULL stays nil: collapsing it to "" here is what made
				// "absent" and "present but empty" the same value in Go.
				g.printf("\t\t%s: func() *string { if %s == nil { return nil }; v := C.GoString(%s); return &v }(),\n", goField, cExpr, cExpr)
			} else {
				g.printf("\t\t%s: C.GoString(%s),\n", goField, cExpr)
			}
		case ast.PrimBool:
			if t.Nullable {
				g.printf("\t\t%s: func() *bool { v := bool(%s); return &v }(),\n", goField, cExpr)
			} else {
				g.printf("\t\t%s: bool(%s),\n", goField, cExpr)
			}
		case ast.PrimI8:
			g.printf("\t\t%s: int8(%s),\n", goField, cExpr)
		case ast.PrimU8:
			g.printf("\t\t%s: uint8(%s),\n", goField, cExpr)
		case ast.PrimI16:
			if t.Nullable {
				g.printf("\t\t%s: func() *int16 { v := int16(%s); return &v }(),\n", goField, cExpr)
			} else {
				g.printf("\t\t%s: int16(%s),\n", goField, cExpr)
			}
		case ast.PrimU16:
			if t.Nullable {
				g.printf("\t\t%s: func() *uint16 { v := uint16(%s); return &v }(),\n", goField, cExpr)
			} else {
				g.printf("\t\t%s: uint16(%s),\n", goField, cExpr)
			}
		case ast.PrimI32:
			if t.Nullable {
				g.printf("\t\t%s: func() *int32 { v := int32(%s); return &v }(),\n", goField, cExpr)
			} else {
				g.printf("\t\t%s: int32(%s),\n", goField, cExpr)
			}
		case ast.PrimU32:
			if t.Nullable {
				g.printf("\t\t%s: func() *uint32 { v := uint32(%s); return &v }(),\n", goField, cExpr)
			} else {
				g.printf("\t\t%s: uint32(%s),\n", goField, cExpr)
			}
		case ast.PrimI64:
			if t.Nullable {
				g.printf("\t\t%s: func() *int64 { v := int64(%s); return &v }(),\n", goField, cExpr)
			} else {
				g.printf("\t\t%s: int64(%s),\n", goField, cExpr)
			}
		case ast.PrimU64:
			if t.Nullable {
				g.printf("\t\t%s: func() *uint64 { v := uint64(%s); return &v }(),\n", goField, cExpr)
			} else {
				g.printf("\t\t%s: uint64(%s),\n", goField, cExpr)
			}
		case ast.PrimF32:
			g.printf("\t\t%s: float32(%s),\n", goField, cExpr)
		case ast.PrimF64:
			g.printf("\t\t%s: float64(%s),\n", goField, cExpr)
		}
	case ast.TypeNamed:
		// Could be enum or struct — for enums, cast; for structs, recurse
		goType := toPascalCase(t.Name)
		if g.isEnum(t.Name) {
			g.printf("\t\t%s: %s(%s),\n", goField, goType, cExpr)
		} else {
			converter := toLowerCamelRaw(t.Name) + "CToGo"
			if t.Nullable {
				g.printf("\t\t%s: func() *%s { v := %s(&%s); return &v }(),\n", goField, goType, converter, cExpr)
			} else {
				g.printf("\t\t%s: %s(&%s),\n", goField, converter, cExpr)
			}
		}
	case ast.TypeSlice:
		// Slice fields in C structs: pointer 'field' + companion 'field_len'.
		// Convert to Go slice, freeing the C array after copy.
		lenExpr := cExpr + "_len"
		if t.Elem != nil {
			switch t.Elem.Kind {
			case ast.TypePrimitive:
				if t.Elem.Name == ast.PrimString {
					// []string: char** + len → []string
					g.printf("\t\t%s: func() []string {\n", goField)
					g.printf("\t\t\tn := int(%s)\n", lenExpr)
					g.printf("\t\t\tif n == 0 || %s == nil { return nil }\n", cExpr)
					g.printf("\t\t\tcSlice := unsafe.Slice(%s, n)\n", cExpr)
					g.printf("\t\t\tresult := make([]string, n)\n")
					g.printf("\t\t\tfor i := 0; i < n; i++ { result[i] = C.GoString(cSlice[i]) }\n")
					g.printf("\t\t\treturn result\n")
					g.printf("\t\t}(),\n")
				} else if t.Elem.Name == ast.PrimU8 {
					// []u8: uint8_t* + len → []byte (binary data)
					g.printf("\t\t%s: func() []byte {\n", goField)
					g.printf("\t\t\tn := int(%s)\n", lenExpr)
					g.printf("\t\t\tif n == 0 || %s == nil { return nil }\n", cExpr)
					g.printf("\t\t\tresult := C.GoBytes(unsafe.Pointer(%s), C.int(n))\n", cExpr)
					g.printf("\t\t\treturn result\n")
					g.printf("\t\t}(),\n")
				} else {
					// Other primitive slices: cast pointer, copy elements
					goElem := goTypeForDispatch(*t.Elem)
					g.printf("\t\t%s: func() []%s {\n", goField, goElem)
					g.printf("\t\t\tn := int(%s)\n", lenExpr)
					g.printf("\t\t\tif n == 0 || %s == nil { return nil }\n", cExpr)
					g.printf("\t\t\tcSlice := unsafe.Slice(%s, n)\n", cExpr)
					g.printf("\t\t\tresult := make([]%s, n)\n", goElem)
					g.printf("\t\t\tfor i := 0; i < n; i++ { result[i] = %s(cSlice[i]) }\n", goElem)
					g.printf("\t\t\treturn result\n")
					g.printf("\t\t}(),\n")
				}
			case ast.TypeNamed:
				if g.isEnum(t.Elem.Name) {
					goElem := toPascalCase(t.Elem.Name)
					g.printf("\t\t%s: func() []%s {\n", goField, goElem)
					g.printf("\t\t\tn := int(%s)\n", lenExpr)
					g.printf("\t\t\tif n == 0 || %s == nil { return nil }\n", cExpr)
					g.printf("\t\t\tcSlice := unsafe.Slice(%s, n)\n", cExpr)
					g.printf("\t\t\tresult := make([]%s, n)\n", goElem)
					g.printf("\t\t\tfor i := 0; i < n; i++ { result[i] = %s(cSlice[i]) }\n", goElem)
					g.printf("\t\t\treturn result\n")
					g.printf("\t\t}(),\n")
				} else {
					// []Struct: use CToGo converter per element
					goElem := toPascalCase(t.Elem.Name)
					converter := toLowerCamelRaw(t.Elem.Name) + "CToGo"
					g.printf("\t\t%s: func() []%s {\n", goField, goElem)
					g.printf("\t\t\tn := int(%s)\n", lenExpr)
					g.printf("\t\t\tif n == 0 || %s == nil { return nil }\n", cExpr)
					g.printf("\t\t\tcSlice := unsafe.Slice(%s, n)\n", cExpr)
					g.printf("\t\t\tresult := make([]%s, n)\n", goElem)
					g.printf("\t\t\tfor i := 0; i < n; i++ { result[i] = %s(&cSlice[i]) }\n", converter)
					g.printf("\t\t\treturn result\n")
					g.printf("\t\t}(),\n")
				}
			}
		}
	case ast.TypeArray:
		if t.Elem != nil {
			arrLen := t.ArrayLen
			switch t.Elem.Kind {
			case ast.TypePrimitive:
				goElem := goTypeForDispatch(*t.Elem)
				g.printf("\t\t%s: func() [%d]%s {\n", goField, arrLen, goElem)
				g.printf("\t\t\tvar result [%d]%s\n", arrLen, goElem)
				g.printf("\t\t\tfor i := 0; i < %d; i++ { result[i] = %s(%s[i]) }\n", arrLen, goElem, cExpr)
				g.printf("\t\t\treturn result\n")
				g.printf("\t\t}(),\n")
			case ast.TypeNamed:
				if g.isEnum(t.Elem.Name) {
					goElem := toPascalCase(t.Elem.Name)
					g.printf("\t\t%s: func() [%d]%s {\n", goField, arrLen, goElem)
					g.printf("\t\t\tvar result [%d]%s\n", arrLen, goElem)
					g.printf("\t\t\tfor i := 0; i < %d; i++ { result[i] = %s(%s[i]) }\n", arrLen, goElem, cExpr)
					g.printf("\t\t\treturn result\n")
					g.printf("\t\t}(),\n")
				} else {
					goElem := toPascalCase(t.Elem.Name)
					converter := toLowerCamelRaw(t.Elem.Name) + "CToGo"
					g.printf("\t\t%s: func() [%d]%s {\n", goField, arrLen, goElem)
					g.printf("\t\t\tvar result [%d]%s\n", arrLen, goElem)
					g.printf("\t\t\tfor i := 0; i < %d; i++ { result[i] = %s(&%s[i]) }\n", arrLen, converter, cExpr)
					g.printf("\t\t\treturn result\n")
					g.printf("\t\t}(),\n")
				}
			}
		}
	}
}

func (g *dispatchCGen) isEnum(name string) bool {
	for _, e := range g.api.Enums {
		if e.Name == name {
			return true
		}
	}
	return false
}

// --- GoToC Converters ---
//
// All GoToC converters use a uniform signature with a freeList parameter
// for tracking C.CString allocations.  The caller (dispatch function)
// creates the freeList and defers freeing all pointers after the C call
// returns.  This ensures forward-compatibility: adding a string field
// to any struct type doesn't change converter signatures.

func (g *dispatchCGen) emitGoToCConverters() {
	// Only emit for struct types (not enums).
	hasStructs := false
	for _, t := range g.api.Types {
		if !g.isEnum(t.Name) {
			hasStructs = true
			break
		}
	}
	if !hasStructs {
		return
	}
	g.printf("// --- GoToC Converters ---\n\n")

	for _, t := range g.api.Types {
		if g.isEnum(t.Name) {
			continue
		}
		goName := toPascalCase(t.Name)
		cType := fmt.Sprintf("C.%s_%s_t", g.api.Name, toSnakeCase(t.Name))
		funcName := toLowerCamelRaw(t.Name) + "GoToC"

		g.printf("func %s(src %s, freeList *[]unsafe.Pointer) %s {\n", funcName, goName, cType)
		g.printf("\tvar dst %s\n", cType)
		for _, f := range t.Fields {
			goField := toPascalCase(f.Name)
			cField := "dst." + cgoFieldAccess(f.Name)
			g.emitFieldGoToC(cField, "src."+goField, f.Type)
		}
		g.printf("\treturn dst\n")
		g.printf("}\n\n")
	}
}

// emitFieldGoToC emits an imperative assignment for a single struct field.
// String fields are allocated via C.CString and tracked in freeList.
func (g *dispatchCGen) emitFieldGoToC(cField, goExpr string, t ast.TypeRef) {
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case ast.PrimString:
			g.tmpSeq++
			tmp := fmt.Sprintf("_cs%d", g.tmpSeq)
			if t.Nullable {
				// nil must reach C as NULL. Emitting C.CString("") here is what
				// let an omitted field read as a supplied empty one on the C
				// side, where the convention is a NULL check.
				g.printf("\tif %s != nil {\n", goExpr)
				g.printf("\t\t%s := C.CString(*%s)\n", tmp, goExpr)
				g.printf("\t\t*freeList = append(*freeList, unsafe.Pointer(%s))\n", tmp)
				g.printf("\t\t%s = %s\n", cField, tmp)
				g.printf("\t}\n")
			} else {
				g.printf("\t%s := C.CString(%s)\n", tmp, goExpr)
				g.printf("\t*freeList = append(*freeList, unsafe.Pointer(%s))\n", tmp)
				g.printf("\t%s = %s\n", cField, tmp)
			}
		case ast.PrimBool:
			if t.Nullable {
				g.printf("\tif %s != nil { %s = C.bool(*%s) }\n", goExpr, cField, goExpr)
			} else {
				g.printf("\t%s = C.bool(%s)\n", cField, goExpr)
			}
		case ast.PrimI8:
			g.printf("\t%s = C.int8_t(%s)\n", cField, goExpr)
		case ast.PrimU8:
			g.printf("\t%s = C.uint8_t(%s)\n", cField, goExpr)
		case ast.PrimI16:
			if t.Nullable {
				g.printf("\tif %s != nil { %s = C.int16_t(*%s) }\n", goExpr, cField, goExpr)
			} else {
				g.printf("\t%s = C.int16_t(%s)\n", cField, goExpr)
			}
		case ast.PrimU16:
			if t.Nullable {
				g.printf("\tif %s != nil { %s = C.uint16_t(*%s) }\n", goExpr, cField, goExpr)
			} else {
				g.printf("\t%s = C.uint16_t(%s)\n", cField, goExpr)
			}
		case ast.PrimI32:
			if t.Nullable {
				g.printf("\tif %s != nil { %s = C.int32_t(*%s) }\n", goExpr, cField, goExpr)
			} else {
				g.printf("\t%s = C.int32_t(%s)\n", cField, goExpr)
			}
		case ast.PrimU32:
			if t.Nullable {
				g.printf("\tif %s != nil { %s = C.uint32_t(*%s) }\n", goExpr, cField, goExpr)
			} else {
				g.printf("\t%s = C.uint32_t(%s)\n", cField, goExpr)
			}
		case ast.PrimI64:
			if t.Nullable {
				g.printf("\tif %s != nil { %s = C.int64_t(*%s) }\n", goExpr, cField, goExpr)
			} else {
				g.printf("\t%s = C.int64_t(%s)\n", cField, goExpr)
			}
		case ast.PrimU64:
			if t.Nullable {
				g.printf("\tif %s != nil { %s = C.uint64_t(*%s) }\n", goExpr, cField, goExpr)
			} else {
				g.printf("\t%s = C.uint64_t(%s)\n", cField, goExpr)
			}
		case ast.PrimF32:
			g.printf("\t%s = C.float(%s)\n", cField, goExpr)
		case ast.PrimF64:
			g.printf("\t%s = C.double(%s)\n", cField, goExpr)
		}
	case ast.TypeNamed:
		if g.isEnum(t.Name) {
			cType := fmt.Sprintf("C.%s_%s_t", g.api.Name, toSnakeCase(t.Name))
			g.printf("\t%s = %s(%s)\n", cField, cType, goExpr)
		} else {
			converter := toLowerCamelRaw(t.Name) + "GoToC"
			g.printf("\t%s = %s(%s, freeList)\n", cField, converter, goExpr)
		}
	case ast.TypeSlice:
		// Slice field: allocate C array, convert elements, set pointer + length.
		g.tmpSeq++
		nVar := fmt.Sprintf("_n%d", g.tmpSeq)
		arrVar := fmt.Sprintf("_arr%d", g.tmpSeq)
		g.printf("\t%s := len(%s)\n", nVar, goExpr)
		g.printf("\tif %s > 0 {\n", nVar)
		lenField := cField + "_len"
		g.printf("\t\t%s = C.size_t(%s)\n", lenField, nVar)
		if t.Elem.Kind == ast.TypePrimitive && t.Elem.Name == ast.PrimString {
			// []string → allocate **C.char array
			g.printf("\t\t%s := (**C.char)(C.calloc(C.size_t(%s), C.size_t(unsafe.Sizeof((*C.char)(nil)))))\n", arrVar, nVar)
			g.printf("\t\t*freeList = append(*freeList, unsafe.Pointer(%s))\n", arrVar)
			g.printf("\t\t_sl%d := unsafe.Slice(%s, %s)\n", g.tmpSeq, arrVar, nVar)
			g.printf("\t\tfor _i%d := range %s {\n", g.tmpSeq, goExpr)
			g.printf("\t\t\t_sl%d[_i%d] = C.CString(%s[_i%d])\n", g.tmpSeq, g.tmpSeq, goExpr, g.tmpSeq)
			g.printf("\t\t\t*freeList = append(*freeList, unsafe.Pointer(_sl%d[_i%d]))\n", g.tmpSeq, g.tmpSeq)
			g.printf("\t\t}\n")
			g.printf("\t\t%s = %s\n", cField, arrVar)
		} else if t.Elem.Kind == ast.TypeNamed && !g.isEnum(t.Elem.Name) {
			// []Struct → allocate array of C structs
			elemCType := fmt.Sprintf("C.%s_%s_t", g.api.Name, toSnakeCase(t.Elem.Name))
			converter := toLowerCamelRaw(t.Elem.Name) + "GoToC"
			g.printf("\t\t%s := (*%s)(C.calloc(C.size_t(%s), C.size_t(unsafe.Sizeof(%s{}))))\n", arrVar, elemCType, nVar, elemCType)
			g.printf("\t\t*freeList = append(*freeList, unsafe.Pointer(%s))\n", arrVar)
			g.printf("\t\t_sl%d := unsafe.Slice(%s, %s)\n", g.tmpSeq, arrVar, nVar)
			g.printf("\t\tfor _i%d := range %s {\n", g.tmpSeq, goExpr)
			g.printf("\t\t\t_sl%d[_i%d] = %s(%s[_i%d], freeList)\n", g.tmpSeq, g.tmpSeq, converter, goExpr, g.tmpSeq)
			g.printf("\t\t}\n")
			g.printf("\t\t%s = %s\n", cField, arrVar)
		} else {
			// []primitive (non-string) → allocate array of C type
			elemCType := cTypeForAPICgo(g.api.Name, *t.Elem)
			// Use appropriate zero value for Sizeof (bool needs special handling)
			zeroVal := elemCType + "(0)"
			if t.Elem.Name == ast.PrimBool {
				zeroVal = elemCType + "(false)"
			}
			g.printf("\t\t%s := (*%s)(C.calloc(C.size_t(%s), C.size_t(unsafe.Sizeof(%s))))\n", arrVar, elemCType, nVar, zeroVal)
			g.printf("\t\t*freeList = append(*freeList, unsafe.Pointer(%s))\n", arrVar)
			g.printf("\t\t_sl%d := unsafe.Slice(%s, %s)\n", g.tmpSeq, arrVar, nVar)
			g.printf("\t\tfor _i%d := range %s {\n", g.tmpSeq, goExpr)
			g.printf("\t\t\t_sl%d[_i%d] = %s(%s[_i%d])\n", g.tmpSeq, g.tmpSeq, elemCType, goExpr, g.tmpSeq)
			g.printf("\t\t}\n")
			g.printf("\t\t%s = %s\n", cField, arrVar)
		}
		g.printf("\t}\n")
	case ast.TypeArray:
		if t.Elem != nil {
			arrLen := t.ArrayLen
			switch t.Elem.Kind {
			case ast.TypePrimitive:
				if t.Elem.Name == ast.PrimString {
					// A fixed array of string would need per-element C.CString
					// alloc + freeList tracking (mirrored on the free side); the
					// scalar-conversion path below emits non-compiling code and
					// leaks. Reject rather than emit broken code — no IDL uses it.
					panic(fmt.Sprintf("gmicompile: emitFieldGoToC: fixed-array-of-string field %q in api %q is not supported — use []string, or implement array-of-string alloc/free", cField, g.api.Name))
				}
				elemCType := cTypeForAPICgo(g.api.Name, *t.Elem)
				g.printf("\tfor _i := 0; _i < %d; _i++ { %s[_i] = %s(%s[_i]) }\n", arrLen, cField, elemCType, goExpr)
			case ast.TypeNamed:
				if g.isEnum(t.Elem.Name) {
					elemCType := fmt.Sprintf("C.%s_%s_t", g.api.Name, toSnakeCase(t.Elem.Name))
					g.printf("\tfor _i := 0; _i < %d; _i++ { %s[_i] = %s(%s[_i]) }\n", arrLen, cField, elemCType, goExpr)
				} else {
					converter := toLowerCamelRaw(t.Elem.Name) + "GoToC"
					g.printf("\tfor _i := 0; _i < %d; _i++ { %s[_i] = %s(%s[_i], freeList) }\n", arrLen, cField, converter, goExpr)
				}
			}
		}
	}
}

// --- Dispatch Functions ---

func (g *dispatchCGen) emitDispatchFuncs() {
	if len(g.api.Funcs) == 0 {
		return
	}
	g.printf("// --- Dispatch Functions ---\n\n")

	for _, fn := range g.api.Funcs {
		if fn.Publish {
			continue
		}
		g.emitOneDispatch(fn)
	}
}

func (g *dispatchCGen) emitOneDispatch(fn ast.Func) {
	apiName := g.api.Name
	fnSnake := toSnakeCase(fn.Name)
	dispatchName := apiName + "Dispatch" + toPascalCase(fn.Name)
	wrapperName := fmt.Sprintf("C.call_%s_%s", apiName, fnSnake)
	cbsType := fmt.Sprintf("C.%s_callbacks_t", apiName)

	g.printf("func %s(callbacks unsafe.Pointer, req []byte) ([]byte, error) {\n", dispatchName)
	g.printf("\tcb := (*%s)(callbacks)\n", cbsType)
	g.printf("\tvar _freeList []unsafe.Pointer\n")
	g.printf("\tdefer func() { for _, p := range _freeList { C.free(p) } }()\n")

	// Unmarshal JSON params. Out params carry the reply, not the request — the
	// request has no field for them and reading one would let a caller supply
	// the value the provider is supposed to produce.
	inParams := make([]ast.Param, 0, len(fn.Params))
	for _, p := range fn.Params {
		if !p.IsOut {
			inParams = append(inParams, p)
		}
	}
	if len(inParams) > 0 {
		g.printf("\tvar params struct {\n")
		for _, p := range inParams {
			fieldName := toPascalCase(p.Name)
			var fieldType string
			if p.IsPtr {
				fieldType = "uint64"
			} else {
				fieldType = goTypeForDispatch(p.Type)
			}
			jsonTag := p.Name
			// A surviving 64-bit param is a body param (check layer rejects 64-bit
			// path/query params), so ",string" is safe. See jsonStringOpt.
			g.printf("\t\t%s %s `json:\"%s%s\"`\n", fieldName, fieldType, jsonTag, jsonStringOptParam(p))
		}
		g.printf("\t}\n")
		g.printf("\tif len(req) > 0 {\n")
		g.printf("\t\tif err := json.Unmarshal(req, &params); err != nil {\n")
		g.printf("\t\t\treturn nil, syscall.EINVAL\n")
		g.printf("\t\t}\n")
		g.printf("\t}\n")

		// Validate IDL @constraints before converting/dispatching (shared func).
		if g.ce.needsValidation(fn) {
			g.printf("\tif verr := %s; verr != nil {\n\t\treturn nil, verr\n\t}\n", g.ce.validateCallExpr(fn, "params"))
		}
	}

	// Convert Go params → C and build call args. The wrapper reads the
	// function pointer and ctx from the struct in C — ctx may be a cgo.Handle
	// integer that must never occupy a Go pointer-typed slot.
	var callArgs []string
	callArgs = append(callArgs, "cb")

	for _, p := range fn.Params {
		cVar := "c" + toPascalCase(p.Name)
		goVar := "params." + toPascalCase(p.Name)
		if p.IsOut {
			g.emitOutParamDecl(cVar, p)
		} else {
			g.emitParamGoToC(cVar, goVar, p)
		}
		callArgs = append(callArgs, g.paramCallArg(cVar, p)...)
	}

	// @rc_error: the return is the status channel and the out param is the
	// payload, so a provider failure becomes an error here instead of a
	// zero-valued 200 response.
	if payload, ok := rcErrorPayload(fn); ok {
		g.printf("\trc := int32(%s(%s))\n", wrapperName, strings.Join(callArgs, ", "))
		g.printf("\tif rc != 0 {\n")
		g.printf("\t\treturn nil, fmt.Errorf(%q, rc)\n", fn.Name+": rc=%d")
		g.printf("\t}\n")
		g.emitOutPayloadConvert("c"+toPascalCase(payload.Name), payload)
		g.printf("\treturn json.Marshal(result)\n")
		g.printf("}\n\n")
		return
	}

	// Call C wrapper — direct return (no error code, no out-param)
	if fn.Return != nil {
		g.printf("\tout := %s(%s)\n", wrapperName, strings.Join(callArgs, ", "))
		g.emitReturnConvert(fn)
	} else {
		g.printf("\t%s(%s)\n", wrapperName, strings.Join(callArgs, ", "))
		g.printf("\treturn nil, nil\n")
	}

	g.printf("}\n\n")
}

// emitNullableScalarGoToC marshals a nullable scalar param (Go *T) into a
// C-heap `*C.<ctype>` — NULL when the Go pointer is nil, so "absent" survives
// the C ABI. The allocation is tracked in _freeList and freed after the call
// (same lifetime as the CString params). cType is the cgo type, e.g. "C.int32_t".
func (g *dispatchCGen) emitNullableScalarGoToC(cVar, goVar, cType string) {
	g.printf("\tvar %s *%s\n", cVar, cType)
	g.printf("\tif %s != nil {\n", goVar)
	g.printf("\t\t%s = (*%s)(C.malloc(C.size_t(unsafe.Sizeof(*new(%s)))))\n", cVar, cType, cType)
	g.printf("\t\t_freeList = append(_freeList, unsafe.Pointer(%s))\n", cVar)
	g.printf("\t\t*%s = %s(*%s)\n", cVar, cType, goVar)
	g.printf("\t}\n")
}

func (g *dispatchCGen) emitParamGoToC(cVar, goVar string, p ast.Param) {
	// ptr qualifier: cast uintptr → unsafe.Pointer → *C.type (no marshaling).
	if p.IsPtr {
		var cType string
		switch p.Type.Kind {
		case ast.TypePrimitive:
			cType = "*C." + primitiveToCType(p.Type.Name)
		default:
			cType = fmt.Sprintf("*C.%s_%s_t", g.api.Name, toSnakeCase(p.Type.Name))
		}
		g.printf("\t%s := (%s)(unsafe.Pointer(uintptr(%s)))\n", cVar, cType, goVar)
		return
	}
	t := p.Type
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case ast.PrimString:
			if t.Nullable {
				// Same rule as a nullable struct field: nil reaches C as NULL,
				// so a callee's `if (pattern)` means what it says.
				g.printf("\tvar %s *C.char\n", cVar)
				g.printf("\tif %s != nil {\n", goVar)
				g.printf("\t\t%s = C.CString(*%s)\n", cVar, goVar)
				g.printf("\t\t_freeList = append(_freeList, unsafe.Pointer(%s))\n", cVar)
				g.printf("\t}\n")
			} else {
				g.printf("\t%s := C.CString(%s)\n", cVar, goVar)
				g.printf("\t_freeList = append(_freeList, unsafe.Pointer(%s))\n", cVar)
			}
		case ast.PrimBool:
			if t.Nullable {
				g.emitNullableScalarGoToC(cVar, goVar, "C.bool")
			} else {
				g.printf("\t%s := C.bool(%s)\n", cVar, goVar)
			}
		case ast.PrimI8:
			g.printf("\t%s := C.int8_t(%s)\n", cVar, goVar)
		case ast.PrimU8:
			g.printf("\t%s := C.uint8_t(%s)\n", cVar, goVar)
		case ast.PrimI16:
			if t.Nullable {
				g.emitNullableScalarGoToC(cVar, goVar, "C.int16_t")
			} else {
				g.printf("\t%s := C.int16_t(%s)\n", cVar, goVar)
			}
		case ast.PrimU16:
			if t.Nullable {
				g.emitNullableScalarGoToC(cVar, goVar, "C.uint16_t")
			} else {
				g.printf("\t%s := C.uint16_t(%s)\n", cVar, goVar)
			}
		case ast.PrimI32:
			if t.Nullable {
				g.emitNullableScalarGoToC(cVar, goVar, "C.int32_t")
			} else {
				g.printf("\t%s := C.int32_t(%s)\n", cVar, goVar)
			}
		case ast.PrimU32:
			if t.Nullable {
				g.emitNullableScalarGoToC(cVar, goVar, "C.uint32_t")
			} else {
				g.printf("\t%s := C.uint32_t(%s)\n", cVar, goVar)
			}
		case ast.PrimI64:
			if t.Nullable {
				g.emitNullableScalarGoToC(cVar, goVar, "C.int64_t")
			} else {
				g.printf("\t%s := C.int64_t(%s)\n", cVar, goVar)
			}
		case ast.PrimU64:
			if t.Nullable {
				g.emitNullableScalarGoToC(cVar, goVar, "C.uint64_t")
			} else {
				g.printf("\t%s := C.uint64_t(%s)\n", cVar, goVar)
			}
		case ast.PrimF32:
			g.printf("\t%s := C.float(%s)\n", cVar, goVar)
		case ast.PrimF64:
			g.printf("\t%s := C.double(%s)\n", cVar, goVar)
		case ast.PrimPtr:
			// ptr is an opaque pointer — not serializable; pass nil for non-REST stubs
			g.printf("\tvar %s unsafe.Pointer // ptr: not serializable\n", cVar)
		}
	case ast.TypeCallback:
		// Callback function pointers cannot be serialized; pass nil for non-REST stubs
		g.printf("\tvar %s unsafe.Pointer // callback: not serializable\n", cVar)
	case ast.TypeImport:
		// Imported struct pointers cannot be serialized; pass nil for non-REST stubs
		g.printf("\tvar %s unsafe.Pointer // import: not serializable\n", cVar)
	case ast.TypeNamed:
		if g.isEnum(t.Name) {
			cType := fmt.Sprintf("C.%s_%s_t", g.api.Name, toSnakeCase(t.Name))
			g.printf("\t%s := %s(%s)\n", cVar, cType, goVar)
		} else {
			converter := toLowerCamelRaw(t.Name) + "GoToC"
			g.printf("\t%s := %s(%s, &_freeList)\n", cVar, converter, goVar)
		}
	case ast.TypeArray:
		// Convert Go [N]T → C [N]T element by element.
		elemCType := cTypeForAPICgo(g.api.Name, *t.Elem)
		g.printf("\tvar %s [%d]%s\n", cVar, t.ArrayLen, elemCType)
		g.printf("\tfor i := 0; i < %d; i++ {\n", t.ArrayLen)
		g.printf("\t\t%s[i] = %s(%s[i])\n", cVar, elemCType, goVar)
		g.printf("\t}\n")
	case ast.TypeSlice:
		if t.Elem != nil && t.Elem.Kind == ast.TypePrimitive && t.Elem.Name == ast.PrimString {
			// []string → char** + count
			g.printf("\t%sLen := C.size_t(len(%s))\n", cVar, goVar)
			g.printf("\t%s := (**C.char)(C.malloc(C.size_t(len(%s)) * C.size_t(unsafe.Sizeof((*C.char)(nil)))))\n", cVar, goVar)
			g.printf("\tdefer C.free(unsafe.Pointer(%s))\n", cVar)
			g.printf("\t%sSlice := unsafe.Slice(%s, len(%s))\n", cVar, cVar, goVar)
			g.printf("\tfor i, s := range %s {\n", goVar)
			g.printf("\t\t%sSlice[i] = C.CString(s)\n", cVar)
			g.printf("\t}\n")
			g.printf("\tdefer func() {\n")
			g.printf("\t\tfor i := range %s {\n", goVar)
			g.printf("\t\t\tC.free(unsafe.Pointer(%sSlice[i]))\n", cVar)
			g.printf("\t\t}\n")
			g.printf("\t}()\n")
		} else if t.Elem != nil && t.Elem.Kind == ast.TypeNamed {
			// []Struct → C array of struct_t + length
			elemCType := cTypeForAPICgo(g.api.Name, *t.Elem)
			converter := toLowerCamelRaw(t.Elem.Name) + "GoToC"
			g.printf("\t%sLen := C.size_t(len(%s))\n", cVar, goVar)
			g.printf("\tvar %s *%s\n", cVar, elemCType)
			g.printf("\tif len(%s) > 0 {\n", goVar)
			g.printf("\t\t%s = (*%s)(C.malloc(C.size_t(len(%s)) * C.size_t(unsafe.Sizeof(%s{}))))\n", cVar, elemCType, goVar, elemCType)
			g.printf("\t\t_freeList = append(_freeList, unsafe.Pointer(%s))\n", cVar)
			g.printf("\t\t%sSlice := unsafe.Slice(%s, len(%s))\n", cVar, cVar, goVar)
			g.printf("\t\tfor i, v := range %s {\n", goVar)
			g.printf("\t\t\t%sSlice[i] = %s(v, &_freeList)\n", cVar, converter)
			g.printf("\t\t}\n")
			g.printf("\t}\n")
		} else if t.Elem != nil {
			// []primitive → C array + length
			elemCType := cTypeForAPICgo(g.api.Name, *t.Elem)
			g.printf("\t%sLen := C.size_t(len(%s))\n", cVar, goVar)
			g.printf("\tvar %s *%s\n", cVar, elemCType)
			g.printf("\tif len(%s) > 0 {\n", goVar)
			g.printf("\t\t%s = (*%s)(C.malloc(C.size_t(len(%s)) * C.size_t(unsafe.Sizeof(%s(0)))))\n", cVar, elemCType, goVar, elemCType)
			g.printf("\t\t_freeList = append(_freeList, unsafe.Pointer(%s))\n", cVar)
			g.printf("\t\t%sSlice := unsafe.Slice(%s, len(%s))\n", cVar, cVar, goVar)
			g.printf("\t\tfor i, v := range %s {\n", goVar)
			g.printf("\t\t\t%sSlice[i] = %s(v)\n", cVar, elemCType)
			g.printf("\t\t}\n")
			g.printf("\t}\n")
		}
	}
}

// paramCallArg returns the C call arguments for a parameter.
// Handles byref/out (pass pointer), arrays (pass pointer to first element), etc.
func (g *dispatchCGen) paramCallArg(cVar string, p ast.Param) []string {
	// ptr qualifier: cVar is already a pointer, pass directly.
	if p.IsPtr {
		return []string{cVar}
	}
	switch p.Type.Kind {
	case ast.TypePrimitive:
		if p.ByRef || p.IsOut {
			return []string{"&" + cVar}
		}
		return []string{cVar}
	case ast.TypeNamed:
		// Enums pass by value; structs pass by pointer (const or mutable).
		if g.isEnum(p.Type.Name) {
			if p.ByRef || p.IsOut {
				return []string{"&" + cVar}
			}
			return []string{cVar}
		}
		return []string{"&" + cVar}
	case ast.TypeArray:
		// Arrays pass pointer to first element.
		return []string{"&" + cVar + "[0]"}
	case ast.TypeSlice:
		if p.IsOut {
			return []string{"&" + cVar}
		}
		return []string{cVar, cVar + "Len"}
	}
	return []string{cVar}
}

// emitOutParamDecl declares the zeroed C variable an out parameter is written
// into. Nothing is read from the request for it — the provider fills it.
func (g *dispatchCGen) emitOutParamDecl(cVar string, p ast.Param) {
	switch p.Type.Kind {
	case ast.TypeSlice:
		g.printf("\tvar %s C.%s\n", cVar, sliceOutCTypeName(g.api.Name, p.Type))
	case ast.TypeArray:
		g.printf("\tvar %s [%d]%s\n", cVar, p.Type.ArrayLen, cTypeForAPICgo(g.api.Name, *p.Type.Elem))
	default:
		g.printf("\tvar %s %s\n", cVar, cTypeForAPICgo(g.api.Name, p.Type))
	}
}

// emitOutPayloadConvert converts a filled-in out parameter into the Go `result`
// the dispatch marshals, freeing whatever the provider allocated. The
// conversion is the same one a by-value return goes through — an @rc_error func
// and its value-returning predecessor produce byte-identical JSON.
func (g *dispatchCGen) emitOutPayloadConvert(cVar string, p ast.Param) {
	g.emitPayloadConvert(cVar, p.Type)
}

func (g *dispatchCGen) emitReturnConvert(fn ast.Func) {
	ret := fn.Return
	g.emitPayloadConvert("out", *ret)

	// For []u8 (byte slices), return raw bytes without JSON encoding.
	// This supports BinaryWatchFunc which sends data as binary WS frames.
	if ret.Kind == ast.TypeSlice && ret.Elem.Kind == ast.TypePrimitive && ret.Elem.Name == "u8" {
		g.printf("\treturn result, nil\n")
		return
	}
	g.printf("\treturn json.Marshal(result)\n")
}

// emitPayloadConvert emits `result := <Go value>` from the C value in cExpr and
// frees the C allocations it owns. cExpr is a by-value C struct/scalar for a
// direct return, or the local an out parameter was written into; a slice payload
// is a {data, len} struct either way, so both share this code.
func (g *dispatchCGen) emitPayloadConvert(cExpr string, t ast.TypeRef) {
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case ast.PrimString:
			// Caller owns returned data: free the C string after copying.
			g.printf("\tresult := C.GoString(%s)\n", cExpr)
			g.printf("\tif %s != nil {\n", cExpr)
			g.printf("\t\tC.free(unsafe.Pointer(%s))\n", cExpr)
			g.printf("\t}\n")
		case ast.PrimBool:
			g.printf("\tresult := bool(%s)\n", cExpr)
		default:
			goType := primitiveToGoType(t.Name)
			g.printf("\tresult := %s(%s)\n", goType, cExpr)
		}

	case ast.TypeNamed:
		if g.isEnum(t.Name) {
			goType := toPascalCase(t.Name)
			g.printf("\tresult := %s(%s)\n", goType, cExpr)
		} else {
			converter := toLowerCamelRaw(t.Name) + "CToGo"
			g.printf("\tresult := %s(&%s)\n", converter, cExpr)
			// Caller owns returned data: free the C allocations
			// (strings, slice buffers) after converting to Go.
			if ty := g.findType(t.Name); ty != nil && g.typeHasCAllocs(t.Name, map[string]bool{}) {
				g.emitFreeCAllocs(cExpr, ty, 0, "\t")
			}
		}

	case ast.TypeSlice:
		// cExpr is a result struct with .data (pointer) and .len (size_t)
		g.printf("\tn := int(%s.len)\n", cExpr)
		if t.Elem.Kind == ast.TypeNamed && !g.isEnum(t.Elem.Name) {
			goElemType := toPascalCase(t.Elem.Name)
			converter := toLowerCamelRaw(t.Elem.Name) + "CToGo"
			g.printf("\tresult := make([]%s, n)\n", goElemType)
			g.printf("\tif n > 0 {\n")
			g.printf("\t\tcSlice := unsafe.Slice(%s.data, n)\n", cExpr)
			g.printf("\t\tfor i := 0; i < n; i++ {\n")
			g.printf("\t\t\tresult[i] = %s(&cSlice[i])\n", converter)
			if ty := g.findType(t.Elem.Name); ty != nil && g.typeHasCAllocs(t.Elem.Name, map[string]bool{}) {
				g.emitFreeCAllocs("cSlice[i]", ty, 1, "\t\t\t")
			}
			g.printf("\t\t}\n")
			g.printf("\t\tC.free(unsafe.Pointer(%s.data))\n", cExpr)
			g.printf("\t}\n")
		} else {
			goElemType := goTypeForDispatch(*t.Elem)
			g.printf("\tresult := make([]%s, n)\n", goElemType)
			g.printf("\tif n > 0 {\n")
			g.printf("\t\tcSlice := unsafe.Slice(%s.data, n)\n", cExpr)
			g.printf("\t\tfor i := 0; i < n; i++ {\n")
			if t.Elem.Kind == ast.TypePrimitive && t.Elem.Name == ast.PrimString {
				g.printf("\t\t\tresult[i] = C.GoString(cSlice[i])\n")
				g.printf("\t\t\tif cSlice[i] != nil {\n")
				g.printf("\t\t\t\tC.free(unsafe.Pointer(cSlice[i]))\n")
				g.printf("\t\t\t}\n")
			} else {
				g.printf("\t\t\tresult[i] = %s(cSlice[i])\n", goElemType)
			}
			g.printf("\t\t}\n")
			g.printf("\t\tC.free(unsafe.Pointer(%s.data))\n", cExpr)
			g.printf("\t}\n")
		}
	}
}

// --- APIMeta ---

func (g *dispatchCGen) emitMeta() {
	metaVar := toPascalCase(g.api.Name) + "Meta"
	g.printf("// --- API Metadata ---\n\n")
	g.printf("var %s = &apiserver.APIMeta{\n", metaVar)
	g.printf("\tName:       %q,\n", g.api.Name)
	g.printf("\tVersion:    %d,\n", g.api.Version)
	g.printf("\tRESTExport: %t,\n", g.api.RestExport)
	g.printf("\tPrefix:     %q,\n", g.api.Prefix)
	g.printf("\tFuncs: []apiserver.FuncMeta{\n")
	for _, fn := range g.api.Funcs {
		if fn.Publish {
			continue
		}
		dispatchName := g.api.Name + "Dispatch" + toPascalCase(fn.Name)
		g.printf("\t\t{\n")
		g.printf("\t\t\tName:     %q,\n", fn.Name)
		g.printf("\t\t\tMethod:   %q,\n", fn.Method)
		g.printf("\t\t\tPath:     %q,\n", fn.Path)
		g.printf("\t\t\tRTSafe:   %t,\n", fn.RTSafe)
		g.printf("\t\t\tDispatch: %s,\n", dispatchName)
		g.printf("\t\t},\n")
	}
	g.printf("\t},\n")
	g.printf("}\n\n")
}

// --- Meta Registration ---

func (g *dispatchCGen) emitRegister() {
	metaVar := toPascalCase(g.api.Name) + "Meta"

	g.printf("// --- Meta Registration ---\n\n")
	g.printf("func init() {\n")
	g.printf("\tapiserver.RegisterMeta(%s)\n", metaVar)
	g.printf("}\n")
}

// --- Type Helpers ---

// toCTypeForAPI returns the C type string for use in the cgo preamble.
func toCTypeForAPI(apiName string, t ast.TypeRef) string {
	if t.Nullable && t.Kind == ast.TypePrimitive && t.Name == ast.PrimString {
		return "const char *"
	}
	switch t.Kind {
	case ast.TypePrimitive:
		return primitiveToCType(t.Name)
	case ast.TypeNamed:
		return fmt.Sprintf("%s_%s_t", apiName, toSnakeCase(t.Name))
	case ast.TypeSlice:
		elemType := toCTypeForAPI(apiName, *t.Elem)
		return fmt.Sprintf("%s *", elemType)
	case ast.TypeArray:
		elemType := toCTypeForAPI(apiName, *t.Elem)
		return fmt.Sprintf("%s[%s]", elemType, cArraySizeStr(apiName, t))
	}
	return "void"
}

// cTypeForAPICgo returns the C type for use in Go code (C. prefix).
func cTypeForAPICgo(apiName string, t ast.TypeRef) string {
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case ast.PrimBool:
			return "C.bool"
		case ast.PrimI8:
			return "C.int8_t"
		case ast.PrimU8:
			return "C.uint8_t"
		case ast.PrimI16:
			return "C.int16_t"
		case ast.PrimU16:
			return "C.uint16_t"
		case ast.PrimI32:
			return "C.int32_t"
		case ast.PrimU32:
			return "C.uint32_t"
		case ast.PrimI64:
			return "C.int64_t"
		case ast.PrimU64:
			return "C.uint64_t"
		case ast.PrimF32:
			return "C.float"
		case ast.PrimF64:
			return "C.double"
		case ast.PrimString:
			return "*C.char"
		case ast.PrimPtr:
			return "unsafe.Pointer"
		}
	case ast.TypeNamed:
		return fmt.Sprintf("C.%s_%s_t", apiName, toSnakeCase(t.Name))
	case ast.TypeSlice:
		return cTypeForAPICgo(apiName, *t.Elem)
	}
	// Fail loud rather than silently emitting C.int for an unsupported shape
	// (a fixed array, or a future primitive with no case): a wrong cgo type
	// truncates/mismaps at the FFI boundary. No current IDL reaches here.
	panic(fmt.Sprintf("gmicompile: cTypeForAPICgo: unsupported type shape %v (name %q) in api %q — add a case or reject in the parser", t.Kind, t.Name, apiName))
}

// goTypeForDispatch returns Go type string for use in dispatch code.
//
// This is the single mapping for provider-facing Go types: dispatch structs,
// the callbacks interface (via bridge_go), and the cgo client all go through
// it, and serverGoGen.toGoType delegates here.  It used to be one of three
// near-copies of the same rule, which is how `string?` came to mean *string in
// one emitter and string in another.
func goTypeForDispatch(t ast.TypeRef) string {
	switch t.Kind {
	case ast.TypePrimitive:
		base := primitiveToGoType(t.Name)
		if t.Nullable {
			return "*" + base
		}
		return base
	case ast.TypeNamed:
		name := toPascalCase(t.Name)
		if t.Nullable {
			return "*" + name
		}
		return name
	case ast.TypeSlice:
		return "[]" + goTypeForDispatch(*t.Elem)
	case ast.TypeArray:
		return fmt.Sprintf("[%d]%s", t.ArrayLen, goTypeForDispatch(*t.Elem))
	}
	return "interface{}"
}

// cgoFieldAccess returns the field name for accessing a C struct field from Go.
// Go keywords get a _ prefix in cgo.
func cgoFieldAccess(cFieldName string) string {
	// C keywords get underscore suffix in struct fields (see cSafeName).
	// cgo accesses those escaped names directly.
	if cKeywords[cFieldName] {
		return cFieldName + "_"
	}
	if goKeywords[cFieldName] {
		return "_" + cFieldName
	}
	return cFieldName
}

// toLowerCamelRaw converts snake_case to lowerCamelCase without keyword escaping.
func toLowerCamelRaw(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if i > 0 && len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	result := strings.Join(parts, "")
	if len(result) > 0 {
		result = strings.ToLower(result[:1]) + result[1:]
	}
	return result
}
