// Copyright (C) 2026 Sascha Ittner <sascha.ittner@modusoft.de>
// License: GPL Version 2
package cgen

import (
	"fmt"
	"io"
	"strings"

	"github.com/sittner/linuxcnc/src/gomc/internal/gmicompile/ast"
)

// GenerateServerGo writes Go server code: types, callbacks interface,
// dispatch wrappers, APIMeta, and Register function.
func GenerateServerGo(w io.Writer, api *ast.API, packageName string) error {
	g := &serverGoGen{w: w, api: api, pkg: packageName}
	return g.generate()
}

// GenerateServerGoExtra writes only the Commands and WatchRegister functions.
// It is appended to the bridge file which already has the package header and interface.
func GenerateServerGoExtra(w io.Writer, api *ast.API, packageName string) error {
	g := &serverGoGen{w: w, api: api, pkg: packageName}
	g.emitWatchCallbacksInterface()
	g.emitCommands()
	g.emitWatchRegister()
	return g.err
}

type serverGoGen struct {
	w   io.Writer
	api *ast.API
	pkg string
	err error
}

func (g *serverGoGen) printf(format string, args ...interface{}) {
	if g.err != nil {
		return
	}
	_, g.err = fmt.Fprintf(g.w, format, args...)
}

func (g *serverGoGen) generate() error {
	g.emitHeader()
	g.emitConstants()
	g.emitEnums()
	g.emitTypes()
	g.emitCallbacksInterface()
	g.emitWatchCallbacksInterface()
	g.emitDispatchFuncs()
	g.emitMeta()
	g.emitRegister()
	g.emitCommands()
	g.emitWatchRegister()
	return g.err
}

// --- Header ---

func (g *serverGoGen) emitHeader() {
	g.printf("// Code generated by gmicompile - DO NOT EDIT.\n")
	EmitMeta(g.w, g.api, "//")
	g.printf("\n")
	g.printf("package %s\n\n", g.pkg)

	needsTime := g.hasWatchFuncs()

	g.printf("import (\n")
	g.printf("\t\"encoding/json\"\n")
	g.printf("\t\"fmt\"\n")
	g.printf("\t\"syscall\"\n")
	if needsTime {
		g.printf("\t\"time\"\n")
	}
	g.printf("\t\"unsafe\"\n")
	g.printf("\n")
	g.printf("\t\"github.com/sittner/linuxcnc/src/gomc/internal/apiserver\"\n")
	g.printf(")\n\n")

	// Suppress unused import warnings
	g.printf("var _ = json.Marshal\n")
	g.printf("var _ = fmt.Sprintf\n")
	g.printf("var _ = syscall.EINVAL\n")
	if needsTime {
		g.printf("var _ time.Duration\n")
	}
	g.printf("var _ unsafe.Pointer\n\n")
}

// --- Constants ---

func (g *serverGoGen) emitConstants() {
	if len(g.api.Consts) == 0 {
		return
	}
	g.printf("// --- Constants ---\n\n")
	g.printf("const (\n")
	for _, c := range g.api.Consts {
		g.printf("\t%s = %d\n", c.Name, c.Value)
	}
	g.printf(")\n\n")
}

// --- Enums ---

func (g *serverGoGen) emitEnums() {
	if len(g.api.Enums) == 0 {
		return
	}
	g.printf("// --- Enums ---\n\n")
	for _, e := range g.api.Enums {
		goName := toPascalCase(e.Name)
		g.printf("type %s int32\n\n", goName)
		g.printf("const (\n")
		for _, v := range e.Values {
			g.printf("\t%s_%s %s = %d\n", goName, v.Name, goName, v.Value)
		}
		g.printf(")\n\n")
	}
}

// --- Struct Types ---

func (g *serverGoGen) emitTypes() {
	if len(g.api.Types) == 0 {
		return
	}
	g.printf("// --- Types ---\n\n")
	for _, t := range g.api.Types {
		goName := toPascalCase(t.Name)
		g.printf("type %s struct {\n", goName)
		for _, f := range t.Fields {
			fieldName := toPascalCase(f.Name)
			fieldType := g.toGoType(f.Type)
			jsonTag := f.Name
			omit := ""
			if f.Type.Nullable {
				omit = ",omitempty"
			}
			g.printf("\t%s %s `json:\"%s%s%s\"`\n", fieldName, fieldType, jsonTag, omit, jsonStringOpt(f.Type))
		}
		g.printf("}\n\n")
	}
}

// --- Callbacks Interface ---

func (g *serverGoGen) emitCallbacksInterface() {
	if len(g.api.Funcs) == 0 {
		return
	}
	ifaceName := toPascalCase(g.api.Name) + "Callbacks"
	g.printf("// --- Callbacks Interface ---\n\n")
	g.printf("// %s defines the API methods that modules must implement.\n", ifaceName)
	g.printf("type %s interface {\n", ifaceName)
	for _, fn := range g.api.Funcs {
		if fn.Watch && fn.Method == "" {
			continue // watch-only function — goes in WatchCallbacks
		}
		if fn.Publish {
			continue // @publish function — handled by ring drain, not callbacks
		}
		methodName := toPascalCase(fn.Name)
		params := g.goMethodParams(fn)
		ret := g.goMethodReturn(fn)
		g.printf("\t%s(%s) %s\n", methodName, params, ret)
	}
	g.printf("}\n\n")
}

func (g *serverGoGen) goMethodParams(fn ast.Func) string {
	parts := make([]string, 0, len(fn.Params))
	for _, p := range fn.Params {
		parts = append(parts, fmt.Sprintf("%s %s", toLowerCamel(p.Name), g.toGoType(p.Type)))
	}
	return strings.Join(parts, ", ")
}

func (g *serverGoGen) goMethodReturn(fn ast.Func) string {
	if fn.Return == nil {
		return "error"
	}
	retType := g.toGoType(*fn.Return)
	if fn.Return.Kind == ast.TypePrimitive {
		return fmt.Sprintf("(%s, error)", retType)
	}
	// Structs, slices, arrays → return pointer for named types
	if fn.Return.Kind == ast.TypeNamed {
		return fmt.Sprintf("(*%s, error)", retType)
	}
	return fmt.Sprintf("(%s, error)", retType)
}

// --- Dispatch Functions ---

func (g *serverGoGen) emitDispatchFuncs() {
	if len(g.api.Funcs) == 0 {
		return
	}
	g.printf("// --- Dispatch Functions ---\n\n")

	ifaceName := toPascalCase(g.api.Name) + "Callbacks"

	for _, fn := range g.api.Funcs {
		if fn.Watch && fn.Method == "" {
			continue // watch-only function — no dispatch needed
		}
		if fn.Publish {
			continue // @publish function — no dispatch needed
		}
		dispatchName := g.api.Name + "Dispatch" + toPascalCase(fn.Name)
		g.printf("func %s(callbacks unsafe.Pointer, req []byte) ([]byte, error) {\n", dispatchName)
		g.printf("\timpl := *(*%s)(callbacks)\n", ifaceName)

		// Unmarshal request params
		if len(fn.Params) > 0 {
			g.printf("\tvar params struct {\n")
			for _, p := range fn.Params {
				fieldName := toPascalCase(p.Name)
				fieldType := g.toGoType(p.Type)
				jsonTag := p.Name
				// A surviving 64-bit param is always a POST/PUT/PATCH *body* param:
				// the check layer rejects 64-bit path/query params (they would reach
				// apiserver.encodeParams as bare numbers, which a ",string" field
				// rejects). So ",string" here is safe and symmetric with the client.
				g.printf("\t\t%s %s `json:\"%s%s\"`\n", fieldName, fieldType, jsonTag, jsonStringOptParam(p))
			}
			g.printf("\t}\n")
			g.printf("\tif len(req) > 0 {\n")
			g.printf("\t\tif err := json.Unmarshal(req, &params); err != nil {\n")
			// Client error (400 via EINVAL) with the json detail kept — same
			// rule as the other dispatch emitters; keep all copies identical.
			g.printf("\t\t\treturn nil, fmt.Errorf(\"%%w: %%v\", syscall.EINVAL, err)\n")
			g.printf("\t\t}\n")
			g.printf("\t}\n")
		}

		// Call the interface method
		methodName := toPascalCase(fn.Name)
		args := make([]string, 0, len(fn.Params))
		for _, p := range fn.Params {
			args = append(args, "params."+toPascalCase(p.Name))
		}
		callArgs := strings.Join(args, ", ")

		if fn.Return == nil {
			g.printf("\tif err := impl.%s(%s); err != nil {\n", methodName, callArgs)
			g.printf("\t\treturn nil, err\n")
			g.printf("\t}\n")
			g.printf("\treturn nil, nil\n")
		} else {
			g.printf("\tresult, err := impl.%s(%s)\n", methodName, callArgs)
			g.printf("\tif err != nil {\n")
			g.printf("\t\treturn nil, err\n")
			g.printf("\t}\n")
			g.printf("\treturn json.Marshal(result)\n")
		}

		g.printf("}\n\n")
	}
}

// --- APIMeta ---

func (g *serverGoGen) emitMeta() {
	metaVar := toPascalCase(g.api.Name) + "Meta"
	g.printf("// --- API Metadata ---\n\n")
	g.printf("var %s = &apiserver.APIMeta{\n", metaVar)
	g.printf("\tName:       %q,\n", g.api.Name)
	g.printf("\tVersion:    %d,\n", g.api.Version)
	g.printf("\tRESTExport: %t,\n", g.api.RestExport)
	g.printf("\tPrefix:     %q,\n", g.api.Prefix)
	g.printf("\tFuncs: []apiserver.FuncMeta{\n")
	for _, fn := range g.api.Funcs {
		if fn.Method == "" {
			continue // watch-only function, no REST dispatch
		}
		dispatchName := g.api.Name + "Dispatch" + toPascalCase(fn.Name)
		g.printf("\t\t{\n")
		g.printf("\t\t\tName:     %q,\n", fn.Name)
		g.printf("\t\t\tMethod:   %q,\n", fn.Method)
		g.printf("\t\t\tPath:     %q,\n", fn.Path)
		g.printf("\t\t\tRTSafe:   %t,\n", fn.RTSafe)
		g.printf("\t\t\tDispatch: %s,\n", dispatchName)
		g.printf("\t\t},\n")
	}
	g.printf("\t},\n")
	g.printf("}\n\n")
}

// --- Register Function ---

func (g *serverGoGen) emitRegister() {
	apiPascal := toPascalCase(g.api.Name)
	funcName := "Register" + apiPascal + "API"
	ifaceName := apiPascal + "Callbacks"

	g.printf("// --- Registration ---\n\n")
	g.printf("// %s registers an implementation of the %s API.\n", funcName, g.api.Name)
	g.printf("func %s(registry *apiserver.Registry, instance string, impl %s) error {\n", funcName, ifaceName)
	g.printf("\tcb := impl\n")
	g.printf("\treturn registry.Register(%q, %d, instance, unsafe.Pointer(&cb))\n", g.api.Name, g.api.Version)
	g.printf("}\n")
}

// --- Type Mapping ---

// toGoType delegates to goTypeForDispatch so the provider-facing type mapping
// exists exactly once.  This used to be its own copy that differed in one
// clause — `string?` mapped to a plain `string` here while the dispatch and
// client emitters produced *string — which is what made a nullable string
// unrepresentable on the provider side.  See the note on goTypeForDispatch.
func (g *serverGoGen) toGoType(t ast.TypeRef) string {
	return goTypeForDispatch(t)
}

func primitiveToGoType(name string) string {
	switch name {
	case ast.PrimBool:
		return "bool"
	case ast.PrimI8:
		return "int8"
	case ast.PrimU8:
		return "uint8"
	case ast.PrimI16:
		return "int16"
	case ast.PrimU16:
		return "uint16"
	case ast.PrimI32:
		return "int32"
	case ast.PrimU32:
		return "uint32"
	case ast.PrimI64:
		return "int64"
	case ast.PrimU64:
		return "uint64"
	case ast.PrimF32:
		return "float32"
	case ast.PrimF64:
		return "float64"
	case ast.PrimString:
		return "string"
	}
	return "interface{}"
}

// --- Name Helpers ---

// toPascalCase converts snake_case or camelCase to PascalCase.
func toPascalCase(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

// toLowerCamel converts snake_case to lowerCamelCase.
func toLowerCamel(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if i > 0 && len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return escapeGoKeyword(strings.Join(parts, ""))
}

// goKeywords is the set of Go reserved words.
var goKeywords = map[string]bool{
	"break": true, "case": true, "chan": true, "const": true, "continue": true,
	"default": true, "defer": true, "else": true, "fallthrough": true, "for": true,
	"func": true, "go": true, "goto": true, "if": true, "import": true,
	"interface": true, "map": true, "package": true, "range": true, "return": true,
	"select": true, "struct": true, "switch": true, "type": true, "var": true,
}

func escapeGoKeyword(name string) string {
	if goKeywords[name] {
		return name + "_"
	}
	return name
}

// --- Helper predicates ---

func (g *serverGoGen) hasWatchFuncs() bool {
	for _, fn := range g.api.Funcs {
		if fn.Watch {
			return true
		}
	}
	return false
}

func (g *serverGoGen) hasWatchOnlyFuncs() bool {
	for _, fn := range g.api.Funcs {
		if fn.Watch && fn.Method == "" {
			return true
		}
	}
	return false
}

// isBinaryWatch returns true if a watch function returns []u8 (binary data).
func (g *serverGoGen) isBinaryWatch(fn ast.Func) bool {
	if fn.Return == nil {
		return false
	}
	r := fn.Return
	return r.Kind == ast.TypeSlice && r.Elem != nil &&
		r.Elem.Kind == ast.TypePrimitive && r.Elem.Name == ast.PrimU8
}

// --- WatchCallbacks Interface ---

func (g *serverGoGen) emitWatchCallbacksInterface() {
	if !g.hasWatchOnlyFuncs() {
		return
	}
	ifaceName := toPascalCase(g.api.Name) + "WatchCallbacks"
	g.printf("// --- Watch Callbacks Interface ---\n\n")
	g.printf("// %s defines watch methods that modules must implement.\n", ifaceName)
	g.printf("type %s interface {\n", ifaceName)
	for _, fn := range g.api.Funcs {
		if !(fn.Watch && fn.Method == "") {
			continue
		}
		methodName := toPascalCase(fn.Name)
		if g.isBinaryWatch(fn) {
			// Binary watch: returns raw bytes + generation counter.
			g.printf("\t%s() ([]byte, uint64, error)\n", methodName)
		} else {
			// JSON watch: returns typed value.
			ret := g.goMethodReturn(fn)
			g.printf("\t%s() %s\n", methodName, ret)
		}
	}
	g.printf("}\n\n")
}

// --- Commands Function ---

// HasWatchFuncs reports whether the API has any @watch function. Used by the
// modcompile driver to gate the WS-client generation modes.
func HasWatchFuncs(api *ast.API) bool {
	for _, fn := range api.Funcs {
		if fn.Watch {
			return true
		}
	}
	return false
}

// isCommandFunc reports whether a function should be exposed as a WS command:
// not watch-only, not @publish, no out-params (complex multi-return), and no
// opaque-pointer params. A raw or function pointer cannot be marshaled from a
// remote JSON request, and exposing one would accept an arbitrary client-supplied
// pointer — such functions (e.g. callback registration) are cgo-local only.
func (g *serverGoGen) isCommandFunc(fn ast.Func) bool {
	return isRESTCommandFunc(fn)
}

// isRESTCommandFunc reports whether fn is dispatched over REST (a "command"):
// not a watch-only function (@watch with no @method — those are WebSocket),
// not a @publish producer, and with no out/opaque-ptr params (unmarshalable).
// The server dispatch and every generated REST client must agree on this set,
// or a client emits a method the server never serves (e.g. halcmd's watch_items
// was mis-emitted as a broken empty-path GET returning []PinInfo).
func isRESTCommandFunc(fn ast.Func) bool {
	if fn.Watch && fn.Method == "" {
		return false
	}
	if fn.Publish {
		return false
	}
	for _, p := range fn.Params {
		if isOpaquePtrParam(p) {
			return false
		}
		// An out param is normally unmarshalable, but the @rc_error shape gives
		// it a defined place on the wire: it is the response body, and the rc is
		// the status. The checker guarantees exactly one for a REST-routed func.
		if p.IsOut && !fn.RcError {
			return false
		}
	}
	if fn.RcError {
		if _, ok := rcErrorPayload(fn); !ok {
			return false
		}
	}
	return true
}

func (g *serverGoGen) emitCommands() {
	// Generate XxxCommands() that wraps all dispatch functions as WS CommandMeta.
	// This includes REST functions and WS-command-only functions.
	hasFuncs := false
	for _, fn := range g.api.Funcs {
		if g.isCommandFunc(fn) {
			hasFuncs = true
			break
		}
	}
	if !hasFuncs {
		return
	}

	apiPascal := toPascalCase(g.api.Name)
	ifaceName := apiPascal + "Callbacks"
	funcName := apiPascal + "Handlers"

	// Same @constraint validation as the REST dispatch — but call the shared
	// validate<Api><Fn> functions emitted once into _cgo.go (same package) rather
	// than re-emitting the checks and a duplicate set of compiled @regex vars
	// here (D8). ce is used only to generate the call expressions.
	ce := newConstraintEmitter(g.api)

	g.printf("// --- Go-native handlers (REST + WebSocket) ---\n\n")
	g.printf("// %s returns the dispatch set that calls the provider directly.\n", funcName)
	g.printf("//\n")
	g.printf("// Both REST and WS use this. Routing through the C callbacks struct instead\n")
	g.printf("// would cost the provider's error: that ABI has no error channel, so the\n")
	g.printf("// //export trampoline substitutes a zero value and the caller is told the\n")
	g.printf("// call succeeded. The C path remains for in-process cmod<->gomod calls,\n")
	g.printf("// which is the reason it exists.\n")
	g.printf("//\n")
	g.printf("// Funcs that are WS-commands-only carry no Method/Path; REST routing skips\n")
	g.printf("// those, so one set serves both surfaces.\n")
	g.printf("func %s(impl %s) []apiserver.FuncMeta {\n", funcName, ifaceName)
	g.printf("\treturn []apiserver.FuncMeta{\n")
	for _, fn := range g.api.Funcs {
		if !g.isCommandFunc(fn) {
			continue
		}
		// The handler calls the Go provider directly, so it sees the REST view:
		// an @rc_error func's payload out-param is its return value here, and
		// there is no rc to encode (the provider's error is the error).
		fn = restView(fn)
		methodName := toPascalCase(fn.Name)

		g.printf("\t\t{Name: %q, Method: %q, Path: %q, RTSafe: %t, Dispatch: func(_ unsafe.Pointer, req []byte) ([]byte, error) {\n",
			fn.Name, fn.Method, fn.Path, fn.RTSafe)

		// Unmarshal params if any
		if len(fn.Params) > 0 {
			g.printf("\t\t\tvar params struct {\n")
			for _, p := range fn.Params {
				fieldName := toPascalCase(p.Name)
				fieldType := g.toGoType(p.Type)
				// WS command params travel as JSON args (no encodeParams), so a
				// 64-bit param is string-encoded here too. See jsonStringOpt.
				g.printf("\t\t\t\t%s %s `json:\"%s%s\"`\n", fieldName, fieldType, p.Name, jsonStringOptParam(p))
			}
			g.printf("\t\t\t}\n")
			g.printf("\t\t\tif len(req) > 0 {\n")
			g.printf("\t\t\t\tif err := json.Unmarshal(req, &params); err != nil {\n")
			// Request-decode failure is a CLIENT error: wrap EINVAL so the REST
			// layer maps it to 400 (a bare raw error reads as a 500 provider
			// fault), keeping the json detail in the message. Same rule as the
			// other dispatch emitters — keep all copies identical.
			g.printf("\t\t\t\t\treturn nil, fmt.Errorf(\"%%w: %%v\", syscall.EINVAL, err)\n")
			g.printf("\t\t\t\t}\n")
			g.printf("\t\t\t}\n")

			// Validate IDL @constraints via the shared validator (no reindent
			// splicing of an inlined check block needed).
			if ce.needsValidation(fn) {
				g.printf("\t\t\tif verr := %s; verr != nil {\n\t\t\t\treturn nil, verr\n\t\t\t}\n", ce.validateCallExpr(fn, "params"))
			}
		}

		// Build call args
		args := make([]string, 0, len(fn.Params))
		for _, p := range fn.Params {
			args = append(args, "params."+toPascalCase(p.Name))
		}
		callArgs := strings.Join(args, ", ")

		// Call the interface method
		if fn.Return == nil {
			// Void method — no return values
			g.printf("\t\t\timpl.%s(%s)\n", methodName, callArgs)
			g.printf("\t\t\treturn nil, nil\n")
		} else {
			g.printf("\t\t\tresult, err := impl.%s(%s)\n", methodName, callArgs)
			g.printf("\t\t\tif err != nil {\n")
			g.printf("\t\t\t\treturn nil, err\n")
			g.printf("\t\t\t}\n")
			g.printf("\t\t\treturn json.Marshal(result)\n")
		}

		g.printf("\t\t}},\n")
	}
	g.printf("\t}\n")
	g.printf("}\n\n")

	// WS command metadata, derived from the same handlers rather than emitted a
	// second time — two independently generated copies of one dispatch body is
	// how REST and WS came to disagree about errors in the first place.
	cmdName := apiPascal + "Commands"
	g.printf("// %s generates WS command metadata from the callbacks implementation.\n", cmdName)
	g.printf("// Thin view over %s — same handlers, keyed by name only.\n", funcName)
	g.printf("func %s(impl %s) []apiserver.CommandMeta {\n", cmdName, ifaceName)
	g.printf("\tfuncs := %s(impl)\n", funcName)
	g.printf("\tcmds := make([]apiserver.CommandMeta, 0, len(funcs))\n")
	g.printf("\tfor i := range funcs {\n")
	g.printf("\t\tfn := funcs[i]\n")
	g.printf("\t\tcmds = append(cmds, apiserver.CommandMeta{\n")
	g.printf("\t\t\tName: fn.Name,\n")
	g.printf("\t\t\tHandler: func(req json.RawMessage) (json.RawMessage, error) {\n")
	g.printf("\t\t\t\tres, err := fn.Dispatch(nil, []byte(req))\n")
	g.printf("\t\t\t\treturn json.RawMessage(res), err\n")
	g.printf("\t\t\t},\n")
	g.printf("\t\t})\n")
	g.printf("\t}\n")
	g.printf("\treturn cmds\n")
	g.printf("}\n\n")
}

// --- Watch Registration ---

func (g *serverGoGen) emitWatchRegister() {
	if !g.hasWatchFuncs() {
		return
	}

	apiPascal := toPascalCase(g.api.Name)
	funcName := "Register" + apiPascal + "Watch"

	// Determine parameter type(s).
	hasWatchOnly := g.hasWatchOnlyFuncs()
	hasDualPurpose := false
	for _, fn := range g.api.Funcs {
		if fn.Watch && fn.Method != "" {
			hasDualPurpose = true
			break
		}
	}

	// Build parameter list.
	g.printf("// --- Watch Registration ---\n\n")
	params := "wreg *apiserver.WatchRegistry, instance string"
	if hasWatchOnly {
		params += ", watchImpl " + apiPascal + "WatchCallbacks"
	}
	if hasDualPurpose {
		params += ", impl " + apiPascal + "Callbacks"
	}
	params += ", commands []apiserver.CommandMeta"

	g.printf("// %s registers WebSocket watch functions and commands.\n", funcName)
	g.printf("func %s(%s) {\n", funcName, params)
	g.printf("\twreg.Register(&apiserver.WatchAPI{\n")
	g.printf("\t\tAPIName:  %q,\n", g.api.Name)
	g.printf("\t\tInstance: instance,\n")

	// Watches
	g.printf("\t\tWatches: []apiserver.WatchFuncMeta{\n")
	for _, fn := range g.api.Funcs {
		if !fn.Watch {
			continue
		}
		methodName := toPascalCase(fn.Name)
		rate := g.parseRate(fn.WatchDefaultRate)

		// @watch_delta — per-connection diff on top-level JSON keys. Emitted
		// only when set so every existing watch registration stays byte-identical.
		delta := ""
		if fn.WatchDelta {
			delta = "Delta: true, "
		}

		if g.isBinaryWatch(fn) {
			// Binary watch — call WatchCallbacks method directly.
			g.printf("\t\t\t{Name: %q, DefaultRate: %s, BinaryWatch: watchImpl.%s},\n",
				fn.Name, rate, methodName)
		} else if fn.Method == "" {
			// Watch-only JSON — wrap WatchCallbacks method.
			g.printf("\t\t\t{Name: %q, DefaultRate: %s, %sWatch: func() (json.RawMessage, error) {\n",
				fn.Name, rate, delta)
			g.printf("\t\t\t\tresult, err := watchImpl.%s()\n", methodName)
			g.printf("\t\t\t\tif err != nil { return nil, err }\n")
			g.printf("\t\t\t\treturn json.Marshal(result)\n")
			g.printf("\t\t\t}},\n")
		} else {
			// Dual-purpose (REST + watch) — wrap Callbacks method.
			g.printf("\t\t\t{Name: %q, DefaultRate: %s, %sWatch: func() (json.RawMessage, error) {\n",
				fn.Name, rate, delta)
			g.printf("\t\t\t\tresult, err := impl.%s()\n", methodName)
			g.printf("\t\t\t\tif err != nil { return nil, err }\n")
			g.printf("\t\t\t\treturn json.Marshal(result)\n")
			g.printf("\t\t\t}},\n")
		}
	}
	g.printf("\t\t},\n")

	// Commands
	g.printf("\t\tCommands: commands,\n")
	g.printf("\t})\n")
	g.printf("}\n")
}

// parseRate converts a duration string like "100ms" or "50ms" to Go code.
func (g *serverGoGen) parseRate(rate string) string {
	if rate == "" {
		return "100 * time.Millisecond"
	}
	if strings.HasSuffix(rate, "ms") {
		ms := strings.TrimSuffix(rate, "ms")
		return ms + " * time.Millisecond"
	}
	if strings.HasSuffix(rate, "s") {
		s := strings.TrimSuffix(rate, "s")
		return s + " * time.Second"
	}
	return "100 * time.Millisecond"
}
